### ISSUE TITLE
[Device] vima smart lock

### ISSUE THREAD

**Issue by berkcan1453** [itavero/homebridge-z2m#101]
**Device description**
Which device would you like to be supported in this plugin?

**Supported in Zigbee2MQTT?**
Is this device already supported by Zigbee2MQTT / zigbee-herdsman-converters?
If this is NOT the case, please add support for the device there first.
Read there manual on [How to support new devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html) for more information.
If this is the case, please provide the version in which support is present/added.

**Device model / Exposes information**
Provide the device model (also known as [exposes information](https://www.zigbee2mqtt.io/information/exposes)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by Zigbee2MQTT.

```json
please put the device model JSON in this code block
```

**Missing features/functionality**
Please describe the features/functionality of this device that are currently not exposed to HomeKit via this plugin.

**Suggested services and characteristics**
For each of the missing features, please mention to which HomeKit Services and Characteristics it should be mapped.
The [Homebridge Plugin Development documentation](https://developers.homebridge.io/) provides a nice overview of the standard HomeKit services and characteristics.
Note that some manufacturers also use custom services and characteristics (the Elgato Eve products for instance), which could also be mimicked if they have been reverse engineered.

**Comment by itavero** [comment]
@berkcan1453 Can you please fill in the data requested in the template?

**Comment by itavero** [comment]
@berkcan1453 Can you please stop creating all these duplicate issues and just update this issue instead?

**Comment by itavero** [comment]
I reckon this question is about support for the [Xiaomi A6121](https://www.zigbee2mqtt.io/devices/A6121.html)?

As far as I can tell it's not exposed as a typical lock, looking at the [device page on the Zigbee2MQTT website](https://www.zigbee2mqtt.io/devices/A6121.html).
This means that it is not supported by the current `lock` integration, but of course support an probably be added.

However, I would need to know what the MQTT messages are that can be expected from this lock and how the related to the [Lock Mechanism](https://developers.homebridge.io/#/service/LockMechanism) service and its characteristics in HomeKit.
I had a quick look at the Zigbee converter for the device in [Koenkk/zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters) and I think this will be very challenging.

**Comment by berkcan1453** [comment]
Thanks for your helps. I guess I'll need to switch to home assistant for this

**Comment by itavero** [comment]
@berkcan1453 That might be a possibility, or perhaps the [homebridge-mqttthing](https://www.npmjs.com/package/homebridge-mqttthing) plugin. Or you can provide the data requested above, which would allow me to see if it is feasible to add it to homebridge-z2m.

If you decide to use Home Assistant or another plugin and are no longer interested in seeing support for this device in this particular plugin, please close this issue so it is clear to me if it is still an active request or not.

**Comment by itavero** [comment]
Marking this issue as stale, as there hasn't been any activity for a while. It will automatically close in a couple of weeks, unless new comments are placed.
