### ISSUE TITLE
[Feature] I want to help you :)

### ISSUE THREAD

**Issue by Kepro** [itavero/homebridge-z2m#11]
Hi man, I want to help you, (I was on my way to create this plugin then I found you already did it :D) 

what do you want to improve in codebase / roadmap? 

I will fix Typescript definition for sure for you :) 

Let me know what do you think

**Comment by itavero** [comment]
If there are open issues you can help with, be sure to leave a comment on them when you start working on it and you're welcome to open up a pull request for those.
