### ISSUE TITLE
[Feature] Exclude keys for a specific device

### ISSUE THREAD

**Issue by Kepro** [itavero/homebridge-z2m#12]
I have several xiaomi smart sockets model `lumi.plug` and this plugs also have temperature and now my temperature in room is based on `lumi.sens` and `lumi.plug` :/ and I don't want to exclude `lumi.plug` as I want to control it :) 

maybe something that we can work on it as "first task" that I will help

**Comment by itavero** [comment]
My initial thought was to make it possible to put a JSON object into `devices.exclude` (but keep the possibility to just use an array). That way you could either use the array to ignore entire devices, or specify specific keys to ignore.

However, I would not be surprised if there will be more things to configure on a device level in the future.
Therefore my suggestion would be to make the configuration like this:
```json
{
   "platform": "zigbee2mqtt",
   "mqtt": {
      "base_topic": "zigbee2mqtt",
      "server": "mqtt://localhost:1883"
   },
   "devices": {
      "exclude": [
         "0x1234567890abcdef"
      ],
      "0xabcdef1234567890": {
         "exclude": [
           "key_to_exclude_here"
         ]
      }
   }
}
```

So next to `exclude` you'd also be able to put in the friendly name or IEEE address and put device specific configuration in there.

I'm open for accepting a PR for this, or I'll look at this myself when I have time.

**Comment by itavero** [comment]
In order for this to still make sense of the configuration screen in `homebridge-config-ui-x`, I will have to change the way how devices are excluded too.

I'll try to implement this in the next few days (depending on the local weather, to be honest).

**Comment by itavero** [comment]
@Kepro I've implemented the feature you suggested. Are you able to test the changes on the `exclude-keys` branch, to see if this works for your use case?

**Comment by itavero** [comment]
@Kepro If you are unable to verify it, that's also fine, then I'll probably just include it in the next release.

**Comment by Kepro** [comment]
@itavero will try on the weekend! :)

**Comment by itavero** [comment]
@Kepro Did it work for you?

**Comment by itavero** [comment]
@Kepro I'll probably make a release this week with this change included.
