### ISSUE TITLE
Zemismart ZM25TQ Curtain Not responding via HomeKit

### ISSUE THREAD

**Issue by EddieDSuza** [itavero/homebridge-z2m#129]
Please use the template and fill in all the data requested below!

**Describe the bug**
Successfully added the device to Z2M frontend. The device does respond using the frontend but any changes to the state of the device provides an error in the log which is below

```
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":41,"motor_speed":false,"position":0,"running":false,"state":"CLOSE"}'
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":41,"motor_speed":false,"position":0,"running":false,"state":"CLOSE"}'
Info Setting motor speed to 0
Warning TuYa_cover_control: Unhandled DP #12 for _TZE200_fzo2pocs: {"status":0,"transid":1,"dp":12,"datatype":5,"fn":0,"data":{"type":"Buffer","data":[1]}}
Warning TuYa_cover_control: Unhandled DP #103 for _TZE200_fzo2pocs: {"status":0,"transid":1,"dp":103,"datatype":1,"fn":0,"data":{"type":"Buffer","data":[0]}}
Warning TuYa_cover_control: Unhandled DP #104 for _TZE200_fzo2pocs: {"status":0,"transid":1,"dp":104,"datatype":1,"fn":0,"data":{"type":"Buffer","data":[0]}}
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":41,"motor_speed":false,"position":0,"running":false,"state":"CLOSE"}'
Warning TuYa_cover_control: Unhandled DP #106 for _TZE200_fzo2pocs: {"status":0,"transid":1,"dp":106,"datatype":4,"fn":0,"data":{"type":"Buffer","data":[0]}}
```

**Related devices**
Are you experiencing this behavior with a particular device?
Zemismart ZM25TQ Curtain
**Expected behavior**
No device response when accessing the device from the Home App

**MQTT messages**
```
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":40,"motor_speed":false,"position":77,"running":true,"state":"OPEN"}'
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":40,"motor_speed":false,"position":100,"running":true,"state":"OPEN"}'
Error No converter available for 'get' 'position' (0)
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":40,"motor_speed":false,"position":16,"running":true,"state":"OPEN"}'
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":40,"motor_speed":false,"position":0,"running":true,"state":"CLOSE"}'
Error No converter available for 'get' 'position' (0)
```
* Messages published by this plugin that might be related to your issue (can also be seen in the homebridge logs)
```
[31/03/2021, 17:51:25] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x5c0272fffea4d0b2/set': '{"position":46}'
[31/03/2021, 17:51:26] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x5c0272fffea4d0b2/set': '{"position":54}'
[31/03/2021, 17:51:26] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x5c0272fffea4d0b2/set': '{"position":100}'
[31/03/2021, 17:51:27] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x5c0272fffea4d0b2/get': '{"position":0}'
[31/03/2021, 17:51:39] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x5c0272fffea4d0b2/set': '{"position":37}'
[31/03/2021, 17:51:40] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x5c0272fffea4d0b2/set': '{"position":0}'
[31/03/2021, 17:51:41] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x5c0272fffea4d0b2/get': '{"position":0}'
```
**Versions used**
Please provide the version of the following pieces of software:
 - This plugin -  v1.1.3
 - Homebridge - v1.3.4
 - Zigbee2MQTT (can be found in MQTT topic `zigbee2mqtt/bridge/info`) - 1.18.1-dev commit: f8f79d3
 - Homebridge Config UI X (if applicable) - v4.41.0
<img width="1398" alt="Screen Shot 2021-03-31 at 17 59 21" src="https://user-images.githubusercontent.com/52710883/113210644-d729ad00-924a-11eb-8101-c7db4b83a8bf.png">

**Comment by itavero** [comment]
Can you also add the entry for the device, from the `zigbee2mqtt/bridge/devices` topic?

**Comment by EddieDSuza** [comment]
`Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure_reporting', payload '{"data":{},"error":"ConfigureReporting 0x5c0272fffea4d0b2/1 closuresShadeCfg([{\"attribute\":\"status\",\"minimumReportInterval\":60,\"maximumReportInterval\":3600,\"reportableChange\":0}], {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (payload is not iterable)","status":"error","transaction":"w0nou-6"}'`

Do I Need to toggle something here ? Please let me know.
<img width="1276" alt="Screen Shot 2021-04-01 at 11 35 57" src="https://user-images.githubusercontent.com/52710883/113310278-70ee6a00-92de-11eb-8ccc-16c18f04c47f.png">

**Comment by EddieDSuza** [comment]
```
state = online
info = {"commit":"f8f79d3","config":{"\\n\\nadvanced:\\n network_key":"GENERATE","advanced":{"adapter_concurrent":null,"adapter_delay":null,"availability_blacklist":[],"availability_blocklist":[],"availability_passlist":[],"availability_timeout":0,"availability_whitelist":[],"cache_state":true,"cache_state_persistent":true,"cache_state_send_on_startup":true,"channel":11,"elapsed":false,"ext_pan_id":[2…
devices = [{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genTime","genOta"],"output":["genPowerCfg","genPollCtrl","ssIasZone"]},"configured_reportings":[]},"242":{"bindings":[],"clusters":{"input":[],"output":["greenPower"]},"configured_reportings":[]}},"friendly_name":"Coordinator","ieee_address":"0x00212effff05def7","interview_completed":true,"interviewing":false,"net…
groups = []
config = {"commit":"f8f79d3","coordinator":{"meta":{"maintrel":0,"majorrel":38,"minorrel":102,"product":0,"revision":"0x26660700","transportrev":0},"type":"ConBee2/RaspBee2"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.18.1-dev"}
extensions = []
logging = {"level":"warning","message":"TuYa_cover_control: Unhandled DP #106 for _TZE200_fzo2pocs:\n {\"status\":0,\"transid\":1,\"dp\":106,\"datatype\":4,\"fn\":0,\"data\":{\"type\":\"Buffer\",\"data\":[0]}}"}
```

**Comment by EddieDSuza** [comment]
`[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genTime","genOta"],"output":["genPowerCfg","genPollCtrl","ssIasZone"]},"configured_reportings":[]},"242":{"bindings":[],"clusters":{"input":[],"output":["greenPower"]},"configured_reportings":[]}},"friendly_name":"Coordinator","ieee_address":"0x00212effff05def7","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type":"Coordinator"},{"date_code":"","definition":{"description":"Curtain motor/roller blind motor/window pusher/tubular motor","exposes":[{"features":[{"access":3,"name":"state","property":"state","type":"binary","value_off":"CLOSE","value_on":"OPEN"},{"access":3,"description":"Position of this cover","name":"position","property":"position","type":"numeric","value_max":100,"value_min":0}],"type":"cover"},{"features":[{"access":3,"description":"Motor speed","name":"motor_speed","property":"motor_speed","type":"numeric","value_max":255,"value_min":0}],"name":"options","property":"options","type":"composite"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0601_cover","supports_ota":false,"vendor":"TuYa"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genTime","genGroups","genScenes","manuSpecificTuya"],"output":["genOta"]},"configured_reportings":[]}},"friendly_name":"Curtain ","ieee_address":"0x5c0272fffea4d0b2","interview_completed":true,"interviewing":false,"model_id":"TS0601","network_address":26183,"power_source":"Mains (single phase)","supported":true,"type":"Router"},{"date_code":"20200519","definition":{"description":"Smart Zigbee 3.0 light controller","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"HGZB-01","supports_ota":false,"vendor":"Nue / 3A"},"endpoints":{"1":{"bindings":[{"cluster":"genOnOff","target":{"endpoint":1,"ieee_address":"0x00212effff05def7","type":"endpoint"}}],"clusters":{"input":["genBasic","genIdentify","genGroups","genScenes","genOnOff"],"output":[]},"configured_reportings":[{"attribute":"onOff","cluster":"genOnOff","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0}]}},"friendly_name":"lampshade","ieee_address":"0x086bd7fffe1cb288","interview_completed":true,"interviewing":false,"model_id":"LXN59-1S7LX1.0","network_address":4023,"power_source":"Mains (single phase)","supported":true,"type":"Router"}]`

**Comment by EddieDSuza** [comment]
`
[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genTime","genOta"],"output":["genPowerCfg","genPollCtrl","ssIasZone"]},"configured_reportings":[]},"242":{"bindings":[],"clusters":{"input":[],"output":["greenPower"]},"configured_reportings":[]}},"friendly_name":"Coordinator","ieee_address":"0x00212effff05def7","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type":"Coordinator"},{"date_code":"","definition":{"description":"Curtain motor/roller blind motor/window pusher/tubular motor","exposes":[{"features":[{"access":3,"name":"state","property":"state","type":"binary","value_off":"CLOSE","value_on":"OPEN"},{"access":3,"description":"Position of this cover","name":"position","property":"position","type":"numeric","value_max":100,"value_min":0}],"type":"cover"},{"features":[{"access":3,"description":"Motor speed","name":"motor_speed","property":"motor_speed","type":"numeric","value_max":255,"value_min":0}],"name":"options","property":"options","type":"composite"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0601_cover","supports_ota":false,"vendor":"TuYa"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genTime","genGroups","genScenes","manuSpecificTuya"],"output":["genOta"]},"configured_reportings":[]}},"friendly_name":"Curtain ","ieee_address":"0x5c0272fffea4d0b2","interview_completed":true,"interviewing":false,"model_id":"TS0601","network_address":26183,"power_source":"Mains (single phase)","supported":true,"type":"Router"},{"date_code":"20200519","definition":{"description":"Smart Zigbee 3.0 light controller","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"HGZB-01","supports_ota":false,"vendor":"Nue / 3A"},"endpoints":{"1":{"bindings":[{"cluster":"genOnOff","target":{"endpoint":1,"ieee_address":"0x00212effff05def7","type":"endpoint"}}],"clusters":{"input":["genBasic","genIdentify","genGroups","genScenes","genOnOff"],"output":[]},"configured_reportings":[{"attribute":"onOff","cluster":"genOnOff","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0}]}},"friendly_name":"lampshade","ieee_address":"0x086bd7fffe1cb288","interview_completed":true,"interviewing":false,"model_id":"LXN59-1S7LX1.0","network_address":4023,"power_source":"Mains (single phase)","supported":true,"type":"Router"}]

`

**Comment by itavero** [comment]
Looking at the product information, it appears that my implementation currently does not check the `access` property for the `position`.
For the IKEA blinds, I actively poll the position, as it does not broadcast it frequently (which looks weird in HomeKit, as it will say that it is still moving until it receives the same position twice or something like that).

I can get rid of this automatic polling stuff, but I'm not sure if the behavior itself will improve or if I even can improve it.

**Comment by EddieDSuza** [comment]
Is there a way of getting rid of it and testing if it works. I don't mind doing it. 😇

**Comment by itavero** [comment]
The code has to be edited for that. 

In `src/converters/cover.ts`, the polling done via the `updateTimer` should only be done if `exposesCanBeGet(positionExpose) === true`.

However, HomeKit expects to see the same position twice (or some magic like that), before it considers the cover to have stopped moving.

By the way, the warnings about the `Unhandled DP` can probably ignored (that's also a Zigbee2MQTT log, not a log from homebridge-z2m).

Just to confirm: you don't see the cover move physically when controlling it via HomeKit?
If you send the MQTT messages manually to change the position, does it work then?

**Comment by EddieDSuza** [comment]
To confirm - I Don't see the cover move physically when controlling it via HomeKit

When sending manually MQTT messages to OPEN or CLOSE or STOP  - it does react with the messages and the motor turns. Here are the LOGS from the frontend.

```
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":193,"motor_speed":false,"position":0,"running":false,"state":"CLOSE"}'
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":193,"motor_speed":false,"position":0,"running":false,"state":"CLOSE"}'
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":193,"motor_speed":false,"position":0,"running":false,"state":"CLOSE"}'
Info MQTT publish: topic 'zigbee2mqtt/Curtain ', payload '{"linkquality":193,"motor_speed":false,"position":12,"running":false,"state":"OPEN"}'
```

**Comment by itavero** [comment]
This plugin uses the `position` attribute. According to the exposes information, this can be set.

If I understand you correctly, this doesn't actually work. In that case, there's probably a bug in Zigbee2MQTT (either `position` should work or it shouldn't be in the exposes information).

An implementation that only fully opens and closes using the other property, might also be possible. However, at this point there's no way for the plugin to distinguish if it should/can use the `position` attribute or not.

**Comment by EddieDSuza** [comment]
Is there a work around or fix ? If not - will need to return the device and look for an alternative to blinds. 

Out of curiosity - what would be the command to set a `position` in MQTT manually ?

**Comment by itavero** [comment]
> what would be the command to set a `position` in MQTT manually ?

As shown in the logs: publish to `zigbee2mqtt/0x5c0272fffea4d0b2/set`: `{"position":100}`

**Comment by EddieDSuza** [comment]
Didn't work. 

Well to wrap up this issue - can the device be functional in HomeKit or no via a plugin update ? 

If not will need to look for another similar solution that will work 😇

Your thoughts and as always appreciate your time on this.

**Comment by itavero** [comment]
If the `position` can't be set properly via Zigbee2MQTT, then I don't think it will work.
Perhaps also report a bug in the Zigbee2MQTT project that the `position` cannot be set for this particular device.

Of course an implementation for just fully opened/closed using the `state` might still be possible, but then Zigbee2MQTT should also be updated so that it does not show the  `position` as "settable" for this device (as it apparently does not work).

**Comment by EddieDSuza** [comment]
Awesome Thanks for the info - will go ahead an open issue in the Zigbee2MQTT project

**Comment by EddieDSuza** [comment]
So I have been doing some research on this and it looks like in the default [device.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js) there is no mention about the support 

**supports: 'open, close, stop, position',**

Any idea on how to add this for HomeBridge - may be its a try cause most of the issues for Z2M are related to HA.

Thanks

**Comment by EddieDSuza** [comment]
So I have been doing some research on this and it looks like in the default [device.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js) there is no mention about the support syntax for this

**supports: 'open, close, stop, position',**

Any idea on how to add this for HomeBridge - may be its a try cause most of the issues for Z2M are related to HA.

Thanks

**Comment by itavero** [comment]
This information is generated from the `exposes` information: https://github.com/Koenkk/zigbee-herdsman-converters/blob/e3902f144238fa5a00027c02db33c75e5ad92c12/devices.js#L1670-L1677

**Comment by EddieDSuza** [comment]
I just seen this [issue](https://github.com/Koenkk/zigbee2mqtt/issues/4465#issuecomment-701935713) and in his configuration there is this support values added.

Any idea on how I can update the device.js within terminal for Homebridge ?

**Comment by itavero** [comment]
> I just seen this [issue](https://github.com/Koenkk/zigbee2mqtt/issues/4465#issuecomment-701935713) and in his configuration there is this support values added.
> 
> Any idea on how I can update the device.js within terminal for Homebridge ?

@EddieDSuza Somehow I missed your comment. Is this still an issue you are facing or has it been resolved with newer versions of Zigbee2MQTT?
