### ISSUE TITLE
[Device] Support Hampton bay 99432 fan control

### ISSUE THREAD

**Issue by joshuata** [itavero/homebridge-z2m#132]
**Device description**
Support the fan control for the Hampton Bay Universal wink enabled white ceiling fan premier remote control (99432)

**Supported in Zigbee2MQTT?**
This is already supported in z2m.

**Device model / Exposes information**

```json
{
          "definition": {
            "description": "Universal wink enabled white ceiling fan premier remote control",
            "exposes": [
                {
                    "features": [
                        {
                            "access": 7,
                            "description": "On/off state of this light",
                            "name": "state",
                            "property": "state",
                            "type": "binary",
                            "value_off": "OFF",
                            "value_on": "ON",
                            "value_toggle": "TOGGLE"
                        },
                        {
                            "access": 7,
                            "description": "Brightness of this light",
                            "name": "brightness",
                            "property": "brightness",
                            "type": "numeric",
                            "value_max": 254,
                            "value_min": 0
                        }
                    ],
                    "type": "light"
                },
                {
                    "features": [
                        {
                            "access": 7,
                            "description": "On/off state of this fan",
                            "name": "state",
                            "property": "fan_state",
                            "type": "binary",
                            "value_off": "OFF",
                            "value_on": "ON"
                        },
                        {
                            "access": 7,
                            "description": "Mode of this fan",
                            "name": "mode",
                            "property": "fan_mode",
                            "type": "enum",
                            "values": [
                                "off",
                                "low",
                                "medium",
                                "high",
                                "on",
                                "auto",
                                "smart"
                            ]
                        }
                    ],
                    "type": "fan"
                },
                {
                    "access": 1,
                    "description": "Link quality (signal strength)",
                    "name": "linkquality",
                    "property": "linkquality",
                    "type": "numeric",
                    "unit": "lqi",
                    "value_max": 255,
                    "value_min": 0
                }
            ],
            "model": "99432",
            "supports_ota": false,
            "vendor": "Hampton Bay"
        }
```

**Missing features/functionality**
Currently only the light aspects of the controller are exposed to HomeKit. It does not expose control to turn the fan on/off or adjust the speed.

**Suggested services and characteristics**
This should map to the Fan service type with the On and Rotation Speed characteristics

**Comment by itavero** [comment]
Can you elaborate a bit on the different modes?
How do the `on` and `off` mode relate to the `state`?
What's the difference between `smart` and `auto`?

It should probably be mapped to the characteristics of the [Fanv2 service](https://developers.homebridge.io/#/service/Fanv2), but it seems that the mapping isn't straight forward.

**Comment by joshuata** [comment]
The levels are a little strange but it should be roughly `off`->0%, `low`->25%, `medium`->50%, `high`->75%, `on`->100%.
Those aren't RPM accurate, but that is evenly spaced intervals so we could make the adjustments snap to 25% increments.

`smart` dynamically changes the speed between settings to gently stir up the air, but I'm not sure that this is a needed option for the adapter since other fan controllers don't map dynamic modes to homekit either.

And I have not been able to figure out what the `auto` mode does specifically. Turning the device on with `fan_state=auto` does not start the fan spinning. From looking at other Hampton Bay controllers it may be thermostat controlled, but require a different remote than the one that ships with the device.

Btw, I'm working on a mvp for a Fanv2 creator/handler, but it will probably be a little messy since I don't have a ton of experience with this codebase. I'm focussing on the On/Off and speed characteristics since there aren't any other z2m devices that use the others as far as I can find.

**Comment by joshuata** [comment]
As I'm looking into it, it may be worth addressing some underlying issues first:
1. Fixing the levels matching in z2m and homeassistant. Currently it only matches `off`, `low`, `medium`, `high`, but doesn't include the `on` level. It seems like mapping power levels correctly makes more sense at the lower levels like z2m rather than this plugin
2. Fixing random dropouts. This was already a pretty flaky device, and I can't keep it stable on z2m for 24 hours. I'm pairing the critical one back to zha while I troubleshoot the second. I suspect it is a problem with routing messages, but it is definitely slowing my progress.
