### ISSUE TITLE
[Bug] Incorrect mapping for 'TRADFRI SHORTCUT Button'.

### ISSUE THREAD

**Issue by EdwardChamberlain** [itavero/homebridge-z2m#138]
**Describe the bug**
The switch has a single 'button' on it but presents in homekit as having 3 buttons with 'single press' actions. 'button 1' is triggered by a single short press, button 3 is triggered by a long press, button 2 is triggered when the long press is released (I assume this is some interpretation of a dimmer switch?)

**Related devices**
TRADFRI SHORTCUT Button

**To Reproduce**
Standard install 

**Expected behavior**
A single button presented to homekit with 'short press' and 'long press' actions attached. 

**MQTT messages**
Short press, long press, then release long press. 
```
[32mZigbee2MQTT:info [39m 2021-04-10 06:32:54: MQTT publish: topic 'zigbee2mqtt/Night Button', payload '{"battery":60,"linkquality":86,"update":{"state":"idle"},"update_available":false}'
[32mZigbee2MQTT:info [39m 2021-04-10 07:28:59: MQTT publish: topic 'zigbee2mqtt/Spare Socket', payload '{"linkquality":55,"power_on_behavior":"off","state":"OFF","update":{"state":"idle"},"update_available":false}'
[32mZigbee2MQTT:info [39m 2021-04-10 08:25:55: MQTT publish: topic 'zigbee2mqtt/Night Button', payload '{"battery":34,"linkquality":65,"update":{"state":"idle"},"update_available":false}'
[32mZigbee2MQTT:info [39m 2021-04-10 08:25:55: MQTT publish: topic 'zigbee2mqtt/Night Button', payload '{"battery":34,"linkquality":65,"update":{"state":"idle"},"update_available":false}'
[32mZigbee2MQTT:info [39m 2021-04-10 08:25:55: MQTT publish: topic 'zigbee2mqtt/Night Button', payload '{"action":"on","battery":34,"linkquality":68,"update":{"state":"idle"},"update_available":false}'
[32mZigbee2MQTT:info [39m 2021-04-10 08:26:10: MQTT publish: topic 'zigbee2mqtt/Night Button', payload '{"action":"brightness_move_up","action_rate":83,"battery":34,"linkquality":68,"update":{"state":"idle"},"update_available":false}'
[32mZigbee2MQTT:info [39m 2021-04-10 08:26:16: MQTT publish: topic 'zigbee2mqtt/Night Button', payload '{"action":"brightness_stop","battery":34,"linkquality":68,"update":{"state":"idle"},"update_available":false}'
[32mZigbee2MQTT:info [39m 2021-04-10 08:26:16: MQTT publish: topic 'zigbee2mqtt/Night Button', payload '{"action":"brightness_stop","battery":34,"linkquality":68,"update":{"state":"idle"},"update_available":false}'
```

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin: v1.1.3
 - Homebridge: v1.3.4
 - Zigbee2MQTT (can be found in MQTT topic `zigbee2mqtt/bridge/info`): v1.18.2

**Comment by itavero** [comment]
As you can see, the different values for `action` don't really have a logic relation, so it is not possible for the plugin to know what the physical device looks like.

The only way to improve on this, is by having users manually define a mapping for each `action` value to a HomeKit switch event.
The goal of this plugin however is to not need any configuration for individual devices.

Functionally there's also no difference between having three buttons in HomeKit or having them combined.

By the way, the mapping is also reported in the Homebridge log upon start up.
