### ISSUE TITLE
[Bug] Aqara Temperature and Humidity Sensor - "Not supported" on Homekit

### ISSUE THREAD

**Issue by BladesKnight** [itavero/homebridge-z2m#14]
Hi there,

I just got one of the Temperature sensors for my home and Homekit says that it's not supported.
https://www.aqara.com/us/temperature_humidity_sensor.html

Zigbee2MQTT: https://www.zigbee2mqtt.io/devices/WSDCGQ11LM.html

From zigbee2mqtt.service:
MQTT publish: topic 'zigbee2mqtt/Aqara TempHumidity Sensor', payload '{"battery":100,"humidity":47.95,"linkquality":39,"pressure":1003.9,"temperature":28.06,"voltage":3225}'

Is it possible to add this so that it shows on Homekit as Humidity, Pressure and Temperature?

Thanks for all that you do!

**Comment by itavero** [comment]
For me these work without any problem (note that the pressure sensor is not in the latest release, but will be in the next release, if I'm not mistaking).
Are you sure that this message was published while the Homebridge plugin was running?

And by "not supported" you mean that it does not show any sensor values, right?

Also, can you please provide all the version numbers of the software applications involved (as was also in the Bug template)?

**Comment by BladesKnight** [comment]
I jumped the gun too soon! Sorry...

Rebooted everything in sight and all is working now after 10 mins or so...

Ok to close now. Thank you once again!

**Comment by itavero** [comment]
No problem. 😉
