### ISSUE TITLE
[Device] Lidl Powerstrip Smart USB Extension Lead TS011F

### ISSUE THREAD

**Issue by mickeymci** [itavero/homebridge-z2m#141]
Please use the template and fill in all the data requested below!

**Device description**
Product name: Smart USB Extension Lead / Smart Connect Strip
Manufacturer: In Z2M: _TZ3000_vmpbygs5, on the device: SilverCrest
Model identifier: In Z2M: TS011F, on the device: SPSZ 3 A1 and TY-HG06338-UK
Device type : Smart Plug / Power Strip
**Supported in Zigbee2MQTT?**
Yes in v1.16:  HG06338 Silvercrest 3 gang switch

Is this device already supported by Zigbee2MQTT / zigbee-herdsman-converters?

Yes in v1.16:  HG06338 Silvercrest 3 gang switch
https://z2m.dev/devices/lidl/hg06338.html

If this is NOT the case, please add support for the device there first.
Read there manual on [How to support new devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html) for more information.
If this is the case, please provide the version in which support is present/added.

**Device model / Exposes information**
Provide the device model (also known as [exposes information](https://www.zigbee2mqtt.io/information/exposes)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by Zigbee2MQTT.

```json
please put the device model JSON in this code block
```

**Missing features/functionality**
Device appears as a single socket in homebridge, other two socket do not appear so are not controllable.  

**Suggested services and characteristics**
For each of the missing features, please mention to which HomeKit Services and Characteristics it should be mapped.
The [Homebridge Plugin Development documentation](https://developers.homebridge.io/) provides a nice overview of the standard HomeKit services and characteristics.
Note that some manufacturers also use custom services and characteristics (the Elgato Eve products for instance), which could also be mimicked if they have been reverse engineered.

**Comment by itavero** [comment]
Please provide the device model (also known as [exposes information](https://www.zigbee2mqtt.io/information/exposes)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by Zigbee2MQTT.

**Comment by mickeymci** [comment]
Hi 
Sorry for the delay.  I looked at the info you requested and i'm confused.  I did find the following on a HA zigbee2mqtt forum:

I home this helps, if not, no worries I appreciate all the work you've done that at least let me load the switch.

the below came for the [following:](https://community.home-assistant.io/t/silvercrest-lidl-smarthome/243561/64)


// Silvercrest
    {
        fingerprint: [
            {modelID: 'TS011F', manufacturerName: '_TZ3000_wzauvbcs'},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_1obwwnmq'},
        ],
        model: 'SPSZ 3 A1',
        vendor: 'Silvercrest',
        description: '3 gang switch, possibly with USB',
        exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'), e.switch().withEndpoint('l3')],
        extend: generic.switch,
        meta: {configureKey: 1, multiEndpoint: true},
        configure: async (device, coordinatorEndpoint) => {
            for (const ID of [1, 2, 3]) {
                await bind(device.getEndpoint(ID), coordinatorEndpoint, ['genOnOff']);
            }
        },
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2, 'l3': 3};
        },
    },

**Comment by itavero** [comment]
It's a bit a harder for me to write a test from this code, rather than the data from the MQTT message published to the `zigbee2mqtt/bridge/devices` topic by Zigbee2MQTT.

Did you see any errors or warnings in the Homebridge log upon startup?

I would expect this to just work, but unfortunately I do not own a device that exposes multiple Switch endpoints.
I'll have another look at the code to see if I can spot a mistake.
