### ISSUE TITLE
zigbee2mqtt groups

### ISSUE THREAD

**Issue by Luftloch80** [itavero/homebridge-z2m#166]
Hey. 
is it possible to add devices which are defined as group in configuration.yaml?
thx

**Comment by itavero** [comment]
At the moment, this is not supported.

To be honest, I haven't used this feature in Zigbee2MQTT yet myself, so I don't have enough knowledge or insight in this area to determine how this could be integrated/exposed.

Feel free to investigate and make a proposal on how it can be implemented.

**Comment by Luftloch80** [comment]
one possible implementation would be to define the group name and the type of device manually in Config.JSON and the plugin grabs necessary data

**Comment by itavero** [comment]
I think the groups and it's members can be retrieved from `zigbee2mqtt/bridge/groups`, so the plugin could use the `exposes` information of the members to find overlapping services/characteristics.

I am wondering what you are trying to achieve with this, because groups can also be made within HomeKit (which is what I use).
Is it just about reducing the amount of Zigbee messages and having a group of devices respond more or less simultaneously?

**Comment by Luftloch80** [comment]
And the other reason Is That multiple lights in HomeKit groups are Not change at the Same time But with some ms Delay. 
it is just for the beauty of Perfection

**Comment by itavero** [comment]
Would that also mean that, if an accessory (device) is controlled/exposed to HomeKit via a group, you would no longer expect the individual device to be visible in HomeKit?

**Comment by chrisjansky** [comment]
Hi, I am trying to use https://www.zigbee2mqtt.io/devices/E1524_E1810.html with a group of IKEA Tradfri bulbs. Judging from this thread it is not possible?

**Comment by itavero** [comment]
> Hi, I am trying to use https://www.zigbee2mqtt.io/devices/E1524_E1810.html with a group of IKEA Tradfri bulbs. Judging from this thread it is not possible?

If you are just trying to control the bulbs with this remote, I would suggest to pair the remote directly to the group of bulbs in Zigbee2MQTT.
This will work faster than going through Homebridge first and I think it will also leave the dimming/temperature change functions "intact".

As mentioned before, I haven't used groups myself, so I'm by no means an expert.
For pairing directly to the group in Zigbee2MQTT, you might want to try their documentation or ask for help on their Discord.

**Comment by vdebrist** [comment]
Dear @itavero , light grouped in zigbee2mqtt have group ID or friendly name, maybe it is possible to add a group with the friendly name as an additional device and copy controls from one device in this group (for example lights)? 

I have a lot of zigbee lamps, that include 4-5 bulbs, so when I group them in HomeKit, it's a flood by zigbee commands to each of the devices (especially when I am changing colour or brightness in Home.app), we can reduce it in 4-5 times with the help of groups. 

More detailed it's desribed in "groups" sections to the zigbee2mqtt. Link: https://www.zigbee2mqtt.io/guide/usage/groups.html#configuration . 

Now I need to use HASS to control lights in my home and not to spam zigbee channel. I believe you can add groups support to your plugin.

**Comment by itavero** [comment]
@vdebrist Please see #277 instead of replying to old, closed issues.
