### ISSUE TITLE
[Bug] homebridge Config UI freeze

### ISSUE THREAD

**Issue by ivanosh** [itavero/homebridge-z2m#169]
**Description**
Homebridge Config UI frozen when trying to open UI config of homebridge-z2m

**Related devices**
Google Chrome

**To Reproduce**
1. open `http://homebridge.local/plugins?installed=homebridge-z2m`
2. Chrome tab is frozen

**Versions used**
 - This plugin: 1.1.3
 - Homebridge: 1.3.4
 - Zigbee2MQTT: 1.18.3
 - Homebridge Config UI X: 4.41.1

**Comment by itavero** [comment]
I also use it with Chrome without any problems, so I'm going to need a bit more information in order to solve this.

* Does it work for other plug-ins?
* Do you see anything in the browser console log (accessable by pressing F12)?
* Any warnings or errors in the Homebridge logs?
* Can you share your current configuration?

**Comment by ivanosh** [comment]
Hello!
1. Yes, there is no problems with other plugins
2. `condition functionBody errored out on evaluation: return !model.devices[arrayIndices].exclude;`
3. Nothing
4. Here is full Config file: https://pastebin.com/0LDVFdEP

**Comment by itavero** [comment]
I'll see if a can reproduce this locally. I reckon it has to do with the fact that there is no `devices` entry, but since there won't be one after you've installed it, that should not cause it to crash.

**Comment by itavero** [comment]
I tried to reproduce it in Chrome Version 90.0.4430.212 (Official Build) (x86_64) on macOS (with the same plugin/homebridge/config-ui-x versions).
I do see the errors in the console, but the tab does not hang in my browser.

I think these console errors are not related to the behavior you are seeing, but unfortunately I also wouldn't know how to debug this browser stuff.
I reckon one of the other tabs in the browser developer tools might give you insight in that.
