### ISSUE TITLE
[Device] HEIMAN HS2WD-E Smart Siren

### ISSUE THREAD

**Issue by warevlc** [itavero/homebridge-z2m#175]
Hi there,

**Device description**
_Which device would you like to be supported in this plugin?_
The device is HEIMAN HS2WD-E Smart Siren, currently it appears in the z2m.dev supported devices but only the battery indicator.

**Supported in Zigbee2MQTT?**
_Is this device already supported by Zigbee2MQTT / zigbee-herdsman-converters?_
Yes, check [zigbee2mqtt dedicated entry](https://www.zigbee2mqtt.io/devices/HS2WD-E.html). I have been able to trigger the alarm from mqtt and also using the own zigbee2mqtt frontend web.

**Device model / Exposes information**
{"date_code":"2018.03.21","definition":{"description":"Smart siren","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"features":[{"access":2,"description":"Mode of the warning (sound effect)","name":"mode","property":"mode","type":"enum","values":["stop","burglar","fire","emergency","police_panic","fire_panic","emergency_panic"]},{"access":2,"description":"Sound level","name":"level","property":"level","type":"enum","values":["low","medium","high","very_high"]},{"access":2,"description":"Turn on/off the strobe (light) during warning","name":"strobe","property":"strobe","type":"binary","value_off":false,"value_on":true},{"access":2,"description":"Duration in seconds of the alarm","name":"duration","property":"duration","type":"numeric","unit":"s"}],"name":"warning","property":"warning","type":"composite"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"HS2WD-E","supports_ota":false,"vendor":"HEIMAN"},"endpoints":{"1":{"bindings":[{"cluster":"genPowerCfg","target":{"endpoint":1,"ieee_address":"0x00124b0006100116","type":"endpoint"}}],"clusters":{"input":["genBasic","genPowerCfg","genIdentify","genGroups","genAlarms","ssIasZone","ssIasWd"],"output":["genIdentify","genOta"]},"configured_reportings":[{"attribute":"batteryPercentageRemaining","cluster":"genPowerCfg","maximum_report_interval":62000,"minimum_report_interval":3600,"reportable_change":0}]}},"friendly_name":"0x000d6f0016195fc2","ieee_address":"0x000d6f0016195fc2","interview_completed":true,"interviewing":false,"model_id":"WarningDevice","network_address":22304,"supported":true,"type":"Router"}]

**Missing features/functionality**
Currently the device appears as invalid, the missing functionalities are the ones related with the HomeKit security such as STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED or ALARM_TRIGGERED.

**Suggested services and characteristics**
To work as Homekit alarm system with the already existing functionalities described above that will permit many users to configure in HomeKit this smart siren as part of the security system.

Thanks
Ware

**Comment by itavero** [comment]
Can you describe how the properties from the `exposes` information should be mapped to HomeKit Characteristics (and to which HomeKit service this should belong)?

I think this was also requested in the issue template you filled in, but perhaps I wasn't clear enough.

**Comment by warevlc** [comment]
Hi itavero,
Sorry, you are right I omitted that part but I did because I thought perhaps you already integrated any security system or smart siren in Homebridge-z2m, then I thought you would reuse all that. 
I'll do my best to provide you that info missing.
Cheers
Ware

**Comment by warevlc** [comment]
Hi @itavero 

I have been investigating and the device itself just buzzes and blinks after a combination of commands, quite simple, here is an example:

{topic: "device/set", 
payload: {warning: {mode: "emergency", duration: 1, strobe: true}}
} 

Then the rest of the effort is more related about having the HomeKit Security System functions (https://developers.homebridge.io/#/service/SecuritySystem) which is the siren icon in home app to toggle the different status. The icon and functions related that I guess it may appear in HomeKit thru homebridge-z2m when the Smart Siren is joining the Zigbee network isthe default home kit's security system or alarm icon. Similar to what happens if someone has an Aqara M1 hub and configures, it also shows the siren icon (check [here](https://youtu.be/k8fvkOsnF3Y?t=156) just for reference).

Thanks
Ware

**Comment by spacemannz** [comment]
+1 for adding service handlers for sirens please :-)

I have a TuYa [TS0216](https://www.zigbee2mqtt.io/devices/TS0216.html) which is supported in z2m and able to be triggered from z2m.

As a workaround would there be any way to expose the siren as a switch? That way it could be triggered by a Homekit automation.

BTW, thanks for the fantastic add-in! I'm a bit of a noob on a steep learning curve and your add-in has made it waaaay easier.

**Comment by itavero** [comment]
I had a quick look: exposing a siren (i.e. a device that exposes a `warning`) as a Security System does not make sense to me.

A couple of switches (one for each `mode`) might make more sense.
But then I wonder, what the do with `level`, `length` and `duration`?
And how to make sure that these go out at the same time.. 🤔

**Comment by warevlc** [comment]
You are right there is no HomeKit device that natively can manage the particular settings of the siren such as mode, duration or strobe. Perhaps a switch to trigger the siren can work with some default settings (better that limitation than the incompatible icon that currently appears). Siren switch could just work like the following:

on:  {topic: "devicename/set", payload: {warning: {mode: "**emergency**", duration: 300, strobe: true}}} 
off: {topic: "devicename/set", payload: {warning: {mode: "**stop**", duration: 1, strobe: true}}} 

And also when the device is detected, not only the switch of the siren would appear but also the default security alarm of the HomeKit so the user can continue the configuration.

**Comment by itavero** [comment]
I'm not sure I understand what you mean with "default security alarm o the HomeKit".

Since there is no set of standard HomeKit Services and Characteristics that make a lot of sense for this device, I'm leaning towards **not** adding it to this plugin.

A workaround could be to exclude it in `homebridge-z2m` and use something like [homebridge-mqttthing](https://www.npmjs.com/package/homebridge-mqttthing) to add a custom switch (or whatever) with the specific action you would like it to trigger.

**Comment by warevlc** [comment]
Yes, I am using exactly that plugin as workaround with not optimal result because I can make it sound and blink but with same mode and duration so it wouldn't cover all our needs.

<img width="761" alt="Captura de pantalla 2021-06-01 a las 22 57 17" src="https://user-images.githubusercontent.com/76872375/120389645-fa490980-c32c-11eb-8c9c-4b3aed1cd7b7.png">

I will keep trying with combinations of other modules like homebridge-mqttthing and homebridge-securitysystem

Thanks for reviewing this

**Comment by itavero** [comment]
Well, I would suggest adding multiple switches for the different kind of "warnings" you would like the siren to give.
