### ISSUE TITLE
[Bug] - Ikea Blinds - Homekit state does not change and the update icon is always shown.

### ISSUE THREAD

**Issue by Blackymas** [itavero/homebridge-z2m#189]
Please use the template and fill in all the data requested below!

**Describe the bug**
Ikea Blinds - Homekit state does not change and the update icon is always shown.

**Related devices**
IKEA FYRTUR roller blind

**To Reproduce**
When I activate a flow via Node Red, the Ikea blinds change as desired. But in Homebridge and especially in Homekit the state does not change and the update icon is always shown.

**Expected behavior**
Homekit should display the correct status and correct value

**MQTT messages**
When I look at the debug, there is something wrong with the passing of CurrentPosition and TargetPosition.
The TargetPosition is always the same whether I send the value 20 or 90. Therefore, it seems that the correct status is not displayed in Homekit.
![Homebridge Value send via NodeRed flow](https://user-images.githubusercontent.com/41958506/119569862-9e700500-bdaf-11eb-82d8-16d17ff8fbf7.png)

when I control the roller blind directly in Homekit I see the following
![Homebridge Value Request via Homekit (1)](https://user-images.githubusercontent.com/41958506/119569885-a92a9a00-bdaf-11eb-9ee0-f5003aed8d76.png)
![Homebridge Value Request via Homekit (2)](https://user-images.githubusercontent.com/41958506/119569891-ab8cf400-bdaf-11eb-92cd-a35d5025fe8d.png)

first image is position changed via Node Red and what arrives in Homebridge.

Second and third image is what arrives at Homebridge when I change the position via Homekit.

In both cases I set the values 20 and 90 - but in picture 1 the TargetPosition is always 100 when i send a new position via Node Red. (TargetPosition 100 was the last change via Homekit)

 think here, via z2m, the TargetPosition must have the same value as CurrentPosition.

**Versions used**
Please provide the version of the following pieces of software:
 - homebridge-z2m v1.2.0
 - Homebridge v1.3.4
 - Zigbee2MQTT 1.18.1-1

**Comment by itavero** [comment]
As mentioned on Discord (if I remember correctly), what probably should be done to make HomeKit "accept" that the final position is reached is to update the `TargetPosition` when the `CurrentPosition` gets the same value twice in a row (in other words, when `PositionState` is set to `PositionState.STOPPED`).

I hope we can merge #147 first, before I start working on this issue, to prevent merge conflicts along the way.

Another thing I'm hoping to fix at the same time is that the plugin no longer tries to poll the `position` if Zigbee2MQTT has indicated that it can _not_ be get (but is only published). This should reduce some unneeded MQTT traffic for battery powered blinds that do _not_ support retrieving the position (unlike the IKEA blinds).

**Comment by Blackymas** [comment]
yes that is correct. I have also tested it via Home Assistant Homekit there it also works without problems. So it is not a problem with Zigbee2mqtt

**Comment by Blackymas** [comment]
any news here?

**Comment by itavero** [comment]
Hoping to hear back from another user about #147 in the next week or so. After that I'll implement the change mentioned earlier, along with some other minor changes.

**Comment by itavero** [comment]
@Blackymas Just merged the PR I referred to earlier, so I hope to fix this issue this week.

**Comment by itavero** [comment]
Did some development and testing today and I think I've solved it.
Still need to update the automated tests though.

Another thing I changed is that the plugin will now only requests an updated `position` if it is actually "gettable" and if we did not receive an update recently after setting the `position` from the plugin.

For all "unexpected" updates to `position` (i.e. if you change it via another system/MQTT), the plugin will consider the current state to be "Stopped".

Lastly I've added some logic to ignore the first `position` update after setting the position, if it is equal to the `position` we've just set via the plugin.
I noticed that Zigbee2MQTT first reports the setpoint back before I'm getting the actual position of my IKEA blinds.
This caused the Home.app to show incorrect directions (apparently it does it's own "magic" based on the _CurrentPosition_).

**Comment by itavero** [comment]
Some more tweaking and I think it's working as you expect now.
This is what it looks like in the Home app for me with the changes I've been working on (blind was fully open so it takes about 20 seconds to close apparently):
![Cover closing in Home.app](https://user-images.githubusercontent.com/203398/122678431-2696ce00-d1e7-11eb-9e42-64e074b5e7d4.gif)

Not sure if I'll be able to update the automated tests today and make a release, but I'll try to do that soon.

**Comment by itavero** [comment]
I've just merged #213 and I'll release it in a bit.
If the next release does not resolve your issue, feel free to reopen this one and to add some more info that might help in resolving it.

**Comment by itavero** [comment]
Release v1.3.0 is now available

**Comment by gukj** [comment]
Turns out nothing is published to the topic.

This is the log from Homebridge:
```
[23/03/2022, 08:36:43] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x588e81fffe641269/get': '{"position":0}'
[23/03/2022, 08:36:47] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x588e81fffe641269/get': '{"position":0}'
[23/03/2022, 08:36:51] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x588e81fffe641269/get': '{"position":0}'
[23/03/2022, 08:36:55] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x588e81fffe641269/get': '{"position":0}'
[23/03/2022, 08:36:59] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x588e81fffe641269/get': '{"position":0}'
[23/03/2022, 08:37:03] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x588e81fffe641269/get': '{"position":0}'
[23/03/2022, 08:37:07] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x588e81fffe641269/get': '{"position":0}'
```
and this is the corresponding log from Zigbee2MQTT:
```
Debug Received MQTT message on 'zigbee2mqtt/0x588e81fffe641269/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to 'BL03'
Debug Received MQTT message on 'zigbee2mqtt/0x588e81fffe641269/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to 'BL03'
Debug Received MQTT message on 'zigbee2mqtt/0x588e81fffe641269/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to 'BL03'
Error Publish 'get' 'position' to 'BL03' failed: 'Error: Read 0x588e81fffe641269/1 closuresWindowCovering(["currentPositionLiftPercentage"], {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'
Debug Error: Read 0x588e81fffe641269/1 closuresWindowCovering(["currentPositionLiftPercentage"], {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received) at DeconzAdapter.sendZclFrameToEndpoint (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:649:23) at Endpoint.sendPendingRequests (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:272:36)
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'get' 'position' to 'BL03' failed: 'Error: Read 0x588e81fffe641269/1 closuresWindowCovering([\"currentPositionLiftPercentage\"], {\"sendWhen\":\"active\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received)'","meta":{"friendly_name":"BL03"},"type":"zigbee_publish_error"}'
Debug Received MQTT message on 'zigbee2mqtt/0x588e81fffe641269/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to 'BL03'
Debug Received MQTT message on 'zigbee2mqtt/0x588e81fffe641269/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to 'BL03'
Debug Received MQTT message on 'zigbee2mqtt/0x588e81fffe641269/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to 'BL03'
```

Running `mosquitto_sub -t zigbee2mqtt/BL03` returns nothing for this device, but for other devices gives updates when something changes.

**Comment by gukj** [comment]
I don't understand how nothing is communicated on the topic and still there are messages back and forth.

**Comment by gukj** [comment]
For anyone stumbling upon this issue in the future:
It seems my issue was resolved by res-syncing the blinds and not giving them friendly names. There still seems to be messages going back and forth about some blinds being in position: 0 even when they're not, but it doesn't stop the blinds from getting new instructions.
This is what I'm seeing in the Z2M log:
```
Debug Received MQTT message on 'zigbee2mqtt/0x000d6ffffe8e9405/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to '0x000d6ffffe8e9405'
Debug Received MQTT message on 'zigbee2mqtt/0x680ae2fffe12a6e7/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to '0x680ae2fffe12a6e7'
Debug Received Zigbee message from '0x000d6ffffe8e9405', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe8e9405', payload '{"battery":85,"linkquality":255,"position":100,"update":{"state":"idle"},"update_available":false}'
Debug Received Zigbee message from '0x680ae2fffe12a6e7', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe12a6e7', payload '{"battery":99,"linkquality":255,"position":100,"update":{"state":"idle"},"update_available":false}'
Debug Received MQTT message on 'zigbee2mqtt/0x000d6ffffe8e9405/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to '0x000d6ffffe8e9405'
Debug Received MQTT message on 'zigbee2mqtt/0x680ae2fffe12a6e7/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to '0x680ae2fffe12a6e7'
Debug Received Zigbee message from '0x000d6ffffe8e9405', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe8e9405', payload '{"battery":85,"linkquality":255,"position":100,"update":{"state":"idle"},"update_available":false}'
Debug Received Zigbee message from '0x680ae2fffe12a6e7', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe12a6e7', payload '{"battery":99,"linkquality":255,"position":100,"update":{"state":"idle"},"update_available":false}'
Debug Received MQTT message on 'zigbee2mqtt/0x000d6ffffe8e9405/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to '0x000d6ffffe8e9405'
Debug Received MQTT message on 'zigbee2mqtt/0x680ae2fffe12a6e7/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to '0x680ae2fffe12a6e7'
Debug Received Zigbee message from '0x000d6ffffe8e9405', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe8e9405', payload '{"battery":85,"linkquality":255,"position":100,"update":{"state":"idle"},"update_available":false}'
Debug Received Zigbee message from '0x680ae2fffe12a6e7', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe12a6e7', payload '{"battery":99,"linkquality":255,"position":100,"update":{"state":"idle"},"update_available":false}'
Debug Received MQTT message on 'zigbee2mqtt/0x000d6ffffe8e9405/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to '0x000d6ffffe8e9405'
Debug Received MQTT message on 'zigbee2mqtt/0x680ae2fffe12a6e7/get' with data '{"position":0}'
Debug Publishing get 'get' 'position' to '0x680ae2fffe12a6e7'
Debug Received Zigbee message from '0x000d6ffffe8e9405', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe8e9405', payload '{"battery":85,"linkquality":255,"position":100,"update":{"state":"idle"},"update_available":false}'
Debug Received Zigbee message from '0x680ae2fffe12a6e7', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe12a6e7', payload '{"battery":99,"linkquality":255,"position":100,"update":{"state":"idle"},"update_available":false}'
```

**Comment by itavero** [comment]
> There still seems to be messages going back and forth about some blinds being in position: 0 even when they're not, but it doesn't stop the blinds from getting new instructions. 

The messages published to the `/get` topic with `{"position:0}`, are coming from homebridge-z2m. This is how it asks Zigbee2MQTT to get the current position from the actual device.
In a previous Zigbee2MQTT log you've shared, it actually showed an error when trying to perform this action.
I think somehow the binding/pairing didn't succeed fully (or got broken somehow).
Glad to hear you've resolved it.

**Comment by gukj** [comment]
I see. What does the `0` represent in that case? Is that just the way that it asks for the `position`? I guess I was stumped by all blinds being set to values `>0` and seeing messages about `position: 0` everywhere.

**Comment by itavero** [comment]
> What does the `0` represent in that case? Is that just the way that it asks for the `position`?

Zigbee2MQTT [only cares about the keys](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-friendly-name-get) and a `0` is the shortest valid value in JSON, so that's why it's a zero. No specific meaning to it, really. :wink:

**Comment by gukj** [comment]
All right. That makes sense.

I just restarted my server and now no blinds respond to any commands. I just see `get' with data '{"position":0}'` for all the blinds I've tried. Any idea where I should direct my troubleshooting attention? 😅

**Comment by itavero** [comment]
I've never experienced this and I've been using the four IKEA KADRILJ with Zigbee2MQTT for about two years now.

Just wondering, are you also using the included [signal repeater](https://www.zigbee2mqtt.io/devices/E1746.html)? (I am using it.)

**Comment by gukj** [comment]
Yes, all of the included repeater are set up in the same network. However, looking at the tree in Z2M, they seem to prefer to connect via bulbs even when repeaters are much closer/unobstructed.

All of the blinds seem to be working as of yesterday evening when I re-configured the struggling ones. For now I'll just write it off as bad luck during setup.

My troubleshooting leads me think that the blinds somehow drops their connection/go to sleep. HB sends a request which is transmitted to the blind (not sure how to tell if it actually arrives). Then HB just keeps asking for the blinds current position (I'm assuming) in the hope that it'll get the requested position, which it never does.
