### ISSUE TITLE
[Feature] Request support EZSP Adapter 

### ISSUE THREAD

**Issue by the3future** [itavero/homebridge-z2m#191]
It will be nice if this support EZSP Adapter.

I am using the Xiaomi Gateway 3 adapter.

**Comment by itavero** [comment]
It seems that there is already (experimental) support for that in Zigbee2MQTT: https://www.zigbee2mqtt.io/information/supported_adapters.html

This plugin doesn't require you to use any specific adapter, if Zigbee2MQTT works, this plugin for Homebridge will just follow along.
