### ISSUE TITLE
[Bug] - Hue lamps jumps the value of the color temperature always back.

### ISSUE THREAD

**Issue by Blackymas** [itavero/homebridge-z2m#208]
Please use the template and fill in all the data requested below!

**Describe the bug**
If you have a colored lamp, the color setting works, but the color temperature value always jumps back.
The color changes as desired but in the HOME APP it is displayed incorrectly with the color of the last state.

I have also tried the devices via Home Assistant Homekit here everything is ok.

**Related devices**
all Hue Color Lamps

**To Reproduce**
Steps to reproduce the behavior, for example:
Change 'COLOR Temperature' via the Home app.
Reproduce with all Hue Lamps

short video of the problem attached!

**Versions used**
Please provide the version of the following pieces of software:
homebridge-z2m v1.2.0
Homebridge v1.3.4
Zigbee2MQTT 1.18.1-1

https://user-images.githubusercontent.com/41958506/121590096-30c30a80-ca38-11eb-8875-02ca57e09190.mov

**Comment by itavero** [comment]
As mentioned on Discord, I need some "magic" (a.k.a. logic) to determine wether to use the `color` or `color_temp` from the status update I've received.
Can you perhaps also log some of the MQTT messages send by Zigbee2MQTT with the status updates?

I guess I'd have to check if the `color_temp` is valid and (if so), ignore the `color`, but I'm not 100% sure about that just yet.

Not sure how other plugins handle this.

**Comment by itavero** [comment]
Just tried to reproduce this locally. A few things I've noticed:
* On my iPhone, after setting the color temperature, I see it going to the last "hue/saturation" color I've set and then going to the color temperature. So there's a short period in between in which the value is incorrect.
* Changes after that, seem to behave correctly.
* The message from Zigbee2MQTT seems to include a `color_mode` property now which indicates if `hs` or `color_temp` is used. I can't remember seeing this property before, but it sounds like this will make solving this issue a lot easier. I'll investigate the specifics of this property.

**Comment by itavero** [comment]
Working on a filter for state updates, based on the `color_mode` property if it is present.
This did change the behavior for me, but not really in the way I expected it too.

After a bit of searching I found an issue for another Homebridge plugin, ebaauw/homebridge-hue#814, and it seems it's actually a "bug" (or poor UX?) in the Home.app.
Luckily, that issue also describes an acceptable solution: transforming the color temperature back to the Hue/Saturation value.
It won't be perfect but it should result in a better UX.

**Comment by itavero** [comment]
Apparently, "officially" it is not allowed to have both _Hue_ / _Saturation_ and _Color Temperature_, if I read [this source code](https://github.com/apple/HomeKitADK/blob/4967f698bdcf0af122e13e986a2c9b595a68cdc5/HAP/HAPCharacteristicTypes.h#L2733-L2756).
This does explain why such a "workaround" is necessary.

**Comment by itavero** [comment]
After #335 is merged and released, the changes I've made to make the user experience a bit better can be tried out be adding the `COLOR_MODE` experimental feature flag to your Homebridge configuration:

```json
{
  "platforms": [
    {
      "platform": "zigbee2mqtt",
      "experimental": [
        "COLOR_MODE"
      ]
    }
  ]
}
```

**Comment by itavero** [comment]
The mentioned "improvement" is now available as an experimental feature (enabled with flag `COLOR_MODE`, see [docs on configuration](https://z2m.dev/config.html#experimental)) in `v1.7.0-rc.1` (also tagged as `homebridge-z2m@next` on NPM).

If you've tried it out and have any suggestions/issues, please reply on this issue.

**Comment by itavero** [comment]
@Blackymas Have you been able to try out the changes I mentioned earlier?

**Comment by itavero** [comment]
For my understanding, which Zigbee2MQTT version are you using? And is this behavior seen with that adaptive lighting branch?
