### ISSUE TITLE
homebridge-z2m never reads occupancy sensor state

### ISSUE THREAD

**Issue by zerobaud** [itavero/homebridge-z2m#224]
Hi there,

Love the plugin.  Recently I picked up a Linkind ZS1100400-IN-V1A02 PIR motion sensor, which is supported by zigbee2mqtt ([see here](https://www.zigbee2mqtt.io/devices/ZS1100400-IN-V1A02.html#linkind-zs1100400-in-v1a02)).  Sure enough, in the zigbee2mqtt console, I see the device on the network, and I can see that it changes the "occupancy" state from false to true and vice versa when it picks up motion.

Homebridge-z2m adds the device and I see it in the Home app.  Using the latest homebridge-z2m as of the time of this post.

However, the Home app never picks up on the occupancy sensor state change.  There is never any corresponding log in the Homebridge console that would indicate that homebridge-z2m also picked up on the occupancy state change.  However, I can see the state change in zigbee2mqtt.

Other devices connected via zigbee2mqtt work just fine through homebridge-z2m.... but for some reason, its like homebridge-z2m doesnt know what to look for in the case of an occupancy sensor.

What can I provide, here?  I don't seem to have any logs on the homebridge-z2m side because nothing ever happens.

**Comment by itavero** [comment]
You can start by logging the MQTT messages, via an additional MQTT client.
I'm particularly interested in the status updates published by Zigbee2MQTT.

Also, do you have debug logging on in Homebridge?
That should provide some information about the messages that were received.

**Comment by zerobaud** [comment]
I'll enable debug logging in homebridge and see if anything is showing up
there.

I'll see about logging the MQTT messages via another client - I'll see if I
can get one configured tomorrow.

**Comment by zerobaud** [comment]
OK, I have some updates here.  Thanks @itavero !

Here's the messages which are being received by zigbee2mqtt when the occupancy sensor detects motion:

```
{"level":"info","message":"MQTT publish: topic 'zigbee2mqtt/MBR Closet Sensor/occupancy', payload 'true'"}
true
{"level":"info","message":"MQTT publish: topic 'zigbee2mqtt/MBR Closet Sensor/tamper', payload 'false'"}
false
{"level":"info","message":"MQTT publish: topic 'zigbee2mqtt/MBR Closet Sensor/battery_low', payload 'false'"}
false
{"level":"info","message":"MQTT publish: topic 'zigbee2mqtt/MBR Closet Sensor/last_seen', payload '2021-06-28T18:52:06+00:00'"}
2021-06-28T18:52:06+00:00
{"level":"info","message":"MQTT publish: topic 'zigbee2mqtt/MBR Closet Sensor/linkquality', payload '255'"}
255
```

...and, here's what's showing up in the Homebridge debug output at the same time:

```
[6/28/2021, 2:52:06 PM] [zigbee2mqtt] Unhandled message on topic: MBR Closet Sensor/occupancy
[6/28/2021, 2:52:06 PM] [zigbee2mqtt] Unhandled message on topic: MBR Closet Sensor/tamper
[6/28/2021, 2:52:06 PM] [zigbee2mqtt] Unhandled message on topic: MBR Closet Sensor/battery_low
[6/28/2021, 2:52:06 PM] [zigbee2mqtt] Unhandled message on topic: MBR Closet Sensor/last_seen
[6/28/2021, 2:52:06 PM] [zigbee2mqtt] Unhandled message on topic: MBR Closet Sensor/linkquality
```

It looks to me like the plugin doesn't quite know what to do with the messages sourcing from the occupancy sensor.

**Comment by itavero** [comment]
Can it be that you have changed the default `output` format in the [Zigbee2MQTT configuration](https://www.zigbee2mqtt.io/information/configuration.html)?
This plugin only processes JSON messages, so it should be set to `json` or `attribute_and_json`.

I think someone reported a similar issue before, but I wasn't able to find it quickly. Changing the configuration back solved it in that case.

**Comment by zerobaud** [comment]
I’ll double check, but the other devices reporting through zigbee2mqtt all
seem to be working.  I’ll give it a look and report back!

**Comment by zerobaud** [comment]
...wow, sure enough it was set to "attribute," and switching it back to "json" fixes the issue, now the sensor reports occupancy.  Great call, thank you @itavero !

I have no idea why it was ever changed in the first place, but weirder things have happened.

**Comment by zerobaud** [comment]
...wow, sure enough it was set to "attribute," and switching it back to "json" fixes the issue, now the sensor reports occupancy. Great call, thank you @itavero !

I have no idea why it was ever changed in the first place, but weirder things have happened.

**Comment by itavero** [comment]
I'll see if I can add a warning in the logs if such a configuration is detected. 🤔

**Comment by zerobaud** [comment]
That would have definitely saved me some digging!  Thanks again; love the plugin.  It's mostly hands off :)
