### ISSUE TITLE
[Bug] Ikea/Hue Remote: Failed to process MQTT message

### ISSUE THREAD

**Issue by al3x1337** [itavero/homebridge-z2m#23]
**Describe the bug**
![image](https://user-images.githubusercontent.com/44815197/98386511-44c80900-201e-11eb-8d9f-db0a17914164.png)

**To Reproduce**
Hue Dimmer Remote + IKEA Puck + IKEA On/Off Remotes paired via zigbee2mqtt. 
It is discovered:
![image](https://user-images.githubusercontent.com/44815197/98386663-76d96b00-201e-11eb-9e42-464bfc2a9ce7.png)
However on button presses it produces an error. 

I've tried switching MQTT version to 3,4,5 and get the same error. Is exposing Remotes currently working? I thought i read in #2 that it was supported in the release. 

Am running homebridge config UI.

**Comment by itavero** [comment]
Support for push buttons is pending on the `exposes` attribute in zigbee2mqtt.
It will probably be in the next release of zigbee2mqtt, and then I'll integrate it in this plugin as soon as I can.

Just wondering: which version of the plugin are you using?
I think I ran into the same issue and fixed it, but perhaps I forgot to publish the release as the `latest` tag on NPM.

**Comment by itavero** [comment]
Looks like I didn't publish it to the `latest` tag yet. You should be able to update to `0.0.10` now, which should get rid of this messages. ;)

**Comment by itavero** [comment]
I'm closing this issue. If it's not fixed in the release I've mentioned, let me know, @al3x1337
