### ISSUE TITLE
[Bug] Phillips Hue E27 cannot change color

### ISSUE THREAD

**Issue by marius-se** [itavero/homebridge-z2m#24]
**Describe the bug**
In Apple Home (and Homebridge UI) I cannot change the color of my Phillips Hue E27 (white and color ambiance). The only option I have is to change the brightness of the lamp, so the color wheel doesn't show up at all in Home. Tho it is possible for me to change the color via the Phillips Hue Bluetooth app (I know it probably doesn't matter, but I thought I'd add it).

**To Reproduce**
1. Figure out the friendly name and add it to the plugin config.
2. Restart Homebridge
3. Try to change the color -> Color wheel doesn't show up (Home/ homebridge)

**Expected behavior**
Color wheel showing up to change the color of the bulb.

**MQTT messages**
* The device identification from `zigbee2mqtt/bridge/config/devices` -> Is it the friendly name? Then it's zigbee2mqtt/0x0017880108ac9e9e
* Status update from `zigbee2mqtt/0x0017880108ac9e9e`:
   `MQTT publish: topic 'zigbee2mqtt/0x0017880108ac9e9e', payload '{"brightness":254,"linkquality":36,"state":"OFF","update_available":false}'`

**Versions used**
 - Z2M v0.0.10
 - Homebridge v1.1.6
 - Zigbee2mqtt 1.16.1
 - homebridge-config-ui-x v4.32.0

**Comment by marius-se** [comment]
Update: Just tried to set up my second Phillips Hue bulb (same model, same firmware). This bulb doesn't work at all. Zigbee2MQTT log says ` No converter available for 'state' (ON)` when I try to turn it on or off...

**Comment by itavero** [comment]
Does it work directly via MQTT to zigbee2mqtt?
It seems that it does not report all the right keys for the device in the status message.

**Comment by itavero** [comment]
I've also updated my zigbee2mqtt installation today. For me it still works. Have you tried sending the command manually to see if that works, @marius-se ?

**Comment by marius-se** [comment]
Ah sorry, I didn't have the time yet to check. Now I'm back. Give me a second...

**Comment by marius-se** [comment]
Changing the color directly via mqtt seems to work.
`mosquitto_pub -t zigbee2mqtt/0x0017880108ac9e9e/set -m '{"color":{"r":255, "g":0, "b":0}}'`
...et voilà my rooms turns red.

**Comment by itavero** [comment]
In the status MQTT message, do you also see a color property now?
I don't see it in the message you've shared before.
If it's not there then this plugin also won't know it exists right now (as mentioned in the read me).

**Comment by marius-se** [comment]
Yes, now it's:
'zigbee2mqtt/0x0017880108ac9e9e', payload '{"brightness":254,"color":{"x":0.304580214170851,"y":0.31468018726472},"color_temp":140,"linkquality":44,"state":"ON","update_available":false}'

Also the color controls appeared in my Home app after I manually changed the color via mqtt for the first time.

**Comment by marius-se** [comment]
> Unfortunately, a downside is that the device must have published its data before the plugin knows how HomeKit could use it

Now I get what you meant with this line. _Weird tho that it only sends the data after a manual mqtt pub._

**Comment by itavero** [comment]
I've seen it with some devices before, but indeed it is weird.
Not 100% sure if it's a configuration thing or some kind of glitch.

Luckily the latest version of zigbee2mqtt includes a newer API which can list the features/properties of a device via the new `exposes` field.
As mentioned in some other issues, this will make it easier for this plugin to show the right characteristics from the get go.
Hopefully I'll have some time to refactor some stuff and integrate this new field soon. Then I can remove that sentence from the read me file. 😉

**Comment by marius-se** [comment]
Awesome thanks! I have to say I'm really happy with the plugin. A couple of months earlier and I'd have had to switch to Hass (to use zigbee2mqtt)
