### ISSUE TITLE
TRADFRI Remote Control (E1524 ) only 4 Button

### ISSUE THREAD

**Issue by ghdbwise** [itavero/homebridge-z2m#240]
Using always actual latest versions of zigbee2mqtt, homebridge-z2m plugin, homebridge, ... .
In Apples HK only 4 buttons are displayed key1 - left, key2 - right, key3 - up, key4 - down. Fifth key toggle isn't displayed.
In zigbee2mqtt log i can see when center button is pressed >>payload '{"action":"toggle","battery":87,"linkquality":47}'<<
Monitoring my mqtt broker i also see {"action":"toggle","battery ....}

So, where is that missing button?

**Comment by itavero** [comment]
Can you please provide the information requested in the [Bug Report](https://github.com/itavero/homebridge-z2m/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBug%5D+) issue template?

I'm specifically interested in:
* The `exposes` information for the device (a.k.a. the device entry from `zigbee2mqtt/bridge/devices`)
* The log from when Zigbee2MQTT starts, which should list the mapping for this device.

I had a quick look at the [device page](https://www.zigbee2mqtt.io/devices/E1524_E1810.html#action-enum) on the Zigbee2MQTT website and it doesn't seem to mention a `toggle` value for the `action`, so it might be that a change in [Koenkk/zigbee-herdsman-converters](http://github.com/Koenkk/zigbee-herdsman-converters) is needed to correct the `exposes` information.

**Comment by ghdbwise** [comment]
zigbee2mqtt/bridge/devices
[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genTime","genOta"],"output":["genPowerCfg","genPollCtrl","ssIasZone"]},"configured_reportings":[]},"242":{"bindings":[],"clusters":{"input":[],"output":["greenPower"]},"configured_reportings":[]}},"friendly_name":"Coordinator","ieee_address":"0x00212effff06177a","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type":"Coordinator"},{"definition":{"description":"Aqara vibration sensor","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["vibration","tilt","drop"]},{"access":1,"name":"strength","property":"strength","type":"numeric"},{"access":3,"name":"sensitivity","property":"sensitivity","type":"enum","values":["low","medium","high"]},{"access":1,"name":"angle_x","property":"angle_x","type":"numeric","value_max":90,"value_min":-90},{"access":1,"name":"angle_y","property":"angle_y","type":"numeric","value_max":90,"value_min":-90},{"access":1,"name":"angle_z","property":"angle_z","type":"numeric","value_max":90,"value_min":-90},{"access":1,"description":"Voltage of the battery in millivolts","name":"voltage","property":"voltage","type":"numeric","unit":"mV"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"DJT11LM","supports_ota":false,"vendor":"Xiaomi"},"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"2":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]}},"friendly_name":"Vibrationssensor","ieee_address":"0x00158d000312c1f8","interview_completed":true,"interviewing":false,"model_id":"lumi.vibration.aq1","network_address":6975,"power_source":"Battery","supported":true,"type":"EndDevice"},{"definition":{"description":"MiJia human body movement sensor","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Indicates whether the device detected occupancy","name":"occupancy","property":"occupancy","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Voltage of the battery in millivolts","name":"voltage","property":"voltage","type":"numeric","unit":"mV"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"RTCGQ01LM","supports_ota":false,"vendor":"Xiaomi"},"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]}},"friendly_name":"BWM AZ","ieee_address":"0x00158d0002c12dc4","interview_completed":true,"interviewing":false,"model_id":"lumi.sensor_motion","network_address":57207,"power_source":"Battery","supported":true,"type":"EndDevice"},{"definition":{"description":"Aqara human body movement and illuminance sensor","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Indicates whether the device detected occupancy","name":"occupancy","property":"occupancy","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Measured temperature value","name":"temperature","property":"temperature","type":"numeric","unit":"°C"},{"access":1,"description":"Voltage of the battery in millivolts","name":"voltage","property":"voltage","type":"numeric","unit":"mV"},{"access":1,"description":"Measured illuminance in lux","name":"illuminance_lux","property":"illuminance","type":"numeric","unit":"lx"},{"access":1,"description":"Measured illuminance in lux","name":"illuminance","property":"illuminance","type":"numeric","unit":"lx"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"RTCGQ11LM","supports_ota":false,"vendor":"Xiaomi"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","msOccupancySensing","msIlluminanceMeasurement","ssIasZone","genPowerCfg","genIdentify"],"output":["genBasic","genOta"]},"configured_reportings":[]}},"friendly_name":"BWM Werkstatt","ieee_address":"0x00158d0002c66b9e","interview_completed":true,"interviewing":false,"model_id":"lumi.sensor_motion.aq2","network_address":6327,"power_source":"Battery","software_build_id":"3000-0001","supported":true,"type":"EndDevice"},{"date_code":"20161128","definition":{"description":"Aqara wireless switch","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Voltage of the battery in millivolts","name":"voltage","property":"voltage","type":"numeric","unit":"mV"},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["single","double","triple","quadruple","hold","release"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"WXKG11LM","supports_ota":false,"vendor":"Xiaomi"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genOnOff"],"output":["genBasic","genGroups"]},"configured_reportings":[]}},"friendly_name":"Taste III","ieee_address":"0x00158d000204401e","interview_completed":true,"interviewing":false,"model_id":"lumi.sensor_switch.aq2","network_address":38542,"power_source":"Battery","software_build_id":"3000-0001","supported":true,"type":"EndDevice"},{"date_code":"20190708","definition":{"description":"TRADFRI remote control","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["arrow_left_click","arrow_left_hold","arrow_left_release","arrow_right_click","arrow_right_hold","arrow_right_release","brightness_down_click","brightness_down_hold","brightness_down_release","brightness_up_click","brightness_up_hold","brightness_up_release"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"E1524/E1810","supports_ota":true,"vendor":"IKEA"},"endpoints":{"1":{"bindings":[{"cluster":"genOnOff","target":{"id":901,"type":"group"}},{"cluster":"genPowerCfg","target":{"endpoint":1,"ieee_address":"0x00212effff06177a","type":"endpoint"}}],"clusters":{"input":["genBasic","genPowerCfg","genIdentify","genPollCtrl","touchlink"],"output":["genIdentify","genGroups","genOnOff","genLevelCtrl","genOta","touchlink"]},"configured_reportings":[{"attribute":"batteryPercentageRemaining","cluster":"genPowerCfg","maximum_report_interval":62000,"minimum_report_interval":3600,"reportable_change":0}]}},"friendly_name":"TRADFRI Fernbedienung","ieee_address":"0x000b57fffe3145e9","interview_completed":true,"interviewing":false,"model_id":"TRADFRI remote control","network_address":33466,"power_source":"Battery","software_build_id":"2.3.014","supported":true,"type":"EndDevice"}]
-----------
zigbee2mqtt:
Jul 25 18:30:43 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:30:43: MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"0zv0h-5"}'
Jul 25 18:31:40 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:31:40: Device '0x000b57fffe3145e9' joined
Jul 25 18:31:40 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:31:40: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000b57fffe3145e9","ieee_address":"0x000b57fffe3145e9"},"type":"device_joined"}'
Jul 25 18:31:40 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:31:40: Starting interview of '0x000b57fffe3145e9'
Jul 25 18:31:40 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:31:40: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000b57fffe3145e9","ieee_address":"0x000b57fffe3145e9","status":"started"},"type":"device_interview"}'
Jul 25 18:31:40 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:31:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x000b57fffe3145e9"},"type":"device_connected"}'
Jul 25 18:31:40 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:31:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x000b57fffe3145e9"},"type":"pairing"}'
Jul 25 18:32:15 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:32:15: Successfully interviewed '0x000b57fffe3145e9', device has successfully been paired
Jul 25 18:32:15 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:32:15: Device '0x000b57fffe3145e9' is supported, identified as: IKEA TRADFRI remote control (E1524/E1810)
Jul 25 18:32:15 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:32:15: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"TRADFRI remote control","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["arrow_left_click","arrow_left_hold","arrow_left_release","arrow_right_click","arrow_right_hold","arrow_right_release","brightness_down_click","brightness_down_hold","brightness_down_release","brightness_up_click","brightness_up_hold","brightness_up_release"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"E1524/E1810","supports_ota":true,"vendor":"IKEA"},"friendly_name":"0x000b57fffe3145e9","ieee_address":"0x000b57fffe3145e9","status":"successful","supported":true},"type":"device_interview"}'
Jul 25 18:32:15 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:32:15: Configuring '0x000b57fffe3145e9'
Jul 25 18:32:15 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:32:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"TRADFRI remote control","friendly_name":"0x000b57fffe3145e9","model":"E1524/E1810","supported":true,"vendor":"IKEA"},"type":"pairing"}'
Jul 25 18:32:25 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:32:25: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe3145e9', payload '{"battery":60,"linkquality":199}'
Jul 25 18:32:25 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:32:25: Successfully configured '0x000b57fffe3145e9'
Jul 25 18:33:22 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:33:22: Configuring '0x000b57fffe3145e9'
Jul 25 18:33:23 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:33:23: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe3145e9', payload '{"action":"toggle","battery":60,"linkquality":135}'
Jul 25 18:33:26 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:33:26: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe3145e9', payload '{"action":"toggle_hold","battery":60,"linkquality":127}'
Jul 25 18:33:43 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:33:43: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe3145e9', payload '{"battery":74,"linkquality":231}'
Jul 25 18:33:43 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:33:43: Successfully configured '0x000b57fffe3145e9'
Jul 25 18:33:43 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:33:43: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0x000b57fffe3145e9"},"status":"ok","transaction":"0zv0h-6"}'
Jul 25 18:34:04 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:34:04: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe3145e9', payload ''
Jul 25 18:34:04 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:34:04: MQTT publish: topic 'zigbee2mqtt/TRADFRI Fernbedienung', payload '{"battery":74,"linkquality":231}'
Jul 25 18:34:04 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:34:04: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/rename', payload '{"data":{"from":"0x000b57fffe3145e9","homeassistant_rename":false,"to":"TRADFRI Fernbedienung"},"status":"ok","transaction":"0zv0h-7"}'
Jul 25 18:34:13 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:34:13: MQTT publish: topic 'zigbee2mqtt/TRADFRI Fernbedienung', payload '{"action":"toggle","battery":74,"linkquality":215}'
Jul 25 18:34:13 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:34:13: MQTT publish: topic 'zigbee2mqtt/TRADFRI Fernbedienung', payload '{"action":"brightness_up_click","battery":74,"linkquality":247}'
Jul 25 18:34:14 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:34:14: MQTT publish: topic 'zigbee2mqtt/TRADFRI Fernbedienung', payload '{"action":"brightness_down_click","battery":74,"linkquality":215}'
Jul 25 18:34:15 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:34:15: MQTT publish: topic 'zigbee2mqtt/TRADFRI Fernbedienung', payload '{"action":"arrow_right_click","battery":74,"linkquality":199}'
Jul 25 18:34:15 rpi62 npm[15760]: Zigbee2MQTT:info  2021-07-25 18:34:15: MQTT publish: topic 'zigbee2mqtt/TRADFRI Fernbedienung', payload '{"action":"arrow_left_click","battery":74,"linkquality":183}'
----------
homebridge-hue
[25/07/2021, 18:35:29] [zigbee2mqtt] Restoring accessory: 0x000b57fffe3145e9 (0x000b57fffe3145e9)
[25/07/2021, 18:35:29] [zigbee2mqtt] Mapping of property 'action' of device 'TRADFRI Fernbedienung':
Button 1 (arrow_left):
        - SINGLE: arrow_left_click
        - LONG  : arrow_left_hold
Button 2 (arrow_right):
        - SINGLE: arrow_right_click
        - LONG  : arrow_right_hold
Button 3 (brightness_down):
        - SINGLE: brightness_down_click
        - LONG  : brightness_down_hold
Button 4 (brightness_up):
        - SINGLE: brightness_up_click
        - LONG  : brightness_up_hold
----------

**Comment by itavero** [comment]
The `toggle value is not exposed by Zigbee2MQTT, as you can see in the information from `zigbee2mqtt/bridge/devices` you shared:
```json
{
  "access":1,
  "description":"Triggered action (e.g. a button click)",
  "name":"action",
  "property":"action",
  "type":"enum",
  "values":[
    "arrow_left_click",
    "arrow_left_hold",
    "arrow_left_release",
    "arrow_right_click",
    "arrow_right_hold",
    "arrow_right_release",
    "brightness_down_click",
    "brightness_down_hold",
    "brightness_down_release",
    "brightness_up_click",
    "brightness_up_hold",
    "brightness_up_release"
  ]
}
```

So the assumption I might before seems to be correct: a change in [Koenkk/zigbee-herdsman-converters](http://github.com/Koenkk/zigbee-herdsman-converters) is needed to correct the `exposes` information.
The plugin is functioning as intended with the information it is provided.
