### ISSUE TITLE
[Feature] Light sensor illuminance (not illuminance_lux)

### ISSUE THREAD

**Issue by GiffE** [itavero/homebridge-z2m#25]
**Problem description**
I bought a [mijia light sensor](https://www.zigbee2mqtt.io/devices/GZCGQ01LM.html) which I hoped to do some automations with.  
After pairing it, I found it only outputs battery sensors and illuminance.  Not illuminance_lux, this prevents it from showing up in home bridge.

**Suggested solution**
Add an illuminance support for more light sensor device options

**Are you willing to contribute to this feature?**
Yes

**Comment by itavero** [comment]
I think I have the exact same sensor and for me it does report `illuminance_lux`.

Anyway, I'm currently in the process of refactoring the inner workings of the plugin to make use of the `exposes` information that is added to zigbee2mqtt recently.
I'll try to implement support for the non-lux `illuminance`, when this is finished.

**Comment by GiffE** [comment]
You know what?  My zigbee2mqtt version was getting a bit stale so I updated it to the latest and it now includes the `illuminance_lux` key.  Must have had an out of date version of the Zigbee converters.

Thanks for getting me to update!

**Comment by itavero** [comment]
Good to hear that it's working now.
