### ISSUE TITLE
[Device Support] Current Products Corp CP180335E-01

### ISSUE THREAD

**Issue by RMCob** [itavero/homebridge-z2m#254]
Please use the template and fill in all the data requested below!

**Describe the bug**
For device "Current Products Corp CP180335E-01", the information supplied by zigbee2mqtt does not match the format you are expecting and the 'cover' property is not exposed to Homekit.

**Related devices**
Current Products Corp CP180335E-01

**To Reproduce**
By subscribing to the zigbee2mqtt/bridge/devices topic with a mosquitto client I can see that zigbee2mqtt is returning all the necessary information, but not in the format described in https://z2m.dev/cover.html

**Expected behavior**
See above

**MQTT messages**
If possible (and applicable), please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)
{
	"date_code": "",
	"definition": {
		"description": "Gen. 2 hybrid E-Wand",
		"exposes": [{
			"access": 1,
			"description": "Remaining battery in %",
			"name": "battery",
			"property": "battery",
			"type": "numeric",
			"unit": "%",
			"value_max": 100,
			"value_min": 0
		}, {
			"features": [{
				"access": 3,
				"name": "state",
				"property": "state",
				"type": "enum",
				"values": ["OPEN", "CLOSE", "STOP"]
			}, {
				"access": 7,
				"description": "Tilt of this cover",
				"name": "tilt",
				"property": "tilt",
				"type": "numeric",
				"value_max": 100,
				"value_min": 0
			}],
			"type": "cover"
		},

* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
info  2021-08-10 16:14:50: MQTT publish: topic 'zigbee2mqtt/0x847127fffe4cf99c', payload '{"battery":77,"linkquality":111,"tilt":45}'

* Messages published by this plugin that might be related to your issue (can also be seen in the homebridge logs)

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin             V1.3.0
 - Homebridge           V1.3.4
 - Zigbee2MQTT (can be found in MQTT topic `zigbee2mqtt/bridge/info`)  V1.21.0
 - Homebridge Config UI X (if applicable)  v4.41.2

**Comment by itavero** [comment]
This is not a bug as the plugin is working as intended. The device doesn't expose a `position`.
A position is required for the [window covering](https://developers.homebridge.io/#/service/WindowCovering) service.

Copied the following from the _Device Support_ issue template. If you can, please provide the following:

**Missing features/functionality**
Please describe the features/functionality of this device that are currently not exposed to HomeKit via this plugin.

**Suggested services and characteristics**
For each of the missing features, please mention to which HomeKit Services and Characteristics it should be mapped.
The [Homebridge Plugin Development documentation](https://developers.homebridge.io/) provides a nice overview of the standard HomeKit services and characteristics.
Note that some manufacturers also use custom services and characteristics (the Elgato Eve products for instance), which could also be mimicked if they have been reverse engineered.

**Comment by RMCob** [comment]
Missing features/functionality
The device is not recognized as a Window Covering as it should be since the 'Position' parameter is not exposed by zigbee2mqtt.

Suggested services and characteristics
The 'Tilt' value that is returned from the device is essentially it's current 'Position'.


Is this something that can be compensated for in z2m, or should I pursue getting it fixed in zigbee2mqtt?
Thanks!

**Comment by itavero** [comment]
According to home-assistant/core#51793, the state is indeed related only to the _tilt_ position of the device.
I think the best workaround would be to just use the _tilt_ instead of the _position_, if no _position_ is present.
I'll see if I can find some time in the next week or so to implement this change.

**Comment by RMCob** [comment]
Thank you!

**Comment by itavero** [comment]
@RMCob Can you provide the full device entry from `zigbee2mqtt/bridge/devices`? It seems that you're missing a bit at the end. I'd like to use it for my automated test. 😉

**Comment by RMCob** [comment]
[zigbee_devices_info.txt](https://github.com/itavero/homebridge-z2m/files/6984368/zigbee_devices_info.txt)

**Comment by RMCob** [comment]
No pressure, just a question: when will these changes be in a version (Beta?) that I can try? Not sure what your release schedule is. Thanks again for doing this.....

**Comment by itavero** [comment]
@RMCob Currently working on a release. 😉  I was hoping to include support for some Air Quality sensors (as requested by others), but that proved to be a bit more challenging than I anticipated, hence the delay. I don't really have a tight release schedule, I generally try to release things within a week after implementing/fixing it.

**Comment by itavero** [comment]
v1.4.0 has been released
