### ISSUE TITLE
No devices found?

### ISSUE THREAD

**Issue by gmum4d** [itavero/homebridge-z2m#258]
I have just installed this plugin and MQTT on my Hoobs Box using the Youtube instructions from Eddie D'Souza (great work Eddie).  Everything seems to be running and connecting according to my log files, BUT I cannot add any devices I have put into pair mode?  I have tried an Aqara Mini Button, A Tradfri Mini Dimmer and 2 Hue Bulbs.  I have made sure the allowed pairing is on in the frontend but nothing shows up in the devices or the logs.  Can anyone help?

**Comment by itavero** [comment]
This sounds like a Zigbee2MQTT question, rather than an homebridge-z2m.

I would suggest to checkout the Zigbee2MQTT website at www.zigbee2mqtt.io or ask for help on their [Discord](https://discord.gg/NyseBeK).
