### ISSUE TITLE
Getting started using an IKEA outlet?

### ISSUE THREAD

**Issue by ouvoun** [itavero/homebridge-z2m#26]
Please forgive me for filing this, I just am unable to figure out how to get started using your library which seems awesome!

**Setup**
I'm running on `zigbee2mqtt` 1.16.2 through docker. Previously I had a working setup using deCONZ + Homebridge Hue, but I wanted to mix it up again since it seems like z2m has evolved very nicely over the past year.

I'm on a fresh setup and just added a single IKEA control outlet (E1603/E1702) to z2m. It sets up successfully:

```
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:25:11: Device '0x000d6ffffe7cb852' joined
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:25:11: Starting interview of '0x000d6ffffe7cb852'
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:25:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x000d6ffffe7cb852"},"type":"device_connected"}'
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:25:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x000d6ffffe7cb852"},"type":"pairing"}'
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:25:26: Successfully interviewed '0x000d6ffffe7cb852', device has successfully been paired
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:25:26: Device '0x000d6ffffe7cb852' is supported, identified as: IKEA TRADFRI control outlet (E1603/E1702)
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:25:26: Configuring '0x000d6ffffe7cb852'
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:25:26: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"TRADFRI control outlet","friendly_name":"0x000d6ffffe7cb852","model":"E1603/E1702","supported":true,"vendor":"IKEA"},"type":"pairing"}'
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:25:26: Successfully configured '0x000d6ffffe7cb852'
zigbee2mqtt    | Zigbee2MQTT:info  2020-12-05 11:26:08: MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"dateCode":"0x26660700","friendly_name":"Coordinator","ieeeAddr":"0x00212effff054339","lastSeen":1607196368683,"networkAddress":0,"softwareBuildID":"ConBee2/RaspBee2","type":"Coordinator"},{"dateCode":"20180528","description":"TRADFRI control outlet","friendly_name":"0x000d6ffffe7cb852","hardwareVersion":1,"ieeeAddr":"0x000d6ffffe7cb852","lastSeen":1607196326506,"manufacturerID":4476,"manufacturerName":"IKEA of Sweden","model":"E1603/E1702","modelID":"TRADFRI control outlet","networkAddress":6447,"powerSource":"Mains (single phase)","softwareBuildID":"1.4.020","type":"Router","vendor":"IKEA"}]'
```

Based on the instructions in the readme, I gathered the device identifier and put it into my homebridge config as a device:

```
{
    "mqtt": {
        "base_topic": "zigbee2mqtt",
        "server": "<server>",
        "user": "<username>",
        "password": "<password>",
        "reject_unauthorized": false,
        "keepalive": 60,
        "version": 4
    },
    "devices": [
        {
            "id": "0x000d6ffffe7cb852"
        }
    ],
    "platform": "zigbee2mqtt"
}
```

I checked the homebridge logs for homebridge-z2m, and found a few logs:

```
[12/5/2020, 11:26:08 AM] [zigbee2mqtt] Connected to MQTT server
[12/5/2020, 11:26:08 AM] [zigbee2mqtt] New accessory: 0x000d6ffffe7cb852
[12/5/2020, 11:26:08 AM] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x000d6ffffe7cb852/get': '{}'
```

However, the outlet doesn't show up in homebridge as a device. I tried restarting it a few times to no avail.

I feel like I'm probably missing something. I'm unsure whether I need to somehow fill in the capabilities of the device in my config? Or how I might even do that. Maybe I'm missing something obvious in the documentation, and if so please feel free to tell me to RTFM. 😄 

**Versions used**
 - This plugin: v0.0.10
 - Homebridge: v1.2.3
 - Zigbee2mqtt: v1.16.2
 - Homebridge Config UI X: v4.35.0

**Comment by itavero** [comment]
Hi @ouvoun. Thanks for giving the plugin a try.
The current version of the plugin needs to have seen an MQTT status message of the device in order to determine what kind of device it is (this is mentioned in the README).
It might help changing the state "manually" (on the device or by publishing a message to MQTT).
That usually also triggers a status update, as the state changed.

Please note that, due to recent improvements in zigbee2mqtt, I'm currently working on a new version of the plugin for which this "status message" requirement is no longer applicable.
See #18 for some more info and updates.

**Comment by ouvoun** [comment]
Ah, thank you @itavero!

Power cycling the outlet seemed to send a status update to MQTT and was picked up by the plugin. Excellent! Sorry I don't fully understand how MQTT works so I didn't realize that's what was meant by the paragraph in the readme.

Looking forward to the updated version, and thank you for making such a lovely plugin!
