### ISSUE TITLE
[Device] SmartThings IM6001-MPP01

### ISSUE THREAD

**Issue by drenwick** [itavero/homebridge-z2m#264]
**Device description**
SmartThings IM6001-MPP01 - Multi-purpose sensor. Vibration /moving not reporting. 

**Supported in Zigbee2MQTT?**
Is this device already supported by Zigbee2MQTT / zigbee-herdsman-converters? - YES
If this is the case, please provide the version in which support is present/added.
I am using: homebridge-z2m v1.6.0

**Device model / Exposes information**

```json
{
    "battery": 100,
    "battery_low": false,
    "contact": false,
    "linkquality": 255,
    "moving": false,
    "tamper": false,
    "temperature": 25.46,
    "x_axis": -1000,
    "y_axis": -95,
    "z_axis": -8
}
```

**Missing features/functionality**
Moving / Vibration is not being exposed / not visible in Homebridge via the plugin. 

**Suggested services and characteristics**
I can't see a suitable Service Type to map vibration / moving too. Perhaps map it to a stateless button like the Xiaomi | DJT11LM device

<img width="434" alt="Screenshot 2021-08-31 at 13 39 48" src="https://user-images.githubusercontent.com/5267522/131504084-ec9d5ce8-d04a-4074-9081-f6d3c9872282.png">

**Comment by itavero** [comment]
Please provide the device model (also known as [exposes information](https://www.zigbee2mqtt.io/information/exposes)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by Zigbee2MQTT.

**Comment by itavero** [comment]
Would it make sense to add a [Motion Sensor](https://developers.homebridge.io/#/service/MotionSensor) service and expose the `moving` parameter via the [Motion Detected](https://developers.homebridge.io/#/characteristic/MotionDetected) characteristic?

**Comment by drenwick** [comment]
Motion Sensors show up in HomeKit as Occupancy (don't they?). They don't really work in the same way as what I would consider a vibration sensor should - which would be to trigger a single event.
Full disclosure - I am far from an expert on Zigbee2MQTT / HomeBridge / HomeKit.

**Comment by itavero** [comment]
A _Motion Sensor_ is something different than a _Occupancy Sensor_, however both expose a binary characteristic on which you can add events. HomeKit has several of these "binary" sensors (a.o. _Leak Sensor_, _Smoke Detector_, _Contact Sensor_ and _Carbon Monoxide Sensor_). For both states of their binary characteristics, you can setup automations.

So in the Home.app you could say, if motion is detected (i.e. `moving = true`), then activate a certain scene/automation.
Or, if motion is no longer detect (i.e. `moving = false`), then activate another scene/automation.

**Comment by drenwick** [comment]
Ah - OK. I was basing my comment about Motion Sensor showing up as Occupancy because I'd tested a SmartThings 3325-S motion sensor (2015) model and it exposes 'occupancy' in Zigbee2MQTT and therefore the same in HomeKit.
If motion typically is exposed differently then sure it might well make sense to add a motion sensor service to expose the moving event. 

As clarity by the way - sorry I should have added this to the device support details - The reason I am keen to use this multi-purpose device is that when used in SmartThings (which I am trying to decommission) it gives me the full suite of functions (temp, open / close, acceleration and vibration) and on a front door - and vibration can detect a knock (I know - that seems obvious). I've been unable to find a suitable replacement for HomeKit and the use of the Xiaomi DJT11LM vibration sensor doesn't seem to be reliable to sensitive enough when compared to the rock solid Samsung sensor which I've had for years installed in the door. 

I am curious now to why the SmartThings 3325-S motion sensor  reports Occupancy and not motion? Can I change that do you think ? Perhaps a separate device support request on that one.

**Comment by itavero** [comment]
> I am curious now to why the SmartThings 3325-S motion sensor reports Occupancy and not motion? Can I change that do you think ? Perhaps a separate device support request on that one.

There has been a request before (#45). Personally I don't need it, so it's not high on my list.
In reality, in HomeKit there isn't really any difference with what you can do in terms of automation between an _Occupancy Sensor_ and an _Motion Sensor_.
Only the visible representation in the Home.app and perhaps how Siri informs you, is different.

A lot of people say that a PIR sensor is a "Motion Sensor". However, I work for a company that designs and manufactures sensors and controls for HVAC systems (amongst other things) and we use a PIR sensor to determine if a room is occupied.
Just an example to indicate that it's all about perspective. But again, for your automations it shouldn't matter.

**Comment by drenwick** [comment]
Thanks for the insight. I might go get myself a non-smartthing Motion Sensor to see how that works. Let me know if you need anything else on the Vibration / Moving device support request.
