### ISSUE TITLE
[Bug] Aqara Temperature and Humidity Sensor - "No pressure sensor"

### ISSUE THREAD

**Issue by poki123** [itavero/homebridge-z2m#275]
Hello,

is it possible to add pressure support for the Aqara Temperature and Humidity Sensor?

Thank you,
J.

**Comment by itavero** [comment]
This is already supported?

https://z2m.dev/devices/xiaomi/wsdcgq11lm.html

Do note that this is not a standard HomeKit service/characteristic (as none is defined by Apple for Air Pressure), so it will not show up in the Apple Home.app.
You will have to use a third party app, like Eve, to view it and add automations for it.

I have that particular sensor and this is what it looks like in Eve:
![image](https://user-images.githubusercontent.com/203398/131729862-a39cc35b-b393-47a1-8abb-1799dfb5f729.jpeg)
