### ISSUE TITLE
[Bug] Xiaomi Smoke Sensor, after disconnect not processed in HomeKiit as sensor unavailable...

### ISSUE THREAD

**Issue by xfishernet** [itavero/homebridge-z2m#278]
Xiaomi Smoke Sensor, after disconnect not processed in HomeKiit as sensor unavailable...

**Comment by itavero** [comment]
Please provide all the information requested in the [bug report template](https://raw.githubusercontent.com/itavero/homebridge-z2m/master/.github/ISSUE_TEMPLATE/bug_report.md).
I can't solve a "bug" based on just one sentence.

**Comment by xfishernet** [comment]
Device: Honeywell Smoke Detector (http://files.xiaomi-mi.co.uk/files/MiJia_Honeywell/MiJia_Honeywell_Smoke_Detector_EN.pdf)
Software: Homebridge + z2m plugin
z2m config:

` {
            "platform": "zigbee2mqtt",
            "mqtt": {
                "base_topic": "zigbee2mqtt",
                "server": "mqtt://localhost:1883",
                "reject_unauthorized": false,
                "keepalive": 60,
                "version": 4,
                "disable_qos": false
            },
            "defaults": {
                "exclude": false
            },
            "devices": []
        }`

After I disconnected the device from the network (disconnected the battery), HomeKit did not determine that it was offline even after a few hours.

**Comment by itavero** [comment]
This is not something currently supported by this plugin. Please also see #36

**Comment by xfishernet** [comment]
Ok, thanks for the quick reply!

**Comment by xfishernet** [comment]
Are there any plans to handle this?

**Comment by itavero** [comment]
> Are there any plans to handle this?

See the issue I've referenced in my previous comment.
