### ISSUE TITLE
[Feature] remap sensor type (contact into presence)

### ISSUE THREAD

**Issue by rcarmo** [itavero/homebridge-z2m#279]
Please use the template and fill in all the data requested below!

**Problem description**

I'd like to have some contact sensors surfaced into HomeKit as presence sensors

**Suggested solution**

Add a configuration setting to override the type and map the contact closed characteristic to presence detected

**Describe alternatives you've considered**

I have a Node-RED MQTT flow that does this, but requires me to expose the sensors separately.

**Additional context**

I am using Aqara sensors (both contact and presence), which is why I'm comparing both directly.

**Are you willing to contribute to this feature?**

Yes, provided there are enough hints to find the relevant bits of code to tweak. There might also be other kinds of sensors for which such a remapping is desirable.

**Comment by itavero** [comment]
Sounds like a duplicate of #46, which was closed due to inactivity.

**Comment by rcarmo** [comment]
Actually, I don’t see the resemblance. I want a configurable device type masking, not inverting a state.

**Comment by itavero** [comment]
They wanted to have some binary sensor (occupancy, if I remember correctly) to be exposed as another binary sensor (contact sensor).
Sounds very similar to me, or am I missing something?

**Comment by rcarmo** [comment]
Ah, I hadn't read the full discussion. Yes.

My idea would be to have an `override` or `callback` key where one could slot in a JS function that would convert the sensor type or its events. That would free up the main project from maintaining these hacks.

**Comment by itavero** [comment]
I don't think it's that straightforward, as you would also have to provide the Service and Characteristic type.
Having to insert JavaScript somewhere doesn't sound like a user friendly solution to me (I mean you might as well use [homebridge-mqttthing](https://www.npmjs.com/package/homebridge-mqttthing) if you know how that all works).
