### ISSUE TITLE
ability to split payload in to multiple requests

### ISSUE THREAD

**Issue by matrosovas** [itavero/homebridge-z2m#294]
**Problem description**
When turning both light switch gangs off the request is grouped to '{"state_left":"OFF","state_right":"OFF"}'  but this way only the 1st state updates. 

**Suggested solution**
Need ability to send one request per state with a debounce preferably. 

**Describe alternatives you've considered**
Apple shortcuts but that still would not solve leaving 1 light on if all home lights would be commanded to turn off

**Are you willing to contribute to this feature?**
Yes

**Comment by matrosovas** [comment]
Since that repository ignores this request, could you maybe point to a place in code that merges those requests into one? I would fork the repo and just use my own version then as this issue is really annoying in all the rooms with double switches. Thanks in advance!

**Comment by itavero** [comment]
It's not that straight forward to split it up, but combining is done in the accessory class (don't know the exact name out of the top of my head).

Can you reference the issue you have raised on the Zigbee2MQTT project?

**Comment by matrosovas** [comment]
First, thanks for being responsive! The issue is raised here: https://github.com/Koenkk/zigbee2mqtt/issues/9239

**Comment by onixx** [comment]
The same issue occurs with the GE plug in smart dimmer model 45852GE. Brightness and State on is published together and in this case only brightness is taken by device. State is ignored which results in the device not turning on. Republishing state on manually does turn on the device
