### ISSUE TITLE
Expose soil_moisture readings as humidity for homebridge

### ISSUE THREAD

**Issue by ChoBoMon** [itavero/homebridge-z2m#309]
Please use the template and fill in all the data requested below!

**Problem description**
Way to get soil_moisture readings to Homekit

**Suggested solution**
Convert soil_moisture reading as a humidity. So it would be possible to make some automations with it. (for example with EFEKTA_PWS)

**Describe alternatives you've considered**
Was thinking about using homeassistant instead of homebridge and homekit.

**Additional context**

**Are you willing to contribute to this feature?**
I dont have needed skills :/

**Comment by itavero** [comment]
It would be even better if we could figure out what characteristic is being used by existing HomeKit enabled soil moisture sensors, like the [one from votion|https://www.votion.io/products/soil-sensor]

**Comment by WojtekWro** [comment]
Thank you very much. I really appreciate your work. 
Can I help you somehow? Some tests?
