### ISSUE TITLE
[Bug] Changing only brightness and color temperature turns on bulb

### ISSUE THREAD

**Issue by chrisb86** [itavero/homebridge-z2m#324]
Please use the template and fill in all the data requested below!

**Describe the bug**
I have a setup with homekit automations that set scenes at a certain time (I change the color temperature and brightness of my ambient lights for da, evening end night settings). The scenes are set up to only change the brightness and temperature but leave the on/off state untouched. When I used deconz, this worked like a charme.

With zigbee2mqtt all related lights turn on when setting these scenes.

**Related devices**
Mostly hue bulbs.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Set a scene that only changes color temperature and brightness for bulbs that are switched off.
2. [23.11.2021, 20:37:09] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x00178801090cd17a/set': '{"color_temp":454,"brightness":114}'
3. The brightness and color temperature changes but the device turns on.

**Expected behavior**
I expect that the color temperature and brightness ist set but the state of the bulb stays untouched.

**MQTT messages**
If possible (and applicable), please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)

`{
    "date_code": "20210422",
    "definition": {
      "description": "Hue white ambiance E14 (with Bluetooth)",
      "exposes": [
        {
          "features": [
            {
              "access": 7,
              "description": "On/off state of this light",
              "name": "state",
              "property": "state",
              "type": "binary",
              "value_off": "OFF",
              "value_on": "ON",
              "value_toggle": "TOGGLE"
            },
            {
              "access": 7,
              "description": "Brightness of this light",
              "name": "brightness",
              "property": "brightness",
              "type": "numeric",
              "value_max": 254,
              "value_min": 0
            },
            {
              "access": 7,
              "description": "Color temperature of this light",
              "name": "color_temp",
              "presets": [
                {
                  "description": "Coolest temperature supported",
                  "name": "coolest",
                  "value": 150
                },
                {
                  "description": "Cool temperature (250 mireds / 4000 Kelvin)",
                  "name": "cool",
                  "value": 250
                },
                {
                  "description": "Neutral temperature (370 mireds / 2700 Kelvin)",
                  "name": "neutral",
                  "value": 370
                },
                {
                  "description": "Warm temperature (454 mireds / 2200 Kelvin)",
                  "name": "warm",
                  "value": 454
                },
                {
                  "description": "Warmest temperature supported",
                  "name": "warmest",
                  "value": 500
                }
              ],
              "property": "color_temp",
              "type": "numeric",
              "unit": "mired",
              "value_max": 500,
              "value_min": 150
            },
            {
              "access": 7,
              "description": "Color temperature after cold power on of this light",
              "name": "color_temp_startup",
              "presets": [
                {
                  "description": "Coolest temperature supported",
                  "name": "coolest",
                  "value": 150
                },
                {
                  "description": "Cool temperature (250 mireds / 4000 Kelvin)",
                  "name": "cool",
                  "value": 250
                },
                {
                  "description": "Neutral temperature (370 mireds / 2700 Kelvin)",
                  "name": "neutral",
                  "value": 370
                },
                {
                  "description": "Warm temperature (454 mireds / 2200 Kelvin)",
                  "name": "warm",
                  "value": 454
                },
                {
                  "description": "Warmest temperature supported",
                  "name": "warmest",
                  "value": 500
                },
                {
                  "description": "Restore previous color_temp on cold power on",
                  "name": "previous",
                  "value": 65535
                }
              ],
              "property": "color_temp_startup",
              "type": "numeric",
              "unit": "mired",
              "value_max": 500,
              "value_min": 150
            }
          ],
          "type": "light"
        },
        {
          "access": 2,
          "description": "Triggers an effect on the light (e.g. make light blink for a few seconds)",
          "name": "effect",
          "property": "effect",
          "type": "enum",
          "values": [
            "blink",
            "breathe",
            "okay",
            "channel_change",
            "finish_effect",
            "stop_effect"
          ]
        },
        {
          "access": 1,
          "description": "Link quality (signal strength)",
          "name": "linkquality",
          "property": "linkquality",
          "type": "numeric",
          "unit": "lqi",
          "value_max": 255,
          "value_min": 0
        }
      ],
      "model": "9290022944",
      "options": [
        {
          "access": 2,
          "description": "Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition).",
          "name": "transition",
          "property": "transition",
          "type": "numeric",
          "value_min": 0
        },
        {
          "access": 2,
          "description": "When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true).",
          "name": "color_sync",
          "property": "color_sync",
          "type": "binary",
          "value_off": false,
          "value_on": true
        }
      ],
      "supports_ota": true,
      "vendor": "Philips"
    },
    "endpoints": {
      "11": {
        "bindings": [],
        "clusters": {
          "input": [
            "genBasic",
            "genIdentify",
            "genGroups",
            "genScenes",
            "genOnOff",
            "genLevelCtrl",
            "touchlink",
            "develcoSpecificAirQuality",
            "lightingColorCtrl"
          ],
          "output": [
            "genOta"
          ]
        },
        "configured_reportings": [],
        "scenes": []
      },
      "242": {
        "bindings": [],
        "clusters": {
          "input": [],
          "output": [
            "greenPower"
          ]
        },
        "configured_reportings": [],
        "scenes": []
      }
    },
    "friendly_name": "Flur Kommode",
    "ieee_address": "0x00178801090cd17a",
    "interview_completed": true,
    "interviewing": false,
    "manufacturer": "Signify Netherlands B.V.",
    "model_id": "LTE002",
    "network_address": 7109,
    "power_source": "Mains (single phase)",
    "software_build_id": "1.88.2",
    "supported": true,
    "type": "Router"
  },`

* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
`{"brightness":114,"color_mode":"color_temp","color_temp":454,"linkquality":255,"state":"OFF","update":{"state":"idle"},"update_available":false}`
Changes to:
`{"brightness":8,"color_mode":"color_temp","color_temp":454,"linkquality":255,"state":"ON","update":{"state":"idle"},"update_available":false}`

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin: homebridge-z2m v1.6.1 
 - Homebridge: v1.3.8 
 - Zigbee2MQTT: commit a51626e3
 - Homebridge Config UI X: homebridge-config-ui-x v4.41.2

**Comment by itavero** [comment]
The data send to Zigbee2MQTT via MQTT doesn't contain a `state` change. I think this behavior is caused by Zigbee2MQTT, not this plugin.
