### ISSUE TITLE
ikea switch/button requiers a home hab to be used with the home app

### ISSUE THREAD

**Issue by mpuff** [itavero/homebridge-z2m#325]
Hello,

i have a lot of devices, only the ikea switch E1743 and ikea button E1812 are giving me the info in the homebridge that it is required a home hub to be used with the home app.

kind regards,
martin

**Comment by itavero** [comment]
What is the actually issue here?

**Comment by mpuff** [comment]
I can't control these devices, they are not shown as switch

**Comment by itavero** [comment]
Can you provide the information requested in the Bug Report issue template?
Perhaps the answers to those questions will make it more clear to me.
