### ISSUE TITLE
[Device support] IKEA STARKVIND

### ISSUE THREAD

**Issue by smartmatic** [itavero/homebridge-z2m#333]
Please use the template and fill in all the data requested below!

**Describe the bug**
I've installed the latest zigbee2mqtt release 1.22.1 and with this release the IKEA STARKVIND Air Purifier is fully supported and can fully controlled within zigbee2mqtt.

[https://www.zigbee2mqtt.io/devices/E2007.html#ikea-e2007](url)

It is is not possible to switch the Air Purifier on or off or change the fan mode as only the Air Quality information is displayed in Homebridge

**Related devices**
[https://www.zigbee2mqtt.io/devices/E2007.html#ikea-e2007](url)

**To Reproduce**
Add device to zigbee2mqtt and try to control the device via Homebridge

**Expected behavior**
My expectation was to get at least two Homebridge Devices. One for the Air Purifier and one for the Air Quality but Homebridge shows only the Air Quality Sensor. Therefore it is is not possible to switch the Air Purifier on or off or change the fan mode.

**MQTT messages**
If possible (and applicable), please provide the following:

**Versions used**
Please provide the version of the following pieces of software:
 - Plugin version: v1.6.1
 - Homebridge: 1.3.8
 - Homebridge Config UI X: v4.41.3

**Comment by itavero** [comment]
This is not a bug. Fans are not supported at the moment. Even on the [page for this device](https://z2m.dev/devices/ikea/e2007.html) it only shows the Air Quality Sensor.
I do wonder if the PM10 is correct though. I thought it had a PM2.5 sensor.

Based on the issue template for _Device support_, please provide the following:
* device model (also known as [exposes information](https://www.zigbee2mqtt.io/information/exposes)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by Zigbee2MQTT.
* describe the features/functionality of this device that are currently not exposed to HomeKit via this plugin.

For each of the missing features, please mention to which HomeKit Services and Characteristics it should be mapped.
The [Homebridge Plugin Development documentation](https://developers.homebridge.io/) provides a nice overview of the standard HomeKit services and characteristics.
Note that some manufacturers also use custom services and characteristics (the Elgato Eve products for instance), which could also be mimicked if they have been reverse engineered.

**Comment by smartmatic** [comment]
> page for this device

I am a bit confused about your answer. What do you exactly mean with Fans are not supported a the moment?
Not supported through this plugin? 

My current understanding from this plugin is that all devices listed here [https://zigbee.blakadder.com](url) and marked with zigbee2mqtt should be available through this plugin here.
Please correct me if this expectation and common understanding is wrong?

The current zigbee2mqtt integration fully supports all functionalities which the IKEA STARKVIND offers. The full integration is described here: [https://www.zigbee2mqtt.io/devices/E2007.html#ikea-e2007](url)

I observed that it is currently not possible to activate and deactivate the device and also not to control the fan with this plugin. But with FHEM in the background and appropriate homebridge mappings i am able to nearly fully control the STARKVIND except the Child Lock. But i can switch on and off the device and i change the fan speed with Apple Home App.

I used the following Homekit services and characteristics
**Homekit Service: Air Purifier**
Active
Current Air Purifier State
Target Air Purifier State
Rotation Speed

**Homekit Service: AirQualitySensor**
Air Quality

The IKEA STARKVIND provides PM2.5 density

Hope that helps in a first step?

**Comment by itavero** [comment]
Not all devices that are supported by Zigbee2MQTT, are supported homebridge-z2m.
That site only shows compatibility with Zigbee2MQTT.

Can you also add the `exposes` info for the device?

**Comment by itavero** [comment]
Generated `exposes` info:
```json
[
  {
    "type": "fan",
    "features": [
      {
        "type": "binary",
        "name": "state",
        "property": "fan_state",
        "access": 7,
        "value_on": "ON",
        "value_off": "OFF",
        "description": "On/off state of this fan"
      },
      {
        "type": "enum",
        "name": "mode",
        "property": "fan_mode",
        "access": 7,
        "values": [
          "off",
          "auto",
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9"
        ],
        "description": "Mode of this fan"
      }
    ]
  },
  {
    "type": "numeric",
    "name": "fan_speed",
    "property": "fan_speed",
    "access": 5,
    "value_min": 0,
    "value_max": 9,
    "description": "Current fan speed"
  },
  {
    "type": "numeric",
    "name": "pm25",
    "property": "pm25",
    "access": 5,
    "unit": "µg/m³",
    "description": "Measured PM2.5 (particulate matter) concentration"
  },
  {
    "type": "enum",
    "name": "air_quality",
    "property": "air_quality",
    "access": 5,
    "values": [
      "excellent",
      "good",
      "moderate",
      "poor",
      "unhealthy",
      "hazardous",
      "out_of_range",
      "unknown"
    ],
    "description": "Measured air quality"
  },
  {
    "type": "binary",
    "name": "led_enable",
    "property": "led_enable",
    "access": 7,
    "value_on": true,
    "value_off": false,
    "description": "Enabled LED"
  },
  {
    "type": "binary",
    "name": "child_lock",
    "property": "child_lock",
    "access": 7,
    "value_on": "LOCK",
    "value_off": "UNLOCK",
    "description": "Enables/disables physical input on the device"
  },
  {
    "type": "binary",
    "name": "replace_filter",
    "property": "replace_filter",
    "access": 5,
    "value_on": true,
    "value_off": false,
    "description": "Filter is older than 6 months and needs replacing"
  },
  {
    "type": "numeric",
    "name": "linkquality",
    "property": "linkquality",
    "access": 1,
    "unit": "lqi",
    "description": "Link quality (signal strength)",
    "value_min": 0,
    "value_max": 255
  }
]
```

**Comment by itavero** [comment]
Looking at the `exposes` information, there's no way to "see" that this is an air purifier. It exposes itself as a `fan`.

Unfortunately the `fan_modes` are slightly different than other fans supported by Zigbee2MQTT, but I guess I can work around that.

**Comment by itavero** [comment]
`replace_filter` can be exposed as a [Filter Maintenance](https://developers.homebridge.io/#/service/FilterMaintenance) service.

**Comment by ComicBit** [comment]
Is it anyone gonna look trough this?

**Comment by itavero** [comment]
> Is it anyone gonna look trough this? 

Not sure what you mean. I look through the open issues when I have time to see if there's stuff I can do with the time I think I have available. Unfortunately I don't have that much spare time on my hands currently (still need to earn a living and spend time with my family).

Main reason I reopened this one is to keep all information on one location.

**Comment by ComicBit** [comment]
> > Is it anyone gonna look trough this?
> 
> Not sure what you mean. I look through the open issues when I have time to see if there's stuff I can do with the time I think I have available. Unfortunately I don't have that much spare time on my hands currently (still need to earn a living and spend time with my family).
> 
> Main reason I reopened this one is to keep all information on one location.

I totally get what you mean, I just wanted to understand if it makes sense to keep it open or there are no chances of developing the integration further

**Comment by JeanMertz** [comment]
Came here looking for this as well. Is there any way to keep "feature request" issues open, to make it easier to find them?

**Comment by ComicBit** [comment]
> Came here looking for this as well. Is there any way to keep "feature request" issues open, to make it easier to find them?
I tried to implement it myself but it's very hard and the documentation it's pretty complicated to grasp. I would love to have the full support, because as right now it's just sitting there being barely used

**Comment by JayJay-Master** [comment]
I would also be interested in being able to address the other properties via homebridge-z2m.
Maybe someone can take pity on it again and realize full support for homebridge.

**Comment by Avamander** [comment]
I'll try and take a look this week, but it seems a bit complex to set up a Homebridge-Z2M development environment with everything needed.

**Comment by ComicBit** [comment]
@Avamander thank you! I wish I ever got to try but time is not on my side 😄  let me know if there is anything I can help you with though!

**Comment by Avamander** [comment]
I've finished initial air purifier support in https://github.com/itavero/homebridge-z2m/pull/1012

Works great to change the speed (or child lock setting) on my STARKVIND.
