### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Leseptiemeciel** [itavero/homebridge-z2m#337]
**Expose power**
Hi, I added a E1C-NB7 Sengled smart plug with energy. I can see energy reading on zigbee2mqtt but it’s not passing trough z2m. Only on/off appears on Eve app. 

**Suggested solution**
Would be nice to expose power to homekit

**Are you willing to contribute to this feature?**
Yes

**Comment by itavero** [comment]
Related to #96

**Comment by Leseptiemeciel** [comment]
![image](https://user-images.githubusercontent.com/96351056/146660733-b07512c7-6171-4220-b274-10d36d06509c.jpeg)

![image](https://user-images.githubusercontent.com/96351056/146660736-4e9e4919-964c-419f-a1be-099558399c7e.jpeg)

Got this from Zigbee2mqtt if it can help

**Comment by Leseptiemeciel** [comment]
![image](https://user-images.githubusercontent.com/96351056/146660981-0a789d96-3090-4d75-8edf-58d0658df7aa.jpeg)

**Comment by itavero** [comment]
If someone would be able to give #1155 a go on their system as well, that would be great.

(You can check out the branch, run `npm ci`, `npm build` and lastly `npm link` to do so).

**Comment by itavero** [comment]
This is now released in [v1.11.0-beta.11](https://github.com/itavero/homebridge-z2m/releases/tag/v1.11.0-beta.11) 🚀
