### ISSUE TITLE
[question] Exclude part of device from HomeKit 

### ISSUE THREAD

**Issue by WojtekWro** [itavero/homebridge-z2m#338]
Hello,
The question “how to … “
I have couple of Aqara devices like leak sensor, motion sensor, …
They expose temperature to HomeKit. In my opinion the measurement is not accurate and I don’t want it in HomeKit. 
Is there any chance to remove it?

**Comment by itavero** [comment]
You can exclude keys via the [plug-in configuration](https://z2m.dev/config.html#devices).

**Comment by WojtekWro** [comment]
Thank you. 
It works as expected. 
However I couldn’t exclude window detection key in radiator valve accessory. 
Any chance to get rid of this switch from HomeKit?

**Comment by WojtekWro** [comment]
Thank you.
