### ISSUE TITLE
Outlet instead of Switch?

### ISSUE THREAD

**Issue by cnekola** [itavero/homebridge-z2m#380]
Hi,

is it possible to change the device type from switch to outlet?

thx, Chris

**Comment by itavero** [comment]
Not a bug, as it is simply not supported at the moment.

Possible duplicate of #45 / #279.

**Comment by cnekola** [comment]
Hi,

thx, for the answer. And sorry, I can't found a correct tag for my questions thus I used "bug".
Do you plan to support this feature in the future? Also a device renaming would be ingenious.

BTW, I love you plugin. very good job.

br, chris

**Comment by itavero** [comment]
> Do you plan to support this feature in the future?

I'm not against it, but as mentioned in #45, it doesn't really have a high priority to me. I don't see what the real benefit would be, at least not within how I use HomeKit/Siri (but your use cases might be different of course).
Therefor I'm open for suggestions/PRs from others to provide such functionality in a generic way, without breaking backwards compatibility for users that don't care about this.

> Also a device renaming would be ingenious.

Not sure what you mean by this?
You can rename devices in the frontend of Zigbee2MQTT and/or via the HomeKit app (these are not synced however).
If you change a name in the Zigbee2MQTT frontend, it should automatically be picked up by this plugin and if you have not set a custom name in the HomeKit app, it should also propogate there.
As mentioned in #76, you might have to restart Homebridge for HomeKit to also pick up the new name for some reason.

> BTW, I love you plugin. very good job.

Thank you. Glad you enjoy it!

**Comment by cnekola** [comment]
Hi,

you are right. No benefit, only optic ;)
Other plugins support this feature. 
Homematic: "outlets": [ "HmIP-RF.00021A4995E371:3","BidCos-RF.LEQ0532532:1","BidCos-RF.LEQ1344292:1" ]
I have no clue how complex this is. 

Rename:
I have about over 70 zigbee devices in my configuration.yaml file with a own name schema. I used this in my node red config.
The name schema is not Homekit friendly thus I must rename the devices in the Homekit App. Is not user friendly on phone ;)
But again I have no idea how complicated this is.

thx for your time, Chris

**Comment by cnekola** [comment]
hi, yes. thx. this issue can be close.
