### ISSUE TITLE
[Device] AC0251700NJ OSRAM SMART MINI SWITCH

### ISSUE THREAD

**Issue by stodla123** [itavero/homebridge-z2m#382]
It is a cheap three button device:
https://www.zigbee2mqtt.io/devices/AC0251100NJ_AC0251600NJ_AC0251700NJ.html

**Device description**
AC0251700NJ - OSRAM SMART MINI SWITCH

**Supported in Zigbee2MQTT?**
Is this device already supported by Zigbee2MQTT / zigbee-herdsman-converters?   

->YES it is successfully paired, payload "on" "off" is shown as buttons are pressed.

**Device model / Exposes information**

Feb 11 09:52:45 raspberrypi npm[1936]: Zigbee2MQTT:info  2022-02-11 09:52:45: Successfully interviewed '0x000d6f00109c65b8', device has successfully been paired
Feb 11 09:52:45 raspberrypi npm[1936]: Zigbee2MQTT:info  2022-02-11 09:52:45: Device '0x000d6f00109c65b8' is supported, identified as: OSRAM Smart+ switch mini (AC0251100NJ/AC0251600NJ/AC0251700NJ)
Feb 11 09:52:45 raspberrypi npm[1936]: Zigbee2MQTT:info  2022-02-11 09:52:45: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Smart+ switch mini","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["up","up_hold","up_release","down_release","circle_release","circle_hold","down","down_hold","circle_click"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"AC0251100NJ/AC0251600NJ/AC0251700NJ","options":[{"access":2,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true).","name":"legacy","property":"legacy","type":"binary","value_off":false,"value_on":true}],"supports_ota":true,"vendor":"OSRAM"},"friendly_name":"0x000d6f00109c65b8","ieee_address":"0x000d6f00109c65b8","status":"successful","supported":true},"type":"device_interview"}'

OFF BUTTON:

Feb 11 10:10:03 raspberrypi npm[2055]: Zigbee2MQTT:info  2022-02-11 10:10:03: MQTT publish: topic 'zigbee2mqtt/JalousieWohnzimmerBalkontuere', payload '{"action":"off","linkquality":55}'

MIDDLE BUTTON:

Feb 11 10:10:06 raspberrypi npm[2055]: Zigbee2MQTT:info  2022-02-11 10:10:06: MQTT publish: topic 'zigbee2mqtt/JalousieWohnzimmerBalkontuere', payload '{"action":"color_temperature_move","action_color_temperature":370,"action_transition_time":10,"linkquality":44}'

ON BUTTON:

Feb 11 10:10:06 raspberrypi npm[2055]: Zigbee2MQTT:info  2022-02-11 10:10:06: MQTT publish: topic 'zigbee2mqtt/JalousieWohnzimmerBalkontuere', payload '{"action":"on","linkquality":44}'

Feb 11 10:07:20 raspberrypi npm[2055]: Zigbee2MQTT:info  2022-02-11 10:07:20: MQTT publish: topic 'zigbee2mqtt/JalousieWohnzimmerBalkontuere', payload '{"action":"on","linkquality":57}'

```json

That's what i get from the z2m frontend:

{
    "battery": 80,
    "linkquality": 89,
    "voltage": 2900
}

```

**Missing features/functionality**
Please describe the features/functionality of this device that are currently not exposed to HomeKit via this plugin.

**Suggested services and characteristics**
payload "ON" "OFF" "MIDDLE-BUTTON" 

In homekit-app three buttons are shown but they dont work, if a scene is assigned no action happens.

Gerätename
JalousieWohnzimmerBalkontuere
Zuletzt gesehen
N/A
Verfügbarkeit
[Deaktiviert](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
Geräte Typ
EndDevice
Zigbee Modell
Lightify Switch Mini
Zigbee Hersteller
[OSRAM](https://www.zigbee2mqtt.io/supported-devices/#v=OSRAM)
Beschreibung
Smart+ switch mini
Unterstützungsstatus
unterstützt

IEEE Addresse
0x000d6f00109c65b8
Netzwerk Adresse
0x402B
Firmware Datum
201803271005270
Firmware Version
e.1.11.0M
Hersteller
OSRAM
Modell
[AC0251100NJ/AC0251600NJ/AC0251700NJ](https://www.zigbee2mqtt.io/devices/AC0251100NJ_AC0251600NJ_AC0251700NJ.html#osram-ac0251100nj%252Fac0251600nj%252Fac0251700nj)
Spannungsversorgung
Batterie 
Interview erfolgreich
![IMG_2366](https://user-images.githubusercontent.com/64693317/153565320-49174563-9da9-4a34-b2c8-9a55e53f3231.PNG)

Wahr

**Comment by itavero** [comment]
The list of actions in the data you provided is:
`["up","up_hold","up_release","down_release","circle_release","circle_hold","down","down_hold","circle_click"]`

According to that there is no `on` or `off` action.

There might be a `legacy` device option for this device in Zigbee2MQTT (but usually that would be listed on the their website).

Otherwise, this should probably be fixed in [Koenkk/zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters)

**Comment by stodla123** [comment]
Thank you very much! The "legacy option" resolved it:

![image](https://user-images.githubusercontent.com/64693317/153566370-7dfbeccf-4cf2-4709-b2fe-d333f9f2a9ff.png)


Thanks a lot!
