### ISSUE TITLE
[Bug] TS0601 cover

### ISSUE THREAD

**Issue by manfilof** [itavero/homebridge-z2m#385]
Please use the template and fill in all the data requested below!

**Describe the bug**
HB is sending the MQTT topic without "/set".
![Curtain_3](https://user-images.githubusercontent.com/69819178/154809760-ba378f2b-f092-4a16-bd80-176b9e42b46b.JPG)
![Curtain_2](https://user-images.githubusercontent.com/69819178/154809761-de7d2947-489b-4274-86c8-51054b1cc98b.JPG)
![Curtain](https://user-images.githubusercontent.com/69819178/154809762-c42d952a-ac70-4935-840c-9f4419a855dd.JPG)

**Related devices**
Tuya Zigbee Curtain Motor (https://aliexpress.ru/item/4000739390813.html?aff_fcid=8f7004c95a95472d9aef2d1fa3142551-1645286877793-00860-_ASdhwf&aff_fsk=_ASdhwf&aff_platform=default&aff_trace_key=8f7004c95a95472d9aef2d1fa3142551-1645286877793-00860-_ASdhwf&bizType=ProductDetail&businessType=ProductDetail&platform=AE&shareId=40162348846&sk=_ASdhwf&sku_id=12000027106634417&social_params=40162348846&spreadType=socialShare&srcSns=sns_More&terminal_id=940c926ba186444bb786d1e09627863d&tt=MG)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Connect device to zigbee2mqtt.
2. Try to open/close (run/stop) motor in zigbee2mqtt UI, it works.
2. Install z2m plugin in homebridge
3. Device adds in homebridge.
4. Try to open/close (run/stop) motor, nothing happens.
5. Device id = 0x2c1165fffe4f03b3. Device friendly name = Bedroom Curtain Motor.

**Expected behavior**
Expected that motor will run, but nothing happens.

**MQTT messages**
If possible (and applicable), please provide the following:
HB sends two topics at the moment of pushing button in HB/Homekit
1. zigbee2mqtt/Bedroom Curtain Motor
{"linkquality":168,"position":100,"running":true,"state":"OPEN"}
2. zigbee2mqtt/0x2c1165fffe4f03b3/set
{"position":100}

There is an issue that 1st topic is without "/set". Despite I provided the friendly name, the second topic uses the device id instead of friendly name.

I tried to send message with "/set" using the MQTT.fx and it worked.
e.g. zigbee2mqtt/Bedroom Curtain Motor/set {"linkquality":168,"position":100,"running":true,"state":"OPEN"}

HB publish log:
[19/02/2022, 16:24:34] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x2c1165fffe4f03b3/set': '{"position":100}'

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin - v1.6.2
 - Homebridge - v1.3.9
 - Zigbee2MQTT - v1.23.0
 - Homebridge Config UI X - v4.41.5

**Comment by manfilof** [comment]
Looks like the "zigbee2mqtt/Bedroom Curtain Motor {"linkquality":168,"position":100,"running":true,"state":"OPEN"}" should be with "/set" and "zigbee2mqtt/0x2c1165fffe4f03b3/set {"position":100}" should be w/o "/set", just getting the current position of curtains...but that's just my guess.

**Comment by manfilof** [comment]
Topics with 0x2c1165fffe4f03b3 are not working, it works only with friendly name

**Comment by itavero** [comment]
Sorry, but I don't think what you are saying can be true.

There is no code in the plugin that will publish to the device topic.
This is most likely Zigbee2MQTT itself, sending a status update.
The plugin always publishes to `/set` or `/get` (as you've probably also seen in the logs from Homebridge).

Can you manually send the message from the logs, the one with just the `position` being set, to the `/set` topic also mentioned there?

If manually sending different positions also doesn't get the cover to work, then it might be an issue with the implementation in Zigbee2MQTT itself.

**Comment by manfilof** [comment]
Nothing additional was done in Zigbee2MQTT, moreover I have deleted device from Zigbee2MQTT and added it again before raising the issue. The device

Done some tests:

1. Sending "position" with set with IEEE.
zigbee2mqtt/0x2c1165fffe4f03b3/set {"position":25}

Failed. Nothing happens.

2.  Sending "position" with set with friendly name.
zigbee2mqtt/Bedroom Curtain Motor/set {"position":25}

Failed. Nothing happens.

3. Sending "state" with set with IEEE.
zigbee2mqtt/0x2c1165fffe4f03b3/set {"state":"OPEN"}

Passed. Working.

4. Sending "state" with set with friendly name.
zigbee2mqtt/Bedroom Curtain Motor/set {"state":"OPEN"}

Passed. Working.

5. Open questions.
- What is the parameter to run the motor? Position or state? Currently is seems that state control the motor. At least in Zigbee2MQTT I can control the motor by changing the state.
![state](https://user-images.githubusercontent.com/69819178/154835077-d4c4fb66-e970-48a9-a3fe-089bdbab79c2.JPG)

**Comment by itavero** [comment]
The plugin uses `position` to control the position.

**Comment by itavero** [comment]
Can you provide the device entry from the `zigbee2mqtt/bridge/devices` MQTT topic?
(note: this is different from `zigbee2mqtt/bridge/config/devices`)

That should contain the device model and "exposes" information.

**Comment by manfilof** [comment]
Hope that is you requested. Tried to divide this device from others. Btw, attached all config for all devices.
[zigbee2mqtt-bridge-devices.txt](https://github.com/itavero/homebridge-z2m/files/8104431/zigbee2mqtt-bridge-devices.txt)


{"date_code":"","definition":{"description":"Curtain motor/roller blind motor/window pusher/tubular motor","exposes":[{"features":[{"access":3,"name":"state","property":"state","type":"enum","values":["OPEN","CLOSE","STOP"]},{"access":3,"description":"Position of this cover","name":"position","property":"position","type":"numeric","value_max":100,"value_min":0}],"type":"cover"},{"features":[{"access":3,"description":"Motor speed","name":"motor_speed","property":"motor_speed","type":"numeric","value_max":255,"value_min":0}],"name":"options","property":"options","type":"composite"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0601_cover","options":[{"access":2,"description":"Inverts the cover position, false: open=100,close=0, true: open=0,close=100 (default false).","name":"invert_cover","property":"invert_cover","type":"binary","value_off":false,"value_on":true}],"supports_ota":false,"vendor":"TuYa"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genTime","genGroups","genScenes","manuSpecificTuya"],"output":["genOta"]},"configured_reportings":[],"scenes":[]}},"friendly_name":"Bedroom Curtain Motor","ieee_address":"0x2c1165fffe4f03b3","interview_completed":true,"interviewing":false,"manufacturer":"_TZE200_nogaemzt","model_id":"TS0601","network_address":31420,"power_source":"Mains (single phase)","supported":true,"type":"Router"},{"definition":{"description":"MiJia wireless switch","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["single","double","triple","quadruple","hold","release","many"]},{"access":1,"description":"Voltage of the battery in millivolts","name":"voltage","property":"voltage","type":"numeric","unit":"mV"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"WXKG01LM","options":[{"description":"The WXKG01LM only reports a button press and release.By default, a hold action is published when there is at least 1000 ms between both events. It could be that due to delays in the network the release message is received late. This causes a single click to be identified as a hold action. If you are experiencing this you can try experimenting with this option (e.g. set it to 2000) (value is in ms).","name":"hold_timeout","property":"hold_timeout","type":"numeric","value_min":0},{"description":"Sometimes it happens that the button does not send a release. To avoid problems a release is automatically send after a timeout. The default timeout is 4000 ms, you can increase it with this option (value is in ms).","name":"hold_timeout_expire","property":"hold_timeout_expire","type":"numeric","value_min":0},{"access":2,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true).","name":"legacy","property":"legacy","type":"binary","value_off":false,"value_on":true}]

**Comment by manfilof** [comment]
Speaking about the position I also could not control the motor by changing the cursor/value in zigbee2mqtt.

**Comment by itavero** [comment]
Did you already set the start and end limits of the device?
I remember I also had a Tuya based cover motor in the past, for which I first had to configure the limits on the device, before the position worked correctly.

**Comment by itavero** [comment]
According to the `exposes` information you have provided, it should be able to set the `position` according to Zigbee2MQTT (`access: 3` means that the value can be set and will be published by the device, but can not be get):
```json
       {
            "access":3,
            "description":"Position of this cover",
            "name":"position",
            "property":"position",
            "type":"numeric",
            "value_max":100,
            "value_min":0
          }
```

**Comment by manfilof** [comment]
> also had a Tuya based cover motor in the past, for which I first had to configure the limit

not yet, since the rail is on the way. Any idea how it should be done? Should I change the config after installing the rail and motor?

Anyway, I suppose it should works by changing the "position", but it does not.

**Comment by itavero** [comment]
For the motor I had, I had to use buttons on the motor it self.
