### ISSUE TITLE
[Device] Tuya Thermostat valve

### ISSUE THREAD

**Issue by mojijafari** [itavero/homebridge-z2m#39]
Dear itavero,
First of all, I should thank you very much for your kind effort. I appretite your work. Is there any way to help you with new devices? you can not buy all of them, however we have some, is there any way to share the data of them with you, or help for coding? Or if you can invent the structure that any one can establish a connection and add new device, would be great. we have specefic type of zigbees and with your kind work, all of them could work.

my next offer is the pairing button and reset button. isn't better to add new button in homebridge to reset and/or pair new devices?

By the way, I have new Tuya thermostat that z2m recognize it as curtain :)

**Comment by itavero** [comment]
Providing the data mentioned in the issue template helps with adding support for new devices (mostly from MQTT messages).

Which version of the plug-in are you running?
homebridge-z2m v1 and newer should not show your thermostat as a window covering, unless Zigbee2MQTT is reporting it incorrectly.

Please note that support for thermostats is not in homebridge-z2m yet. See #32 and #37

**Comment by itavero** [comment]
With regards to managing your Zigbee network and adding/removing devices, please have a look at the [web frontend](https://www.zigbee2mqtt.io/information/frontend.html) of zigbee2mqtt.
It provides a better experience for those use cases then I will be able to provide within the constraints of HomeKit.

**Comment by itavero** [comment]
For your specific device, can you please provide the device model (also known as [exposes information](https://www.zigbee2mqtt.io/information/exposes)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by zigbee2mqtt.
That way I can take it into account in the automated test suite when I start implementing support for `climate` devices.

**Comment by mojijafari** [comment]
> For your specific device, can you please provide the device model (also known as [exposes information](https://www.zigbee2mqtt.io/information/exposes)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by zigbee2mqtt.
> That way I can take it into account in the automated test suite when I start implementing support for `climate` devices.

Thank you very much. I opened zigbee2mqtt folder and did not see bridge folder. How can I find that?

**Comment by mojijafari** [comment]
igbeeModel: ['kud7u2l'],
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_ckud7u2l'}],
        model: 'TS0601_thermostat',
        vendor: 'TuYa',
        description: 'Radiator valve with thermostat',
        whiteLabel: [{vendor: 'Moes', model: 'HY369RT'}, {vendor: 'SHOJZJ', model: '378RT'}],
        meta: {tuyaThermostatPreset: tuya.thermostatPresets, tuyaThermostatSystemMode: tuya.thermostatSystemModes3},
        ota: ota.zigbeeOTA,
        onEvent: tuya.onEventSetLocalTime,
        fromZigbee: [fz.tuya_thermostat, fz.ignore_basic_report, fz.ignore_tuya_set_time],
        toZigbee: [tz.tuya_thermostat_child_lock, tz.tuya_thermostat_window_detection, tz.tuya_thermostat_valve_detection,
            tz.tuya_thermostat_current_heating_setpoint, tz.tuya_thermostat_auto_lock,
            tz.tuya_thermostat_calibration, tz.tuya_thermostat_min_temp, tz.tuya_thermostat_max_temp,
            tz.tuya_thermostat_boost_time, tz.tuya_thermostat_comfort_temp, tz.tuya_thermostat_eco_temp,
            tz.tuya_thermostat_force_to_mode, tz.tuya_thermostat_force, tz.tuya_thermostat_preset, tz.tuya_thermostat_away_mode,
            tz.tuya_thermostat_window_detect, tz.tuya_thermostat_schedule, tz.tuya_thermostat_week, tz.tuya_thermostat_away_preset],
        exposes: [
            e.child_lock(), e.window_detection(), e.battery_low(), e.valve_detection(), e.position(),
            exposes.climate().withSetpoint('current_heating_setpoint', 5, 35, 0.5, exposes.access.STATE_SET)
                .withLocalTemperature(exposes.access.STATE).withSystemMode(['heat', 'auto', 'off'], exposes.access.STATE_SET)
                .withRunningState(['idle', 'heat'], exposes.access.STATE)
                .withLocalTemperatureCalibration(exposes.access.STATE_SET)
                .withAwayMode().withPreset(['schedule', 'manual', 'boost', 'complex', 'comfort', 'eco']),
            e.auto_lock(), e.away_mode(), e.away_preset_days(), e.boost_time(), e.comfort_temperature(), e.eco_temperature(), e.force(),
            e.max_temperature(), e.min_temperature(), e.week()],

is this what you want?

**Comment by itavero** [comment]
If the topic does not exist, it might be that you are running an old version of Zigbee2MQTT.

Which version of Zigbee2MQTT and of this plugin are you using?

**Comment by mojijafari** [comment]
I'm sorry for misundertanding, this is what I have [https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html]. It works with home assisstant and it's interface in homekit, but it can't use directly in homebridge.

thank you in advance

**Comment by itavero** [comment]
Opened up #40 to group all the individual request for thermostat/TRV support in one place, as these will most likely be handled by the same code.

Because of that I'm closing this issue. Updates/discussion should be done in this new issue.
