### ISSUE TITLE
[Bug] Home app requires two presses for lights... odd behavior

### ISSUE THREAD

**Issue by ncc0624** [itavero/homebridge-z2m#395]
Please use the template and fill in all the data requested below!

**Describe the bug**
Noticed something odd the other day... the Home app requires two presses to match what the light is actually doing if the light is turned on from other than the Home.app. For example... Node-RED automation turns on the light, the light will change from off to on in the Home app. Pushing the light turns off the actual light, however then the home app will show it's off, then go back to on - but the light is still off. Pushing it again shows it off in Home, doesn't change the light. Now they match status.

**Related devices**
Are you experiencing this behavior with a particular device?
Please list which device(s) you experience this with.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Change '...' via the Home app.
2. Log shows MQTT message '...' being published to topic '...'
3. The device does the following: '...'

**Expected behavior**
Matching indications without double clicking.

**MQTT messages**
If possible (and applicable), please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)
* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
info  2022-02-25 10:28:11: MQTT publish: topic 'zigbee2mqtt/Floor Lamp', payload '{"brightness":254,"color":{"hue":42,"saturation":38,"x":0.3636,"y":0.3656},"color_mode":"color_temp","color_temp":226,"last_seen":"2022-02-25T10:27:38-07:00","linkquality":138,"state":"ON","update":{"state":"idle"},"update_available":false}'
info  2022-02-25 10:28:19: MQTT publish: topic 'zigbee2mqtt/Floor Lamp', payload '{"brightness":254,"color":{"hue":42,"saturation":38,"x":0.3636,"y":0.3656},"color_mode":"color_temp","color_temp":226,"last_seen":"2022-02-25T10:28:19-07:00","linkquality":138,"state":"ON","update":{"state":"idle"},"update_available":false}'
info  2022-02-25 10:28:19: MQTT publish: topic 'zigbee2mqtt/Floor Lamp', payload '{"brightness":254,"color":{"hue":42,"saturation":38,"x":0.3636,"y":0.3656},"color_mode":"color_temp","color_temp":226,"last_seen":"2022-02-25T10:28:19-07:00","linkquality":138,"state":"OFF","update":{"state":"idle"},"update_available":false}'
info  2022-02-25 10:28:25: MQTT publish: topic 'zigbee2mqtt/Floor Lamp', payload '{"brightness":254,"color":{"hue":42,"saturation":38,"x":0.3636,"y":0.3656},"color_mode":"color_temp","color_temp":226,"last_seen":"2022-02-25T10:28:25-07:00","linkquality":138,"state":"OFF","update":{"state":"idle"},"update_available":false}'
info  2022-02-25 10:28:25: MQTT publish: topic 'zigbee2mqtt/Floor Lamp', payload '{"brightness":254,"color":{"hue":42,"saturation":38,"x":0.3636,"y":0.3656},"color_mode":"color_temp","color_temp":226,"last_seen":"2022-02-25T10:28:25-07:00","linkquality":138,"state":"OFF","update":{"state":"idle"},"update_available":false}'
info  2022-02-25 10:28:30: MQTT publish: topic 'zigbee2mqtt/Floor Lamp', payload '{"brightness":254,"color":{"hue":42,"saturation":38,"x":0.3636,"y":0.3656},"color_mode":"color_temp","color_temp":226,"last_seen":"2022-02-25T10:28:30-07:00","linkquality":138,"state":"OFF","update":{"state":"idle"},"update_available":false}'
info  2022-02-25 10:28:30: MQTT publish: topic 'zigbee2mqtt/Floor Lamp', payload '{"brightness":254,"color":{"hue":42,"saturation":38,"x":0.3636,"y":0.3656},"color_mode":"color_temp","color_temp":226,"last_seen":"2022-02-25T10:28:30-07:00","linkquality":138,"state":"ON","update":{"state":"idle"},"update_available":false}'
info  2022-02-25 10:28:35: MQTT publish: topic 'zigbee2mqtt/Floor Lamp', payload '{"brightness":254,"color":{"hue":42,"saturation":38,"x":0.3636,"y":0.3656},"color_mode":"color_temp","color_temp":226,"last_seen":"2022-02-25T10:28:35-07:00","linkquality":134,"state":"ON","update":{"state":"idle"},"update_available":false}'
info  2022-02-25 10:28:35: MQTT publish: topic 'zigbee2mqtt/Floor Lamp', payload '{"brightness":254,"color":{"hue":42,"saturation":38,"x":0.3636,"y":0.3656},"color_mode":"color_temp","color_temp":226,"last_seen":"2022-02-25T10:28:35-07:00","linkquality":134,"state":"ON","update":{"state":"idle"},"update_available":false}'

* Messages published by this plugin that might be related to your issue (can also be seen in the homebridge logs)
[2/25/2022, 10:28:19 AM] [homebridge-z2m] Publish to 'zigbee2mqtt/0x00178801048b6ef3/set': '{"state":"OFF"}'
[2/25/2022, 10:28:25 AM] [homebridge-z2m] Publish to 'zigbee2mqtt/0x00178801048b6ef3/set': '{"state":"OFF"}'
[2/25/2022, 10:28:30 AM] [homebridge-z2m] Publish to 'zigbee2mqtt/0x00178801048b6ef3/set': '{"state":"ON"}'
[2/25/2022, 10:28:35 AM] [homebridge-z2m] Publish to 'zigbee2mqtt/0x00178801048b6ef3/set': '{"state":"ON"}'

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin 1.7.0
 - Homebridge 1.4.0
 - Zigbee2MQTT 1.23.0

**Comment by ncc0624** [comment]
Uploading FullSizeRender.MOV…

**Comment by ncc0624** [comment]
Well uploading the screen recording didn't seem to work...

Ah it seems like it could be! Apologies, I searched for "light" when attempting to see if this was already reported.

**Comment by T-IOOO** [comment]
I have also had this weird issue. At first I thought that a group of 6 bulbs in my setup was the cause. Somehow it felt like IKEA LED1923R5 was more affected than my other bulbs. I downgraded Homebridge to v1.3.9 and it seems to work better.

Homebridge: v1.3.9
zigbee2mqtt: 1.24.0-dev
Homebridge-z2m: v1.7.0
