### ISSUE TITLE
[Device] Support for climate devices (thermostats / radiator valves)

### ISSUE THREAD

**Issue by itavero** [itavero/homebridge-z2m#40]
Given that several people are requesting support for `climate` devices, I decided to make one central issue to discuss the implementation and post updates.

Related issues on GitHub:
* #32 Thermostat like the Eurotronics ones
* #37 Immax 07703L Radiator valve
* #39 Tuya Thermostat valve

It seems that these devices are best mapped as a [Thermostat service](https://developers.homebridge.io/#/service/Thermostat). In #32, @sjorge shared the mapping he uses in node-red.

Implementing a Service Handler for `climate` devices will probably bring support for the following devices (and their white label variants) to this plugin:
* [TuYa TS0601_thermostat](https://arno.dev/homebridge-z2m/devices/tuya/ts0601_thermostat.html): Radiator valve with thermostat
* [ETOP HT-08](https://arno.dev/homebridge-z2m/devices/etop/ht-08.html): Wall-mount thermostat
* [ETOP HT-10](https://arno.dev/homebridge-z2m/devices/etop/ht-10.html): Radiator valve
* [TuYa U86KWF-ZPSJ](https://arno.dev/homebridge-z2m/devices/tuya/u86kwf-zpsj.html): Environment controller
* [TuYa D3-DPWK-TY](https://arno.dev/homebridge-z2m/devices/tuya/d3-dpwk-ty.html): HVAC controller
* [TuYa HY08WE](https://arno.dev/homebridge-z2m/devices/tuya/hy08we.html): Wall-mount thermostat
* [eCozy 1TST-EU](https://arno.dev/homebridge-z2m/devices/ecozy/1tst-eu.html): Smart heating thermostat
* [Hive UK7004240](https://arno.dev/homebridge-z2m/devices/hive/uk7004240.html): Radiator valve
* [Hive SLR1b](https://arno.dev/homebridge-z2m/devices/hive/slr1b.html): Heating thermostat
* [Hive SLR2](https://arno.dev/homebridge-z2m/devices/hive/slr2.html): Dual channel heating and hot water thermostat
* [Leviton RC-2000WH](https://arno.dev/homebridge-z2m/devices/leviton/rc-2000wh.html): Omnistat2 wireless thermostat
* [Bitron AV2010/32](https://arno.dev/homebridge-z2m/devices/bitron/av2010_32.html): Wireless wall thermostat with relay
* [Centralite 3157100](https://arno.dev/homebridge-z2m/devices/centralite/3157100.html): 3-Series pearl touch thermostat,
* [Danfoss 014G2461](https://arno.dev/homebridge-z2m/devices/danfoss/014g2461.html): Ally thermostat
* [Eurotronic SPZB0001](https://arno.dev/homebridge-z2m/devices/eurotronic/spzb0001.html): Spirit Zigbee wireless heater thermostat
* [Immax 07703L](https://arno.dev/homebridge-z2m/devices/immax/07703l.html): Radiator valve
* [Stelpro ST218](https://arno.dev/homebridge-z2m/devices/stelpro/st218.html): Ki convector, line-voltage thermostat
* [Stelpro STZB402](https://arno.dev/homebridge-z2m/devices/stelpro/stzb402.html): Ki, line-voltage thermostat
* [Stelpro SMT402](https://arno.dev/homebridge-z2m/devices/stelpro/smt402.html): Maestro, line-voltage thermostat
* [Stelpro SMT402AD](https://arno.dev/homebridge-z2m/devices/stelpro/smt402ad.html): Maestro, line-voltage thermostat
* [Sinope TH1123ZB](https://arno.dev/homebridge-z2m/devices/sinope/th1123zb.html): Zigbee line volt thermostat
* [Sinope TH1124ZB](https://arno.dev/homebridge-z2m/devices/sinope/th1124zb.html): Zigbee line volt thermostat
* [Sinope TH1300ZB](https://arno.dev/homebridge-z2m/devices/sinope/th1300zb.html): Zigbee smart floor heating thermostat
* [Sinope TH1400ZB](https://arno.dev/homebridge-z2m/devices/sinope/th1400zb.html): Zigbee low volt thermostat
* [Sinope TH1500ZB](https://arno.dev/homebridge-z2m/devices/sinope/th1500zb.html): Zigbee dual pole line volt thermostat
* [Zen Zen-01-W](https://arno.dev/homebridge-z2m/devices/zen/zen-01-w.html): Thermostat
* [Moes BHT-002-GCLZB](https://arno.dev/homebridge-z2m/devices/moes/bht-002-gclzb.html): Moes BHT series Thermostat
* [Saswell SEA801-Zigbee/SEA802-Zigbee](https://arno.dev/homebridge-z2m/devices/saswell/sea801-zigbee_sea802-zigbee.html): Thermostatic radiator valve
* [Schneider Electric WV704R0A0902](https://arno.dev/homebridge-z2m/devices/schneider_electric/wv704r0a0902.html): Wiser radiator thermostat
* [Siterwell GS361A-H04](https://arno.dev/homebridge-z2m/devices/siterwell/gs361a-h04.html): Radiator valve with thermostat
* [Viessmann ZK03840](https://arno.dev/homebridge-z2m/devices/viessmann/zk03840.html): ViCare radiator thermostat valve

**Comment by itavero** [comment]
Looks like I'll have at least a couple of hours tomorrow to start setting up the Service Handler for these kind of devices.

In the meantime I've also added all the devices currently in zigbee2mqtt (except for the white label ones) that expose a `climate` type. Hopefully other people will be able to find this issue, instead of opening up a new one. 😄

**Comment by itavero** [comment]
Started on the implementation today. Not a lot of progress yet.

Most devices only expose one property for the setpoint, except for the following two devices which expose both a `occupied_heating_setpoint` and a `occupied_cooling_setpoint`:
* Leviton RC-2000WH
* Centralite 3157100

HomeKit doesn't specify separate heating and cooling setpoints as far as I'm aware.
For now I will ignore these exceptions and focus on an implementation that should work for the majority of the devices (with only a single setpoint).

**Comment by itavero** [comment]
So far I've setup the ServiceHandler class today. I still need to add the code to actually map/handle the characteristics (right now I've only added a monitor to publish the `local_temperature` to HomeKit).
Hopefully I'll be able to do the rest of the implementation this week. Not sure if I'll have enough time to also add the automated tests this week (which I would like to do before releasing it, but since where still in the "beta" phase, I might release it before these tests have been written).

**Comment by itavero** [comment]
Not sure what the [Temperature Display Units](https://developers.homebridge.io/#/characteristic/TemperatureDisplayUnits) characteristic is for. I think it is intended to change the unit on the device itself.
As I don't see a device that supports changing this via Zigbee2MQTT (and if it does it's probably a one time thing), I'm fixing this characteristic to degrees Celcius for now.

**Comment by itavero** [comment]
I think I finished the implementation, but I haven't tested it at all (except for `npm run build`, `npm run test` and regenerating the device documentation 😅).
If you want to have a peek at the implementation, please look at #43 (and ignore all the changes in the `docs/devices/` folder as these are all generated files).
I'll probably have some time to write (some) automated tests tomorrow evening.

So, if you are waiting for this, you might be in luck and be able to control your heating system via HomeKit before this heating season is over. 😉

**Comment by itavero** [comment]
On a related note: I plan to put the new major version on the `latest` channel in February. Before I do that, I'll release this new feature in another beta release to gather some feedback from people that actually have this `climate` devices.

**Comment by itavero** [comment]
Added an automated test and updated the documentation as well (see PR #43 ).
Also thanks to @jukben for already given my code from the PR a test run.

It's late in the evening now, so I'm not going to make a release right now. I do plan to make a new beta release with this new feature this weekend. I'll post another update once it is available via `npm i homebridge-z2m@next` 😉

**Comment by itavero** [comment]
Version 1.1.0-beta.2 has just been released and can be installed with `npm i homebridge-z2m@next`.

@jhm47 / @Kepro / @mojijafari If you have some time to give it a try, that would be awesome. I'm closing this issue as, the implementation is available via the `next` channel now. Feedback can still be added to this issue (or you can open up a new one).

If someone would still like to see support for the **Leviton RC-2000WH** or **Centralite 3157100**, please open up a new issue and propose how to deal with the dual setpoint property "problem".

**Comment by Kepro** [comment]
@itavero I'm using homebridge-z2m `v1.1.0-beta.3` and nothing :( 

![image](https://user-images.githubusercontent.com/1714370/106381952-81589600-63bc-11eb-87e1-95a7b28fe02d.png)
![image](https://user-images.githubusercontent.com/1714370/106381964-933a3900-63bc-11eb-8c78-85f85b59ae57.png)

**Comment by itavero** [comment]
@Kepro Can you start Homebridge with debugging logging enabled and post the logs from the startup? It should mention which services are being created.

**Comment by jhm47** [comment]
Thx Arno! This is awesome!!

Just did a very quick check (updated to beta3) – seems to work … I could change the temperature on my Eurotronics TRV through my iPhone.

(I will need to do some more testing …)

Cheers

**Comment by Kepro** [comment]
hmm, checking zigbee2MQTT version and it's `1.17.0`
```
[31/01/2021, 11:32:49] Loaded plugin: homebridge-z2m@1.1.0-beta.3
[31/01/2021, 11:32:49] Registering platform 'homebridge-z2m.zigbee2mqtt'
[31/01/2021, 11:32:49] ---

[31/01/2021, 11:32:50] [zigbee2mqtt] Restoring old (pre v1.0.0) accessory Thermostat Living Room (0x5c0272fffedaad9e). This accessory will not work until updated device information is received from Zigbee2MQTT v1.17.0 or newer.
[31/01/2021, 11:32:50] [zigbee2mqtt] Restoring old (pre v1.0.0) accessory Thermostat Bed Room (0x847127fffe963e13). This accessory will not work until updated device information is received from Zigbee2MQTT v1.17.0 or newer.
[31/01/2021, 11:32:50] [zigbee2mqtt] Restoring old (pre v1.0.0) accessory Thermostat Kids Room (0x5c0272fffedabf6d). This accessory will not work until updated device information is received from Zigbee2MQTT v1.17.0 or newer.
```

**Comment by montanaishome** [comment]
Have a zen zen-01-w thermostat connected to z2m.  Showing as unsupported in HomeKit.  Was working in the past, but I recently re-installed z2m after a SD card crash.  Any ideas?

**Comment by itavero** [comment]
>  Have a zen zen-01-w thermostat connected to z2m.  Showing as unsupported in HomeKit.  Was working in the past, but I recently re-installed z2m after a SD card crash.  Any ideas?

Perhaps the exposes information provided by Zigbee2MQTT has changed. Our website also mentions it is unsupported now, was that different in the past?
https://z2m.dev/devices/zen/zen-01-w.html

**Comment by montanaishome** [comment]
Yes, it was supported when I bought it.

Aaron Weissman
***@***.***

**Comment by itavero** [comment]
I would suggest to look into the changes made in recent versions of zigbee-herdsman-converters, and/or downgrading Zigbee2MQTT itself to find a working version.
After that you can open up a PR/issue on zigbee-herdsman-converters
