### ISSUE TITLE
[Feature] Include a key which is already excluded by default for a certain device

### ISSUE THREAD

**Issue by Z18Aplha** [itavero/homebridge-z2m#406]
**Problem description**
I have a good reason to exclude a certain key by default. But a new device provides this key and i for this single device, i want to not exclude the key. It would be a lot of work to exclude the key for each of the other devices and the  high value of the z2m plugin (auto-add devices to HomeKit with nearly no effort) would decrease.

**Suggested solution**
An "include_keys" property in the json config which overrides the default setting for the certain device

**Describe alternatives you've considered**
I see no real alternatives, which preserves the functionality with lowest effort.

**Additional context**
In my case, i have a lot Aqara door/window and Aqara PIR sensors. Both provides temperature readings which are unusable for me. So i excluded the "temperature" key by default. My Thermostates aren't affected by excluding the temperature because the data point is called "local_temperature" - fine. Recently, i added an Aqara Room sensor to my network to monitor my room climate. 
For this device i want to see the temperature readings in HomeKit. Currently, there is a little bug in the temperature reading mentioned in #405 but not related to this request. 

**Are you willing to contribute to this feature?**
I can discuss about a best solution and test new releases.

**Comment by itavero** [comment]
Sounds like a good suggestion that can be implemented without much hassle.
My schedule this week/weekend is pretty full, but I'll try to find a moment to add this in the near future.

**Comment by itavero** [comment]
I've just pushed an implementation for this, but there's a couple of other small things I want to try to incorporate in the next release as well.
I'm hoping to have time for this in the coming days, but if that's not the case, I'm still planning to release next week.

I'll keep you posted.

**Comment by itavero** [comment]
I've just released v1.8.0

**Comment by Z18Aplha** [comment]
Thank you @itavero for the release!
