### ISSUE TITLE
[Feature] Option to expose Stateless Programmable Switch as doorbell ?

### ISSUE THREAD

**Issue by bakman2** [itavero/homebridge-z2m#408]
**Feature description**
I use a [Aqara wireless switch](https://www.zigbee2mqtt.io/devices/WXKG11LM.html) as a doorbell.
Currently this is (correctly) exposed as a switch. It would be nice to have a configuration option to override it and expose it as a doorbell.

**Suggested solution**
Homebridge configuration option to override the stateless programmable switch as doorbell.

**Describe alternatives you've considered**
Currently using [homebridge-mqtt](https://github.com/cflurin/homebridge-mqtt#readme) in combination with node-red which allows to create custom homekit devices and control them via mqtt. I created a doorbell there, which works, but would be easier/nicer to just have a "doorbell" flag in z2m. 

**Are you willing to contribute to this feature?**
Maybe, but i am not familiar with the used language.

**Comment by itavero** [comment]
Since this will pretty much always require custom configuration (which is what I'm trying to avoid with this plugin), I think it makes more sense to exclude it in this plugin and add it to your Homebridge setup via [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Accessories.md#doorbell).
Would that solve your use case?

**Comment by bakman2** [comment]
> Since this will pretty much always require custom configuration (which is what I'm trying to avoid with this plugin), I think it makes more sense to exclude it in this plugin and add it to your Homebridge setup via [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Accessories.md#doorbell).
> Would that solve your use case?

mqttthing is even less elegant than my current node-red/homebridge-mqtt solution. But I understand the preference to keep the plugin simple. No worries thanks.
