### ISSUE TITLE
[Bug]  Error message with TuYa TS011F_plug_1

### ISSUE THREAD

**Issue by JayJay-Master** [itavero/homebridge-z2m#409]
Please use the template and fill in all the data requested below!

**Describe the bug**
With restart of Hoimebridge log shows following error message:
[3/31/2022, 10:29:04 PM] [zigbee2mqtt] Failed to setup switch for accessory Steckdose 5 from expose "{"features":[{"access":3,"description":"Enables/disables physical input on the device","name":"state","property":"child_lock","type":"binary","value_off":"UNLOCK","value_on":"LOCK"}],"type":"lock"}": Error: Required "lock_state" property not found for Lock.
On/Off funktion works as expected.

**Related devices**
Are you experiencing this behavior with a particular device?
Please list which device(s) you experience this with.
TuYa TS011F_plug_1            BlitzWolf BW-SHP13

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Change '...' via the Home app.
2. Log shows MQTT message '...' being published to topic '...'
3. The device does the following: '...'
MQTT publish: topic 'zigbee2mqtt/Steckdose 5', payload '{"child_lock":"UNLOCK","current":0.18,"device":{"applicationVersion":74,"dateCode":"","friendlyName":"Steckdose 5","hardwareVersion":1,"ieeeAddr":"0xa4c1389e2b8a719c","manufacturerID":4417,"manufacturerName":"_TZ3000_amdymr7l","model":"TS011F_plug_1","networkAddress":19218,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"energy":0.11,"indicator_mode":"off/on","linkquality":255,"power":24,"power_outage_memory":"restore","state":"ON","voltage":227}'

**Expected behavior**
A clear and concise description of what you expected to happen, compared to what actually happened.
Works as expected with the reduced functionality (see allso device future request #404)

**MQTT messages**
If possible (and applicable), please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)
* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
* Messages published by this plugin that might be related to your issue (can also be seen in the homebridge logs)
 MQTT publish: topic 'zigbee2mqtt/Steckdose 5', payload '{"child_lock":"UNLOCK","current":0.18,"device":{"applicationVersion":74,"dateCode":"","friendlyName":"Steckdose 5","hardwareVersion":1,"ieeeAddr":"0xa4c1389e2b8a719c","manufacturerID":4417,"manufacturerName":"_TZ3000_amdymr7l","model":"TS011F_plug_1","networkAddress":19218,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"energy":0.11,"indicator_mode":"off/on","linkquality":255,"power":24,"power_outage_memory":"restore","state":"ON","voltage":227}'

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin
 - Homebridge
 - Zigbee2MQTT (can be found in MQTT topic `zigbee2mqtt/bridge/info`)
 - Homebridge Config UI X (if applicable)
1.  Homebridge Zigbee2MQTT - @krystofcelba/homebridge-z2m v1.6.0 
2.  Homebridge v1.4.0 (docker version)
3.  Zigbee2MQTT Version:  1.24.0-dev commit: [1c1ca6f]
4.   Homebridge UI - homebridge-config-ui-x v4.42.0

**Comment by itavero** [comment]
You are using a fork of this plugin which I'm not familiar with.

Also please provide the MQTT message with the device model, as requested in the template.

**Comment by itavero** [comment]
@krystofcelba I tried to send an email to you about the forked version you have published to NPM, but got a response from your iCloud that you are over quota. Is there any other way I can reach you?

**Comment by JayJay-Master** [comment]
Hello,
I use Homebridge in a Docker container (oznu/homebridge:latest - actual v1.4.0) on a Synology NAS. 
Z2m plugin is the normal plugin  Homebridge Zigbee2MQTT homebridge-z2m v1.7.0 (2022-02-20). Sorry, in my first message I mentioned a wrong plugin.

MQTT message with device model:
{"child_lock":"UNLOCK","current":0.15,"device":{"applicationVersion":74,"dateCode":"","friendlyName":"Steckdose 5","hardwareVersion":1,"ieeeAddr":"0xa4c1389e2b8a719c","manufacturerID":4417,"manufacturerName":"_TZ3000_amdymr7l","model":"TS011F_plug_1","networkAddress":19218,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"energy":0.36,"indicator_mode":"off/on","linkquality":255,"power":16,"power_outage_memory":"restore","state":"ON","voltage":231}

See also Zigbee2MQTT device description:
https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1

Only forclarification, the following error message is only displayed on startup or restart of homebridge. The switch function of the plug works as expected.  Nevertheless it would be nice, if the additional funtionality of power messurement could be also displayed, maybe not in Apples Home app, but in Eve app (see allso device future request https://github.com/itavero/homebridge-z2m/issues/404).

**Comment by itavero** [comment]
From MQTT, please provide the device entry from topic `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`).

**Comment by JayJay-Master** [comment]
{
		"date_code": "",
		"definition": {
			"description": "Smart plug (with power monitoring)",
			"exposes": [
				{
					"features": [
						{
							"access": 7,
							"description": "On/off state of the switch",
							"name": "state",
							"property": "state",
							"type": "binary",
							"value_off": "OFF",
							"value_on": "ON",
							"value_toggle": "TOGGLE"
						}
					],
					"type": "switch"
				},
				{
					"access": 1,
					"description": "Instantaneous measured power",
					"name": "power",
					"property": "power",
					"type": "numeric",
					"unit": "W"
				},
				{
					"access": 1,
					"description": "Instantaneous measured electrical current",
					"name": "current",
					"property": "current",
					"type": "numeric",
					"unit": "A"
				},
				{
					"access": 1,
					"description": "Measured electrical potential value",
					"name": "voltage",
					"property": "voltage",
					"type": "numeric",
					"unit": "V"
				},
				{
					"access": 1,
					"description": "Sum of consumed energy",
					"name": "energy",
					"property": "energy",
					"type": "numeric",
					"unit": "kWh"
				},
				{
					"access": 3,
					"description": "Recover state after power outage",
					"name": "power_outage_memory",
					"property": "power_outage_memory",
					"type": "enum",
					"values": [
						"on",
						"off",
						"restore"
					]
				},
				{
					"access": 7,
					"description": "Plug LED indicator mode",
					"name": "indicator_mode",
					"property": "indicator_mode",
					"type": "enum",
					"values": [
						"off",
						"off/on",
						"on/off",
						"on"
					]
				},
				{
					"features": [
						{
							"access": 3,
							"description": "Enables/disables physical input on the device",
							"name": "state",
							"property": "child_lock",
							"type": "binary",
							"value_off": "UNLOCK",
							"value_on": "LOCK"
						}
					],
					"type": "lock"
				},
				{
					"access": 1,
					"description": "Link quality (signal strength)",
					"name": "linkquality",
					"property": "linkquality",
					"type": "numeric",
					"unit": "lqi",
					"value_max": 255,
					"value_min": 0
				}
			],
			"model": "TS011F_plug_1",
			"options": [
				{
					"access": 2,
					"description": "Calibrates the power value (percentual offset), takes into effect on next report of device.",
					"name": "power_calibration",
					"property": "power_calibration",
					"type": "numeric"
				},
				{
					"access": 2,
					"description": "Calibrates the current value (percentual offset), takes into effect on next report of device.",
					"name": "current_calibration",
					"property": "current_calibration",
					"type": "numeric"
				},
				{
					"access": 2,
					"description": "Calibrates the voltage value (percentual offset), takes into effect on next report of device.",
					"name": "voltage_calibration",
					"property": "voltage_calibration",
					"type": "numeric"
				}
			],
			"supports_ota": true,
			"vendor": "TuYa"
		},
		"endpoints": {
			"1": {
				"bindings": [
					{
						"cluster": "genOnOff",
						"target": {
							"endpoint": 1,
							"ieee_address": "0x00212effff0781ef",
							"type": "endpoint"
						}
					},
					{
						"cluster": "haElectricalMeasurement",
						"target": {
							"endpoint": 1,
							"ieee_address": "0x00212effff0781ef",
							"type": "endpoint"
						}
					},
					{
						"cluster": "seMetering",
						"target": {
							"endpoint": 1,
							"ieee_address": "0x00212effff0781ef",
							"type": "endpoint"
						}
					}
				],
				"clusters": {
					"input": [
						"genIdentify",
						"genGroups",
						"genScenes",
						"genOnOff",
						"seMetering",
						"haElectricalMeasurement",
						"manuSpecificTuya_3",
						"57344",
						"genBasic"
					],
					"output": [
						"genOta",
						"genTime"
					]
				},
				"configured_reportings": [
					{
						"attribute": "rmsCurrent",
						"cluster": "haElectricalMeasurement",
						"maximum_report_interval": 3600,
						"minimum_report_interval": 5,
						"reportable_change": 50
					},
					{
						"attribute": "currentSummDelivered",
						"cluster": "seMetering",
						"maximum_report_interval": 3600,
						"minimum_report_interval": 5,
						"reportable_change": [
							1,
							1
						]
					},
					{
						"attribute": "activePower",
						"cluster": "haElectricalMeasurement",
						"maximum_report_interval": "120",
						"minimum_report_interval": 5,
						"reportable_change": 10
					},
					{
						"attribute": "rmsVoltage",
						"cluster": "haElectricalMeasurement",
						"maximum_report_interval": "120",
						"minimum_report_interval": 5,
						"reportable_change": 5
					}
				],
				"scenes": []
			},
			"242": {
				"bindings": [],
				"clusters": {
					"input": [],
					"output": [
						"greenPower"
					]
				},
				"configured_reportings": [],
				"scenes": []
			}
		},
		"friendly_name": "Steckdose 5",
		"ieee_address": "0xa4c1389e2b8a719c",
		"interview_completed": true,
		"interviewing": false,
		"manufacturer": "_TZ3000_amdymr7l",
		"model_id": "TS011F",
		"network_address": 19218,
		"power_source": "Mains (single phase)",
		"supported": true,
		"type": "Router"
	}

**Comment by itavero** [comment]
It exposes a `lock`:
```json
			{
				"features": [
					{
						"access": 3,
						"description": "Enables/disables physical input on the device",
						"name": "state",
						"property": "child_lock",
						"type": "binary",
						"value_off": "UNLOCK",
						"value_on": "LOCK"
					}
				],
				"type": "lock"
			}
```

But this `lock` doesn't have a `lock_state`. Nothing to worry about if you don't care about operating the "child lock" feature. Otherwise I'd have to see how I can control it if there is no `lock_state` (although I don't think those should actually be exposed as a "lock").

**Comment by JayJay-Master** [comment]
I have no problem with the error message, the basic functionality works on and off.
Nevertheless, the implementation of the consumption values as additional features would be very welcome (see allso device future request [#404](https://github.com/itavero/homebridge-z2m/issues/404)).
