### ISSUE TITLE
[Bug] TuYa Model-TS011F_plug_1 appears as a switch in Homebridge and not as a smart plug

### ISSUE THREAD

**Issue by Jeepmg** [itavero/homebridge-z2m#422]
Please use the template and fill in all the data requested below!

**Describe the bug**
appears as a switch in Homebridge and not as a smart plug

Switch |  
-- | --
On | 0
Manufacturer | TuYa
Model | TS011F_plug_1
Name | Chromecast
Serial Number | 0xa4c1389a3996b4e3
Firmware Revision | ?
Homebridge Instance IP | 127.0.0.1
Homebridge Instance Port | 51255
Homebridge Instance Username | 0E:5E:DC:8D:93:C8
aid | 2
iid | 9

**Related devices**
Are you experiencing this behavior with a particular device?
Please list which device(s) you experience this with.

TuYa Model-TS011F_plug_1 
TuYa Model-TS011F_plug_3 ?

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Change '...' via the Home app.
2. Log shows MQTT message '...' being published to topic '...'
3. The device does the following: '...'

**Expected behavior**
A clear and concise description of what you expected to happen, compared to what actually happened.

I expect I can choose PLUG in Homekit for this item.

**MQTT messages**
If possible (and applicable), please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)
* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
* Messages published by this plugin that might be related to your issue (can also be seen in the homebridge logs)

{
  "child_lock": "UNLOCK",
  "current": 0,
  "energy": 0.12,
  "indicator_mode": "off/on",
  "linkquality": 163,
  "linkquality": 160,
  "power": 0,
  "power_outage_memory": "restore",
  "state": "OFF",
  "update": {
    "state": "idle"
  },
  "voltage": 240

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin : 1.7.0
 - Homebridge : 1.4.0
 - Zigbee2MQTT (can be found in MQTT topic `zigbee2mqtt/bridge/info`) : 1.25.0
 - Homebridge Config UI X (if applicable) : 4.43

**Comment by itavero** [comment]
Not a bug, as it is working as intended as far as I can tell from the limited information given.

**Comment by Jeepmg** [comment]
![IMG_0313](https://user-images.githubusercontent.com/103240876/164551250-e1441c1c-3963-4faa-a636-cdbbffa506ae.PNG)

Everything actually works.

Sorry, the example is in French. It shows that the plug can be considered in Homekit as a switch, light or fan but in no way as a socket even if it is.

Considering a plug as a switch makes it difficult to manage the device with Siri.

**Comment by itavero** [comment]
I think there has been a feature request for changing device types via the plugin configuration. Currently on my phone, but I'll try to look it up later today.

I'm not sure what the issue with Siri would be. I have smart sockets as well and I can just tell Siri to _Turn On "name of device"_ (or off, of course).
I'm even using Siri in Dutch which still has quite some "issues" (some strange wording, reliability and such), but this has never failed me.

**Comment by Jeepmg** [comment]
> I think there has been a feature request for changing device types via the plugin configuration. Currently on my phone, but I'll try to look it up later today.

Thank you for this.

I forgot to tell you that the plug is:

Zigbee model
     TS011F
Zigbee builder
     _TZ3000_w0qqde0g

the plug changed from TS011F_plug_3 to TS011F_plug_1 in Z2M, in recent days. It seems that a firmware update has occurred even if no firmware version is indicated in Z2M.

**Comment by itavero** [comment]
> I'll try to look it up later today.

See #45 and #279

**Comment by Jeepmg** [comment]
I went to buy another zigbee socket this morning. It is also recognized as a switch instead of a socket. It doesn't seem to be a problem for you, but I promise you it is for me. Especially with Siri seeing these sockets as lights; maybe because of the French. By putting this plug on, I light up the whole apartment!!!

Thank you for spending some time on this anomaly.

**Comment by itavero** [comment]
@Jeepmg, please refer to the issues I've referenced before. Perhaps such a feature would help you and then it makes more sense to add your use case there.

You are aware that you can configure how the Home.app "views" a "switch"? (E.g. Outlet, Light or Fan)

**Comment by Jeepmg** [comment]
Of course I know, then that's the reason for the problem. For a socket you choose in Homekit, light or fan or socket. For a switch you choose, light or switch or fan. Under no circumstances can you choose a socket for a switch in Home.app.
