### ISSUE TITLE
[Device] TuYa PJ-ZGD01 - Support for garage door openers

### ISSUE THREAD

**Issue by jurefl** [itavero/homebridge-z2m#444]
**Device description**
Garage door opener - TuYa PJ-ZGD01

**Supported in Zigbee2MQTT?**
Support is already present in Zigbee2MQTT since v1.23.0

**Device model / Exposes information**
Model: PJ-ZGD01
Exposes:
* Trigger (binary)
* Garage_door_contact (binary)
* Linkquality (numeric)

cc https://www.zigbee2mqtt.io/devices/PJ-ZGD01.html

```json
[
  {
    "type": "binary",
    "name": "trigger",
    "property": "trigger",
    "access": 3,
    "value_on": true,
    "value_off": false,
    "description": "Trigger the door movement"
  },
  {
    "type": "binary",
    "name": "garage_door_contact",
    "property": "garage_door_contact",
    "access": 1,
    "value_on": true,
    "value_off": false
  },
  {
    "type": "numeric",
    "name": "linkquality",
    "property": "linkquality",
    "access": 1,
    "unit": "lqi",
    "description": "Link quality (signal strength)",
    "value_min": 0,
    "value_max": 255
  }
]
```

**Missing features/functionality**
* Triggering open/close door. 
* Status whether the door is closed or open.

**Suggested services and characteristics**
Unsure.

**Comment by itavero** [comment]
Probably should be implemented as a [Garage Door Opener](https://developers.homebridge.io/#/service/GarageDoorOpener).

The difficult thing is that you can only send a trigger and you have to guess the direction the door is moving in.
I'm not sure how you can make this work reliably.
You can only know if it's fully closed. If it's not then you do not know if it's moving or not, and if it's moving you can't know the direction for sure.

**Comment by jurefl** [comment]
Yup - reading through the link, implemented as "Garage Door Opener" would be ideal.

True. Maybe the logic something like below can do it:
* When `garage_door_contact` is reporting true, then doors are closed (this is the only reliable value)
* If doors are closed when a trigger is pressed, then assume doors open
* If doors are opened when a trigger is pressed, assume doors closed (with a timeout i.e. if `garage_door_contact` don't report true in e.g. 45sec after trigger then report either open or `ObstructionDetected`)

I would be happy to give it a go, if you are able to give me some pointers? This would be my first contribution here.

**Comment by andre-sam** [comment]
I have the same sensor and support would be awesome!

Based on my tests the sensor works like an inching relay and exposes trigger, garage_door_contact, linkquality.

`garage_door_contact` is a contact sensor which will report `true` or `false` where true=door closed and false=door open.

`trigger` will trigger a door movement and the value can also be `true` of `false`. However, here is where it gets interesting. If the  `garage_door_contact` is reporting `true` door closed then the only way to trigger the relay is by setting `trigger` to `true` and when `garage_door_contact` is reporting `false` door open the only way to trigger the relay is by setting `trigger` to `false`.

If there is an obstruction my garage door will revert to the previous position. For example, if it starts opening if encounters an obstruction it will automatically move back into a close position and vice-versa.

**Comment by lenny005** [comment]
> Probably should be implemented as a [Garage Door Opener](https://developers.homebridge.io/#/service/GarageDoorOpener).
> 
> The difficult thing is that you can only send a trigger and you have to guess the direction the door is moving in. I'm not sure how you can make this work reliably. You can only know if it's fully closed. If it's not then you do not know if it's moving or not, and if it's moving you can't know the direction for sure.

Hello, could you still implemente it even if you can’t have the full thing working as you wish please ? My door closes automatically with a timer, just need to send an open request. The open/close status is enough for me.

thank you very much.

**Comment by itavero** [comment]
Reopen due to recent requests.

**Comment by Ropuh** [comment]
Hello, please implemente it even partial. 
HA via zigbee2mqtt operates Closed/Opened (via contact sensor) and moving (without direction - close/start based on contact sensor).

**Comment by itavero** [comment]
Currently, between my job, being a father and being a home owner, I simply do not have the time to implement this.
You're more than welcome to provide a PR for this.

**Comment by Ropuh** [comment]
If only I could code...

**Comment by itavero** [comment]
Ordered a PJ-ZGD01 from AliExpress, so I'll also have a device to test with.
Probably will take another month or so to arrive, and of course then I still have to find time to install it.

**Comment by bosu1787** [comment]
i was able to make it work with mqttthing. here is the config:

 {
            "type": "garageDoorOpener",
            "name": "Poarta Auto",
            "topics": {
                "getCurrentDoorState": "zigbee2mqtt/Poarta Auto$.garage_door_contact",
                "getTargetDoorState": "zigbee2mqtt/Poarta Auto$.garage_door_contact",
                "setTargetDoorState": "zigbee2mqtt/Poarta Auto/set/trigger"
            },
            "doorCurrentValues": [
                "false",
                "true",
                "Opening",
                "Closing",
                "Stopped"
            ],
            "doorTargetValues": [
                "false",
                "true"
            ],
            "lockValues": [
                "Unsecured",
                "Secured",
                "Jammed",
                "Unknown"
            ],
            "accessory": "mqttthing"
        }

**Comment by Dansteris** [comment]
@itavero how does it look with support of this garage door opener?

**Comment by itavero** [comment]
> how does it look with support of this garage door opener?

Not sure what you are asking. If you're asking if there's been any progress, there wasn't any from my side.

**Comment by falcomenz** [comment]
> i was able to make it work with mqttthing. here is the config:
> 
> { "type": "garageDoorOpener", "name": "Poarta Auto", "topics": { "getCurrentDoorState": "zigbee2mqtt/Poarta Auto$.garage_door_contact", "getTargetDoorState": "zigbee2mqtt/Poarta Auto$.garage_door_contact", "setTargetDoorState": "zigbee2mqtt/Poarta Auto/set/trigger" }, "doorCurrentValues": [ "false", "true", "Opening", "Closing", "Stopped" ], "doorTargetValues": [ "false", "true" ], "lockValues": [ "Unsecured", "Secured", "Jammed", "Unknown" ], "accessory": "mqttthing" }

Thank you for your mqttthing config, unfortunately the "setTargetDoorState" seems to be the wrong way round. When the garage door is closed (door contact = true), the PJ-ZGD01 needs a "true" value as a trigger to activate the relay and when the door is open (door contact = false) a "false" value. With you config i need to "double tap" the Garage Door in Homekit to open. How do i change the config to get the desired behavior? My workaround currently is with node red, but it would be easier to just have the complete config within mqttthing :) Thank you!

**Comment by YellowNest** [comment]
Just got my PJ-ZGD01 and got disappointed since it’s unsupported 😕

Is it possible to get it to work with homebridge?

**Comment by muller-h** [comment]
he intentado que el PJ-ZGD01  al activar el pulso la puerta se abra y trascurrido el desplazamiento de la puerta (es decir que abra y automáticamente se cierra) y el sensor marque que la puerta se ha cerrado el botón regrese a estar listo para nuevamente abrir la puerta sin tener que pulsarlo dos veces.
he intentado esto con configuration.yaml creando un interruptor virtual

input_boolean:
control_puerta:
name: Control Puerta
icon: mdi:garage

para luego crear un Automatización.

alias: Control Puerta - 
description: Activa el relé de contacto seco solo si la puerta está cerrada
trigger:

platform: state
entity_id: input_boolean.control_puerta
to: "off"
condition:
condition: state
entity_id: binary_sensor.porton_automatico_garage_door_contact
state: "on"
action:
service: switch.turn_on
target:
entity_id: switch.porton_automatico_trigger
delay: "00:00:03"
service: switch.turn_off
target:
entity_id: switch.porton_automatico_trigger
delay: "00:00:01"
service: input_boolean.turn_on
target:
entity_id: input_boolean.control_puerta
mode: single


sin lograrlo si alguien puede ayudar lo agradezco.
