### ISSUE TITLE
[Bug] IKEA TRADFRI bulb switches on with Boot

### ISSUE THREAD

**Issue by Veldkornet** [itavero/homebridge-z2m#446]
Please use the template and fill in all the data requested below!

**Describe the bug**
I have two [IKEA TRADFRI bulb E27 WS opal 1000lm bulbs](https://www.zigbee2mqtt.io/devices/LED1732G11.html#ikea-led1732g11) within 1m of each other. The further away of the two (from the controller) seems to spontaneously switch on every 4 hours, or during boot of homebridge. Ie, if I just restart Homebridge, then the light switches on. I've even created an automation that will turn the light off if it gets turned on (without the door being open) to work around the issue.

Somehow, I am sometime able to fix the issue by deleting things in MQTT, but I'm not really sure what's causing the issue.
See also https://github.com/Koenkk/zigbee2mqtt/issues/10888 

**Related devices**
IKEA TRADFRI bulb E27 WS opal 1000lm bulb

**To Reproduce**
Unclear, a the moment I just restart homebridge and the light turns on
I see the following in the homebridge logs, see below (for both bulbs, although only the one has the problem).

**Expected behavior**
Light should not turn on automatically during boot of homebridge

**MQTT messages**
If possible (and applicable), please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)
I can't see enough lines to get all of the information

* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
```
{"brightness":254,"color_mode":"color_temp","color_temp":370,"linkquality":255,"power_on_behavior":"previous","state":"OFF","update":{"state":"idle"},"update_available":null}
```
* Messages published by this plugin that might be related to your issue (can also be seen in the homebridge logs)
```
[5/22/2022, 11:35:02 AM] [zigbee2mqtt] Restoring accessory: 0xec1bbdfffe254dec (0xec1bbdfffe254dec)
[5/22/2022, 11:35:03 AM] [zigbee2mqtt] Publish to 'zigbee2mqtt/0xec1bbdfffe254dec/get': '{"state":0,"brightness":0,"color_temp":0}'
```

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin: 1.8.0
 - Homebridge: 1.4.1
 - Zigbee2MQTT: 1.25.1
 - Homebridge Config UI X: latest?

**Comment by itavero** [comment]
This plugin does not publish any "set" messages without an event coming from HomeKit. I don't see how this can be caused by this plugin.

Do you have any automations setup in HomeKit that would turn on the light?

**Comment by Veldkornet** [comment]
Nope, I don't use any HomeKit automations at all.

I don't see anything specific in the logs, but I can reproduce it on demand. Just restart HomeBridge, light turns on.

I even deleted the whole zigbee2mqtt node in MQTT and let it rebuild, but it still does it.

**Comment by itavero** [comment]
Do you only restart Homebridge or also Zigbee2MQTT?

If you log the MQTT messages, do you see anything being published to `zigbee2mqtt/FRIENDLY_NAME/set`?

**Comment by Veldkornet** [comment]
No I don't see anything.

The only set is my automation turning it back off, because something turned it on.
Spooky....

`{"state": "OFF", "transition": 1.0}`

**Comment by itavero** [comment]
In the Zigbee2MQTT issue, you mentioned something about retained messages. Are these still there and can you see which client published them?

What message broker are you using for MQTT?

**Comment by duculete** [comment]
how do you restart homebridge? like the service or the entire box /server?
on the same box is the zigbee2mqtt running?

**Comment by itavero** [comment]
Just the service. It depends on how you've installed it. For support with Homebridge, I'd recommend hopping onto their Discord server.

**Comment by Veldkornet** [comment]
Those retained messages aren't' there currently. The only retained message is that of **availability**.
But I deleted everything in mqtt for zigbee2mqtt and it still happens.

For mqtt, I use the standard add-on from the HomeAssistant add-on store.

HomeBridge is in a docker container on a separate host. When restarting, I just push the restart button from the HomeBridge Config UI.

Is it possible that the bulb is just bat poop crazy?

**Comment by itavero** [comment]
> Is it possible that the bulb is just bat poop crazy?

I'd never rule that out as a possibility.
If you check in the Zigbee2MQTT front-end, are there any OTA updates for any of these devices?

**Comment by Veldkornet** [comment]
I recreated my entire z2m stack, but still I had the issue.
So, I replaced the IKEA bulbs with LEDVANCE ones. For now, the issue no longer occurs.

Let's assume it was a faulty IKEA bulb.
