### ISSUE TITLE
[Bug] Battery Service not setting battery level to 100% if battery level is exposed but not part of state on XHS2-SE door sensor devices

### ISSUE THREAD

**Issue by DracoC77** [itavero/homebridge-z2m#457]
**Describe the bug**
All of the XHS2-SE door contact devices report "battery_low = false" in MQTT but show up as 0% battery in the homebridge accessories overview via the homebridge-z2m plugin.

I suspect this may be because the XHS2-SE in MQTT exposes both a battery_low and also a battery level, but for these devices only the battery_low is part of the status message.

Attempted to exclude_key and include_key various combinations of battery and battery_low did not fix this problem.

**Related devices**
XHS2-SE Window/Door Contact sensor

**To Reproduce**
Device that exposes both a battery and battery_low
Status payload with only battery_low = 0 (shows up on homebridge as Status Low battery = 0)

**Expected behavior**
Battery should be showing as 100% per https://z2m.dev/battery.html

**MQTT messages**
info  2022-06-11 19:43:27: MQTT publish: topic 'zigbee2mqtt/Guest Window', payload '{"battery_low":false,"contact":true,"last_seen":1654968316240,"linkquality":255,"tamper":false}'

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin = v1.8.0
 - Homebridge = v1.4.1
 - Zigbee2MQTT = v1.25.2-dev

**Comment by itavero** [comment]
Was a status update published by Zigbee2MQTT whilst Homebridge was active?
If so, have you tried reopening the Home.app after that?

Sometimes an invalid state is reported initially if no status messages was received yet.
Besides that the Home.app also seems to cache some data.

**Comment by DracoC77** [comment]
I believe updates to homebridge have been published (during the debugging in physically opened/closed the device in question and the contact state changed all the way through the home app).

Just tried reopening the Home.app and no luck, I think the issue is probably somewhere in homebridge. When I go to the homebridge UI X acessories tab, it also shows up as 0% battery and status low battery = 0 (see screenshot)
![homebridge snapshot](https://user-images.githubusercontent.com/69522449/173208298-ead29254-76d6-40ec-adc2-59854ca516d0.png)

**Comment by itavero** [comment]
That's strange. Can you also share the device model/exposes information, which was also requested on the issue template?

**Comment by DracoC77** [comment]
Sorry about that had to figure out where to get that from:

        "0x000d6f0010807167": {
            "date_code": "20190426",
            "definition": {
                "description": "Magnetic door & window contact sensor",
                "exposes": [
                    {
                        "access": 1,
                        "description": "Indicates if the contact is closed (= true) or open (= false)",
                        "name": "contact",
                        "property": "contact",
                        "type": "binary",
                        "value_off": true,
                        "value_on": false
                    },
                    {
                        "access": 1,
                        "description": "Indicates if the battery of this device is almost empty",
                        "name": "battery_low",
                        "property": "battery_low",
                        "type": "binary",
                        "value_off": false,
                        "value_on": true
                    },
                    {
                        "access": 1,
                        "description": "Indicates whether the device is tampered",
                        "name": "tamper",
                        "property": "tamper",
                        "type": "binary",
                        "value_off": false,
                        "value_on": true
                    },
                    {
                        "access": 1,
                        "description": "Measured temperature value",
                        "name": "temperature",
                        "property": "temperature",
                        "type": "numeric",
                        "unit": "°C"
                    },
                    {
                        "access": 1,
                        "description": "Remaining battery in %",
                        "name": "battery",
                        "property": "battery",
                        "type": "numeric",
                        "unit": "%",
                        "value_max": 100,
                        "value_min": 0
                    },
                    {
                        "access": 1,
                        "description": "Link quality (signal strength)",
                        "name": "linkquality",
                        "property": "linkquality",
                        "type": "numeric",
                        "unit": "lqi",
                        "value_max": 255,
                        "value_min": 0
                    }
                ],
                "model": "XHS2-SE",
                "options": [
                    {
                        "access": 2,
                        "description": "Number of digits after decimal point for temperature, takes into effect on next report of device.",
                        "name": "temperature_precision",
                        "property": "temperature_precision",
                        "type": "numeric",
                        "value_max": 3,
                        "value_min": 0
                    },
                    {
                        "access": 2,
                        "description": "Calibrates the temperature value (absolute offset), takes into effect on next report of device.",
                        "name": "temperature_calibration",
                        "property": "temperature_calibration",
                        "type": "numeric"
                    }
                ],
                "supports_ota": false,
                "vendor": "Sercomm"
            },
            "endpoints": {
                "1": {
                    "bindings": [
                        {
                            "cluster": "genPollCtrl",
                            "target": {
                                "endpoint": 1,
                                "ieee_address": "0x00212effff07df4a",
                                "type": "endpoint"
                            }
                        },
                        {
                            "cluster": "msTemperatureMeasurement",
                            "target": {
                                "endpoint": 1,
                                "ieee_address": "0x00212effff07df4a",
                                "type": "endpoint"
                            }
                        }
                    ],
                    "clusters": {
                        "input": [
                            "genBasic",
                            "genPowerCfg",
                            "genIdentify",
                            "genPollCtrl",
                            "msTemperatureMeasurement",
                            "ssIasZone",
                            "haDiagnostic"
                        ],
                        "output": [
                            "genOta"
                        ]
                    },
                    "configured_reportings": [],
                    "scenes": []
                }
            },
            "friendly_name": "Guest Glass Door",
            "ieee_address": "0x000d6f0010807167",
            "interview_completed": true,
            "interviewing": false,
            "manufacturer": "Sercomm Corp.",
            "model_id": "XHS2-SE",
            "network_address": 27252,
            "power_source": "Battery",
            "supported": true,
            "type": "EndDevice"
        },

**Comment by DracoC77** [comment]
Makes sense, I just tried excluding battery at both a device level, then excluding it as a property globally and no change to the battery states (still 0%) reported in the hoomebridge dashboard (logic happens maybe before exclude?).

**Comment by itavero** [comment]
It might be that the check to see if the key is excluded is missing. Next time I work on the plugin, I'll check this.

**Comment by itavero** [comment]
Had a quick peek in the code, but `src/converters/battery.ts` does seem to filter out all excluded keys/properties.
I could add a test to see if this specific logic is working, but it's used in other places as well of which I know for sure that it works.

Can you perhaps share your plugin configuration, so I can see how you've excluded the property?
