### ISSUE TITLE
[Bug] Switch set many requests at same time

### ISSUE THREAD

**Issue by pierrepinon** [itavero/homebridge-z2m#459]
Please use the template and fill in all the data requested below!

**Describe the bug**
In Home App when I switch off or switch on outlet, it switch from off to on. If I restart Home app, the state is correct

**Related devices**
IKEA [E1603/E1702/E1708]

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Change 'Outlet state to on' via the Home app.
2. Log shows MQTT 3 message publish at same time being published to topic 'zigbee2mqtt/Prise Bureau'
`Info 2022-06-22 20:41:12MQTT publish: topic 'zigbee2mqtt/Prise Bureau', payload '{"last_seen":"2022-06-22T19:41:12+01:00","linkquality":54,"state":"OFF","update":{"state":"idle"}}'
Info 2022-06-22 20:41:13MQTT publish: topic 'zigbee2mqtt/Prise Bureau', payload '{"last_seen":"2022-06-22T19:41:12+01:00","linkquality":54,"state":"ON","update":{"state":"idle"}}'
Info 2022-06-22 20:41:13MQTT publish: topic 'zigbee2mqtt/Prise Bureau', payload '{"last_seen":"2022-06-22T19:41:12+01:00","linkquality":54,"state":"ON","update":{"state":"idle"}}'`

3. Home app report three change in same second (in this case on to off). After close home app, outlet state in correct

**Expected behavior**
Publish one action to MQTT broker rather than three

**MQTT messages**
If possible (and applicable), please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)
* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
* Messages published by this plugin that might be related to your issue (can also be seen in the homebridge logs)

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin : 1.8.0
 - Homebridge : 1.5.0
 - Zigbee2MQTT : 1.25.2
 - Homebridge Config UI X (if applicable)

**Comment by itavero** [comment]
The MQTT messages you show are status updates published by Zigbee2MQTT, not this plugin.

Tweaking your Zigbee2MQTT settings may help. It sounds similar to #383, so I'd suggest trying the configuration change mentioned there to begin with.

**Comment by pierrepinon** [comment]
@itavero Thx for your reply, it’s true !
