### ISSUE TITLE
Danalock V3 lock state wrong

### ISSUE THREAD

**Issue by smulle48** [itavero/homebridge-z2m#46]
Hi

Danalock v3 keeps telling it's unlocked, even though it's locked in z2m. In the home app it's saying it's locking

**Comment by itavero** [comment]
Please use the Bug Report issue template when reporting an issue. It would have asked you for some additional information that I really need in order to handle it.

Some of things the template would have asked you to fill in would be:

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Change '...' via the Home app.
2. Log shows MQTT message '...' being published to topic '...'
3. The device does the following: '...'

**Expected behavior**
A clear and concise description of what you expected to happen, compared to what actually happened.

**MQTT messages**
If possible (and applicable), please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)
* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
* Messages published by this plugin that might be related to your issue (can also be seen in the homebridge logs)

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin
 - Homebridge
 - Zigbee2MQTT (can be found in MQTT topic `zigbee2mqtt/bridge/info`)
 - Homebridge Config UI X (if applicable)

**Comment by smulle48** [comment]
To Reproduce
Steps to reproduce the behavior, for example:

Add lock to zigbee2mqtt and restart Conif UI X.

Zigbee2MQTT:debug 2021-01-27 22:33:03: Received MQTT message on 'zigbee2mqtt/0x000b57fffe59e37d/get' with data '{"state": ""}'
Zigbee2MQTT:debug 2021-01-27 22:33:03: Publishing get 'get' 'state' to '0x000b57fffe59e37d'
Zigbee2MQTT:debug 2021-01-27 22:33:08: Received Zigbee message from '0x000b57fffe59e37d', type 'readResponse', cluster 'closuresDoorLock', data '{"lockState":1}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2021-01-27 22:33:08: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe59e37d', payload '{"battery":80,"linkquality":63,"lock_state":"locked","state":"LOCK"}'
Zigbee2MQTT:debug 2021-01-27 22:33:15: Received Zigbee message from '0x000b57fffe59e37d', type 'commandOperationEventNotification', cluster 'closuresDoorLock', data '{"data":0,"opereventcode":2,"opereventsrc":2,"pin":0,"userid":65535,"zigbeelocaltime":665098393}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2021-01-27 22:33:15: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe59e37d', payload '{"action":"unlock","action_source":2,"action_source_name":"manual","action_user":65535,"battery":80,"linkquality":63,"lock_state":"locked","state":"LOCK"}'
Zigbee2MQTT:debug 2021-01-27 22:33:15: Received Zigbee message from '0x000b57fffe59e37d', type 'attributeReport', cluster 'closuresDoorLock', data '{"lockState":2}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2021-01-27 22:33:15: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe59e37d', payload '{"battery":80,"linkquality":45,"lock_state":"unlocked","state":"UNLOCK"}'

I can control the lock from the Danalock App and zigbee2mqtt frontend, but the state in Config UI X says "unlocked" and the Home app "Unlocking".

MQTT messages
If possible (and applicable), please provide the following:

Zigbee2MQTT:info  2021-01-27 22:30:06: Currently 5 devices are joined:
Zigbee2MQTT:info  2021-01-27 22:30:06: 0xccccccfffe027698 (0xccccccfffe027698): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)
Zigbee2MQTT:info  2021-01-27 22:30:06: 0xccccccfffe2fbac5 (0xccccccfffe2fbac5): LED1837R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (Router)
Zigbee2MQTT:info  2021-01-27 22:30:06: 0x000b57fffe59e37d (0x000b57fffe59e37d): V3-BTZB - Danalock BT/ZB smartlock (EndDevice)
Zigbee2MQTT:info  2021-01-27 22:30:06: 0x90fd9ffffe2ad84c (0x90fd9ffffe2ad84c): LED1650R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (Router)
Zigbee2MQTT:info  2021-01-27 22:30:06: 0x90fd9ffffe32886b (0x90fd9ffffe32886b): LED1650R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (Router)

Please provide the version of the following pieces of software:

This plugin - homebridge-z2m v1.1.0-beta.1
Homebridge - v1.1.7
Zigbee2MQTT (can be found in MQTT topic zigbee2mqtt/bridge/info) - Zigbee2MQTT version 1.17.0-dev (commit #54fc4fa)
Homebridge Config UI X (if applicable) - homebridge-config-ui-x v4.36.0

**Comment by itavero** [comment]
You didn't add the MQTT logs, but I can get them from the Zigbee2MQTT log you've added.
The last line of the log you have shared shows that Zigbee2MQTT publishes an MQTT message to state that the lock is unlocked.
```json
{"battery":80,"linkquality":45,"lock_state":"unlocked","state":"UNLOCK"}
```

If I understand your report correctly, you are saying that it shows up as unlocked, but you expect it say locked?
Do you also see an MQTT message that actually states that it is locked?

**Comment by itavero** [comment]
By the way, I don't have an automated test yet for a Zigbee lock (I don't own one myself).
Would you mind sharing the device entry for this particular device, as published to the MQTT topic `zigbee2mqtt/bridge/devices` by Zigbee2MQTT?

**Comment by smulle48** [comment]
> By the way, I don't have an automated test yet for a Zigbee lock (I don't own one myself).
> Would you mind sharing the device entry for this particular device, as published to the MQTT topic `zigbee2mqtt/bridge/devices` by Zigbee2MQTT?

[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genTime","genOta"],"output":["genPowerCfg","genPollCtrl","ssIasZone"]},"configured_reportings":[]},"242":{"bindings":[],"clusters":{"input":[],"output":["greenPower"]},"configured_reportings":[]}},"friendly_name":"Coordinator","ieee_address":"0x00212effff042817","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type":"Coordinator"},{"date_code":"03092018\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","definition":{"description":"BT/ZB smartlock","exposes":[{"features":[{"access":7,"description":"State of the lock","name":"state","property":"state","type":"binary","value_off":"UNLOCK","value_on":"LOCK"},{"access":1,"description":"Actual state of the lock","name":"lock_state","property":"lock_state","type":"enum","values":["not_fully_locked","locked","unlocked"]}],"type":"lock"},{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"V3-BTZB","vendor":"Danalock"},"endpoints":{"1":{"bindings":[{"cluster":"closuresDoorLock","target":{"endpoint":1,"ieee_address":"0x00212effff042817","type":"endpoint"}},{"cluster":"genPowerCfg","target":{"endpoint":1,"ieee_address":"0x00212effff042817","type":"endpoint"}}],"clusters":{"input":["genBasic","genPowerCfg","genIdentify","genAlarms","genPollCtrl","closuresDoorLock","haDiagnostic"],"output":["genTime","genOta","haDiagnostic"]},"configured_reportings":[{"attribute":"lockState","cluster":"closuresDoorLock","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0},{"attribute":"batteryPercentageRemaining","cluster":"genPowerCfg","maximum_report_interval":62000,"minimum_report_interval":3600,"reportable_change":0}]}},"friendly_name":"0x000b57fffe59e37d","ieee_address":"0x000b57fffe59e37d","interview_completed":true,"interviewing":false,"model_id":"V3-BTZB","network_address":50408,"power_source":"Battery","supported":true,"type":"EndDevice"}]

**Comment by smulle48** [comment]
This it the output, when I press the lock in Config UI X, but no matter what, it stays unlocked

Zigbee2MQTT:debug 2021-01-28 00:33:02: Received MQTT message on 'zigbee2mqtt/0x000b57fffe59e37d/set' with data '{"state":"UNLOCK"}'
Zigbee2MQTT:debug 2021-01-28 00:33:02: Publishing 'set' 'state' to '0x000b57fffe59e37d'
Zigbee2MQTT:debug 2021-01-28 00:33:07: Received Zigbee message from '0x000b57fffe59e37d', type 'commandOperationEventNotification', cluster 'closuresDoorLock', data '{"data":0,"opereventcode":2,"opereventsrc":1,"pin":0,"userid":65535,"zigbeelocaltime":665105586}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2021-01-28 00:33:07: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe59e37d', payload '{"action":"unlock","action_source":1,"action_source_name":"rf","action_user":65535,"battery":80,"linkquality":92,"lock_state":"locked","state":"LOCK"}'
Zigbee2MQTT:debug 2021-01-28 00:33:08: Received Zigbee message from '0x000b57fffe59e37d', type 'attributeReport', cluster 'closuresDoorLock', data '{"lockState":2}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2021-01-28 00:33:08: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe59e37d', payload '{"battery":80,"linkquality":91,"lock_state":"unlocked","state":"UNLOCK"}'
Zigbee2MQTT:debug 2021-01-28 00:33:10: Received MQTT message on 'zigbee2mqtt/0x000b57fffe59e37d/set' with data '{"state":"LOCK"}'
Zigbee2MQTT:debug 2021-01-28 00:33:10: Publishing 'set' 'state' to '0x000b57fffe59e37d'
Zigbee2MQTT:debug 2021-01-28 00:33:16: Received Zigbee message from '0x000b57fffe59e37d', type 'commandOperationEventNotification', cluster 'closuresDoorLock', data '{"data":0,"opereventcode":1,"opereventsrc":1,"pin":0,"userid":65535,"zigbeelocaltime":665105594}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2021-01-28 00:33:16: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe59e37d', payload '{"action":"lock","action_source":1,"action_source_name":"rf","action_user":65535,"battery":80,"linkquality":91,"lock_state":"unlocked","state":"UNLOCK"}'
Zigbee2MQTT:debug 2021-01-28 00:33:16: Received Zigbee message from '0x000b57fffe59e37d', type 'attributeReport', cluster 'closuresDoorLock', data '{"lockState":1}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2021-01-28 00:33:16: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe59e37d', payload '{"battery":80,"linkquality":91,"lock_state":"locked","state":"LOCK"}'

![Skærmbillede 2021-01-28 kl  00 34 19](https://user-images.githubusercontent.com/24297824/106068272-9f926d80-6100-11eb-8334-128edfef1058.png)

**Comment by smulle48** [comment]
When I turn the lock manually

![Skærmbillede 2021-01-28 kl  00 45 21](https://user-images.githubusercontent.com/24297824/106069145-3e6b9980-6102-11eb-8668-78d6cc173246.png)
![Skærmbillede 2021-01-28 kl  00 45 41](https://user-images.githubusercontent.com/24297824/106069152-41ff2080-6102-11eb-9685-74d7b41579fc.png)

**Comment by itavero** [comment]
I had I a quick look at src/converters/lock.ts (which is the code that handles these kind of devices).
I didn't spot anything obviously wrong (but then again, it's late and I'm also to one who wrote it 😅).

I'll try to setup an automated test for this, when I find some time to do so.

**Comment by smulle48** [comment]
I don't know if it has something to do with that I'm using Conbee2? (I'm on the latest firmware)

If you look at the screenshots from Config UI X, the "Lock Current State" don't change, so somehow the lock don't tell what status it's currently at, and if that's what your plugin is reading, then it's doomed :-D

I've ordered a CC2652RB stick. Hopefully it's here soon and then I'll try to setup a new network with that, to see if it helps :-D

**Comment by itavero** [comment]
Did spot a potential bug in `handleSetState`. The HomeKit value is used as a boolean, but according to [characteristics description](https://developers.homebridge.io/#/characteristic/LockTargetState) it's not a boolean but an integer.

I don't think this will cause the behavior you are experiencing, as this handles the message send "to" Zigbee2MQTT.

**Comment by itavero** [comment]
Looking at the messages in the Zigbee2MQTT log, it seems to be sending the right stuff:
```json
{"action":"unlock","action_source":1,"action_source_name":"rf","action_user":65535,"battery":80,"linkquality":92,"lock_state":"locked","state":"LOCK"}
```

```json
{"battery":80,"linkquality":91,"lock_state":"unlocked","state":"UNLOCK"}
```

The `lock_state` property is what the plugin should use.

**Comment by smulle48** [comment]
Maybe some here can guide you in the right direction. Looks exactly like my problem

[https://github.com/homebridge/HAP-NodeJS/issues/265](url)

**Comment by smulle48** [comment]
Just a wild guess (my ts skills are a bit rusty) but in the z2mmodels it's number (floating value?), but according to the HB docs, it should be uint8

**Comment by itavero** [comment]
If I understand the issue you've linked correctly, it is important to set both the `LockTargetState` and the `LockCurrentState` characteristic to the value HomeKit is expecting.
I would think that the current implementation does this, but once I have some spare time left to investigate this, I'll try to write a set of automated tests to verify this.

**Comment by itavero** [comment]
By the way, would it be possible to share logs of Zigbee2MQTT and the plugin of the same time frame, so I can actually relate them to eachother?

**Comment by smulle48** [comment]
> By the way, would it be possible to share logs of Zigbee2MQTT and the plugin of the same time frame, so I can actually relate them to eachother?

Sure

How do I get the logs from the plug-in? :-)

**Comment by itavero** [comment]
What I see in the logs:
* At 2021-1-30 4:51:22, you activate the lock from Homebridge, which publishes an MQTT message: `{"state":"LOCK"}`
* Within the same second, Zigbee2MQTT receives this messages and sends a request to the lock.
* At 2021-01-30 04:51:25, Zigbee2MQTT publishes the state of the lock after receiving a message on Zigbee, that says that the lock is unlocked: `{"battery":80,"linkquality":18,"lock_state":"unlocked","state":"UNLOCK"}`

So, if Homebridge shows that it is unlocked at that point, that is because Zigbee2MQTT published a message to indicate that this is the state.
If you send the MQTT message to lock / unlock manually (with MQTT Explorer or some other tool), what kind of behavior do you see then?

**Comment by smulle48** [comment]
> What I see in the logs:
> 
> * At 2021-1-30 4:51:22, you activate the lock from Homebridge, which publishes an MQTT message: `{"state":"LOCK"}`
> 
> * Within the same second, Zigbee2MQTT receives this messages and sends a request to the lock.
> 
> * At 2021-01-30 04:51:25, Zigbee2MQTT publishes the state of the lock after receiving a message on Zigbee, that says that the lock is unlocked: `{"battery":80,"linkquality":18,"lock_state":"unlocked","state":"UNLOCK"}`
> 
> * At 2021-01-30 04:51:26, Zigbee2MQTT publishes the state of the lock after receiving a message on Zigbee, that says that the lock is locked: `{"battery":80,"linkquality":12,"lock_state":"locked","state":"LOCK"}`
> 
> 
> 
> Maybe I have some time tonight to write an automated test to verify this behavior.
> 
> I don't see how the last message would cause it to show that the lock is unlocked, if I lock at the code.
> 
> 

I'll just check a bit later :-)

I'm starting to suspect that the problem is my conbee2 (I have ordered a cc2652)

If I add 3 IKEA spot, two old white and one new glass) to a group and bind a switch, it's sporadically which turns on and off, but if I remove the new glass spot, it works 99,999% of the time.

Btw, I tested the lock in HA, and there it reports correctly and react correctly on lock and unlock

**Comment by itavero** [comment]
Added a test and I found the mistake. The monitor for the `LockCurrentState` characteristic was passed the property of the wrong exposes entry, on [line 90 in `src/converters/lock.ts`](https://github.com/itavero/homebridge-z2m/blob/2c42616e53a314a5dc9950fbdb4bdaa8d00a5d9c/src/converters/lock.ts#L90).
I'll fix this and publish another release soon (not yet sure if the release will be today though).

**Comment by itavero** [comment]
@smulle48 Just published another [release](https://www.npmjs.com/package/homebridge-z2m/v/1.1.0-beta.3) (second one today already 😅) with the fix included. You can install it using `npm install homebridge-z2m@next`.

If the issue still persists, you can ofcourse reopen this issue, but I really hope this did the trick.

**Comment by smulle48** [comment]
> @smulle48 Just published another [release](https://www.npmjs.com/package/homebridge-z2m/v/1.1.0-beta.3) (second one today already 😅) with the fix included. You can install it using `npm install homebridge-z2m@next`.
> 
> 
> 
> If the issue still persists, you can ofcourse reopen this issue, but I really hope this did the trick.

Nice. Will try it ASAP and report back 😁

**Comment by smulle48** [comment]
> @smulle48 Just published another [release](https://www.npmjs.com/package/homebridge-z2m/v/1.1.0-beta.3) (second one today already 😅) with the fix included. You can install it using `npm install homebridge-z2m@next`.
> 
> If the issue still persists, you can ofcourse reopen this issue, but I really hope this did the trick.

And we have a winner :-D Tnx for the quick fix :-D

![Skærmbillede 2021-01-30 kl  18 16 17](https://user-images.githubusercontent.com/24297824/106363219-8ddedf00-6327-11eb-8377-a36f4075b523.png)
![Skærmbillede 2021-01-30 kl  18 16 23](https://user-images.githubusercontent.com/24297824/106363221-90413900-6327-11eb-8254-429ab1bf1f0e.png)
