### ISSUE TITLE
Homebridge update killed z2m?

### ISSUE THREAD

**Issue by montanaishome** [itavero/homebridge-z2m#472]
I just updated homebridge and now z2m (which runs on the same pi) will not run.  I get this error in the z2m log:

sudo: /use/local/bin/pm: command not found

npm seems to have moved to /opt/homebridge/bin

I tried to re-install NPM (sudo apt-get install npm) and got this error:

E: Package ‘npm’ has no installation candidate

I am at a loss and can’t get z2m to start.

**Comment by montanaishome** [comment]
pi@homebridge:/opt/homebridge/bin $ sudo npm --version
8.11.0

**Comment by itavero** [comment]
Definitely need more information on how you have installed it in the first place to provide any support in the first place.

Also, "homebridge-z2m" is a plugin for Homebridge that provides an integration for Zigbee2MQTT, so you do not start it separately, it should be loaded automatically when you start Homebridge.

If you are talking about Zigbee2MQTT, you might have better luck getting support on the [Zigbee2MQTT Discord server](https://discord.gg/NyseBeK) (but they probably also need more info than what has been provided here).
