### ISSUE TITLE
[Bug] Hue dimmers no longer work

### ISSUE THREAD

**Issue by ratsoid** [itavero/homebridge-z2m#478]
I have 3 Philips Hue Dimmers 324131092621 working with homebridge-z2m
https://z2m.dev/devices/philips/324131092621.html

They appear to no longer work after I updated to zigbee2mqtt v1.26.0. It might not be related since I was about 4 version behind. 

I've cleared the cached accessories, and still the remote doesn't appear to work and there are no logs in homebridge, but I do get this in zigbee2mqtt logs:

`MQTT publish: topic 'zigbee2mqtt/Extra Remote', payload '{"action":"on-press","battery":100,"brightness":191,"counter":1,"duration":0,"linkquality":240,"update":{"state":"idle"},"update_available":false}'`

**Comment by itavero** [comment]
I think you have to change the `legacy` property for this device in the configuration of Zigbee2MQTT.

**Comment by itavero** [comment]
#382 and #407 might be related
