### ISSUE TITLE
Several zigbee2mqtt bridges connected at same time

### ISSUE THREAD

**Issue by pratsenka** [itavero/homebridge-z2m#481]
**Describe the bug**
I've got 2 zigbee2mqtt bridges connected to 1 Homebridge v 1.5.0  at a time. Each z2m device bridges some zigbee sensors. But a Homebridge often looses some sensors or even all the sensors connected to one or another zigbee2mqtt bridge.

**Related devices**
One Zigbee2mqtt bridge is an Aqara Gateway  ZHWG11LM with Zigbee2MQTT application v 1.21.0 installed
It bridges WSDCGQ11LM and SJCGQ11LM sensors by Xiaomi and 2 TS0203sensors by Tuya
Second Zigbee2MQTT bridge is a Zigbee2MQTT v 1.26.0 installed at the same pc as Homebridge. It bridges 2  SNZB-02 - SONOFF sensors

**To Reproduce**
Everything was fine for some months while there was just 1 ZHWG11LM with corresponding sensors. Installing a second Z2M bridge brought troubles mentioned above.
I've triead to use the same base topic at both Z2B bridges or different topics and 2 zigbee2mqtt platforms described at homebridge configuration with no luck. Sometimes I see all the 6 sensors? sometimes just 1.

**Expected behavior**
A clear and concise description of what you expected to happen, compared to what actually happened.

**MQTT messages**
Right now I see 
---
info  2022-07-13 14:07:31: MQTT publish: topic 'core2mqtt/0x00124b0022fc8f84', payload '{"battery":100,"humidity":79.37,"linkquality":42,"temperature":16.79,"voltage":3200}'
info  2022-07-13 14:09:23: MQTT publish: topic 'core2mqtt/0x00124b0022fc8662', payload '{"battery":82,"humidity":50.36,"linkquality":45,"temperature":28,"voltage":2900}'
---
at zigbee2mqtt log.txt but only a device 0x00124b0022fc8662 is seen in Homebridge accessories screen.

**Versions used**
I use now
 - Homebridge Zigbee2MQTT v 1.9.0
 - Homebridge v 1.5.0
 - Zigbee2MQTT v 1.21.0 and 1.26.0
 - Homebridge Config UI X (if applicable) v 4.49.0

**Comment by itavero** [comment]
Are both Zigbee2MQTTs using a different MQTT server or at least a different prefix?

Also, in general it's probably better to create one large Zigbee network and have the second coördinator act as a router instead. Of course, the networks do have to have some devices that can see each other and act as a router.

**Comment by pratsenka** [comment]
Zigbee2MQTT bridges use the same MQTT server but the base topic now differs. I tried to use single base topic initially but moved to different base topics when my sensors started to disappear. It is hard to use a single Zigbee network because of a distance :(
