### ISSUE TITLE
[Bug] device_temperature , how to disable?

### ISSUE THREAD

**Issue by kevin11121147** [itavero/homebridge-z2m#486]
Hello, how to disable temperature device ?
![43C5A879-C967-4C90-8E3A-7C2E95E4E049](https://user-images.githubusercontent.com/60290349/179405517-e2101700-39fc-425e-a11d-06f25e36e39b.png)

**Comment by kevin11121147** [comment]
thank you for the quick reply.
this is what it looks like with me
![Uploading A14042A2-040A-4EA6-856F-5498C09005BE.png…]()

**Comment by kevin11121147** [comment]
thank you for the quick reply.
this is what it looks like with me
![849CACA5-F713-4522-969F-661B83F27745](https://user-images.githubusercontent.com/60290349/179500279-e938336b-5d80-4e01-8616-d2c9341c9172.png)

**Comment by itavero** [comment]
I don't see the `device_temperature` being excluded in your configuration.
You should probably add/merge the following in your existing configuration:
```json
{
   "platform": "zigbee2mqtt",
   "defaults": {
      "excluded_keys": [
         "device_temperature"
      ]
   }
}
```
