### ISSUE TITLE
[Device] AUBESS ZXZIR-02

### ISSUE THREAD

**Issue by Doelfke** [itavero/homebridge-z2m#489]
**Device description**
AUBESS ZXZIR-02 IR Remote

**Supported in Zigbee2MQTT?**
Is this device already supported by Zigbee2MQTT / zigbee-herdsman-converters?  **Yes**
If this is NOT the case, please add support for the device there first.
Read there manual on [How to support new devices](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html) for more information.
If this is the case, please provide the version in which support is present/added.

**Device model / Exposes information**
Provide the device model (also known as [exposes information](https://www.zigbee2mqtt.io/guide/usage/exposes.html)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by Zigbee2MQTT.

```json
ZXZIR-02
```

**Missing features/functionality**
It currently publishes a single entity to homekit that is not supported.  I should be able to learn multiple IR codes and expose them as switches.

**Suggested services and characteristics**
For each of the missing features, please mention to which HomeKit Services and Characteristics it should be mapped.
The [Homebridge Plugin Development documentation](https://developers.homebridge.io/) provides a nice overview of the standard HomeKit services and characteristics.
Note that some manufacturers also use custom services and characteristics (the Elgato Eve products for instance), which could also be mimicked if they have been reverse engineered.

**Comment by itavero** [comment]
you forgot to provide the device exposes information and some of the other requested information.

As far as I know, HomeKit does not provide a characteristic/service for learning devices. The exposes information probably doesn't include information on the learned devices either.
I think you'll be better of triggering the learning via the Zigbee2MQTT front-end (if needed, I don't know this device) and adding the devices in Homebridge via homebridge-mqttthing or something similar.
