### ISSUE TITLE
Missing states

### ISSUE THREAD

**Issue by kerradin** [itavero/homebridge-z2m#5]
Xiaomi wall double switch lumi.ctrl_ln2.aq1 sending state_left and state_right wich missing in z2m so it showing only temperature
![Screenshot 2020-07-02 at 14 27 41](https://user-images.githubusercontent.com/17070589/86353612-316ff000-bc70-11ea-9ab7-067177d65060.png)

**Comment by itavero** [comment]
Just to be sure: this device actually has two relays in side which you want to control via HomeKit?

**Comment by kerradin** [comment]
This one with two buttons https://www.aqara.com/en/smart_light_switch_no_neutral.html

**Comment by itavero** [comment]
@kerradin Just pushed a commit that should resolve this issue for you and expose an accessory with 2 switches (left and right).

*Please note:* these changes are currently in the `master` branch, but not yet released.
If possible, please verify the fix [by testing these changes](https://github.com/itavero/homebridge-z2m#testing-the-latest-changes).

**Comment by itavero** [comment]
By the way, I noticed the device also supplies you with a `power` and `consumption` attribute. I can probably also expose these to HomeKit, if you can tell me what the unit for these values is.

**Comment by itavero** [comment]
Published a new release with the (likely) fix for this issue.
Closing this issue for now. Please let me know if it doesn't work as expected.
