### ISSUE TITLE
[Device] TuYa ZS06

### ISSUE THREAD

**Issue by iUnstable0** [itavero/homebridge-z2m#501]
Please use the template and fill in all the data requested below!

**Device description**
Which device would you like to be supported in this plugin?

TuYa ZS06

**Supported in Zigbee2MQTT?**
Is this device already supported by Zigbee2MQTT / zigbee-herdsman-converters?

Yes it is supported

**Device model / Exposes information**
Provide the device model (also known as [exposes information](https://www.zigbee2mqtt.io/guide/usage/exposes.html)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by Zigbee2MQTT.

```json
[
  {
    "type": "switch",
    "features": [
      {
        "type": "binary",
        "name": "state",
        "property": "learn_ir_code",
        "access": 2,
        "value_on": "ON",
        "value_off": "OFF",
        "description": "Turn on to learn new IR code"
      }
    ]
  },
  {
    "type": "text",
    "name": "learned_ir_code",
    "property": "learned_ir_code",
    "access": 1,
    "description": "The IR code learned by device"
  },
  {
    "type": "text",
    "name": "ir_code_to_send",
    "property": "ir_code_to_send",
    "access": 2,
    "description": "The IR code to send by device"
  },
  {
    "type": "numeric",
    "name": "linkquality",
    "property": "linkquality",
    "access": 1,
    "unit": "lqi",
    "description": "Link quality (signal strength)",
    "value_min": 0,
    "value_max": 255
  }
]
```

**Missing features/functionality**
Its not supported

**Suggested services and characteristics**
I want to add my air conditioner

**Comment by itavero** [comment]
Unfortunately, I don't think I can support this device in this plugin, as the usage really depends on the IR device learned and I can't make a "one size fits all" conversion for this device.

If possible, I would suggest to use [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing) for this particular device instead.

**Comment by paradizelost** [comment]
I've got this device as well, and though I understand it may not be feasible to support it natively, is there a way to send the codes that i've learned with it?

**Comment by itavero** [comment]
> is there a way to send the codes that i've learned with it?

That should be possible with [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing)
