### ISSUE TITLE
[Device] GiEX QT06 Water irrigation valve

### ISSUE THREAD

**Issue by JeanMertz** [itavero/homebridge-z2m#502]
On the website, is it mentioned that the GiEX QT06 device [is supported](https://z2m.dev/devices/giex/qt06.html).

I recently added one to my home, and had to add an [external converter](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#instructions) to my zigbee2mqtt config to get it to work, due to a [change in manufacturer name](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4524).

After this, zigbee2mqtt correctly identifies the valve, but in Homekit it shows up as a generic unsupported device without any of the expected capabilities.

I tried using GH search to find any references to the internal device ID, seeing if I needed to add the new manufacturer here as well, but that doesn't seem to be needed. Is there anything else I need to do here?

**Comment by JeanMertz** [comment]
Thinking on this some more. It _is_ actually the case that I added the device to zigbee2mqtt _before_ I added the external converter. I noticed something was off in zigbee2mqtt, as it too showed an unsupported device, but it autocorrected itself right as I added the external converter and restarted the service.

Perhaps Homebridge is still holding on to that old data initially stored in z2m?

**Comment by JeanMertz** [comment]
Doesn't look like that's the issue. I [removed the device from the cache](https://github.com/oznu/homebridge-config-ui-x/issues/525#issuecomment-582668844) but it was re-added similarly as before.

**Comment by keness521** [comment]
If I understand correctly, the page you linked to confirms that the ONLY services this device exposes to HomeKit ARE the battery services. What you describe is exactly what that page is confirming it can do.

Not all devices supported by Zigbee2MQTT are supposed by Homebridge-Z2M (and therefore HomeKit).

It is a little confusing, but the page you linked to showing that it is supported at the top confirms that the services supported by HomeKit are:

[Battery]
  - Battery Level
  - Charging State
  - Status Low Battery

Below that it details ALL the services the device exposes to Zigbee2MQTT, but that doesn't mean HomeKit gets them. The list at the top is the key bit of information that tells you was is actually passed to HomeKit.

Look at the device information page for another device which is fully functional, and if it is a battery device, you see those same or similar battery services, but you also see listed the actual FUNCTIONAL services of the device as well. This device has no functional services exposed.

So unfortunately, at least at this point, that device looks like it only passes on its battery service, which you mentioned does work, so it is actually working as best as it "can" right now. (I have a thermostat in the same situation.)

**Comment by JeanMertz** [comment]
Ah yeah, all of that makes sense. It does appear that the device has enough details embedded to be able to advertise it as an irrigation system (the HAP specification document describes the need for a combination of "irrigation system" service and one or more "valve" services, with their own set of required characteristics, all of which can probably be fulfilled by the data exposed on MQTT).

However, I don't have the time currently to add a new converter for this, so I'll put this somewhere on my backlog in case I do ever find the time, and close this issue until then. Thank you for explaining how I should read those device pages, it triggered me to take a more in-depth look at the implementation details, and all of it makes more sense to me now.
