### ISSUE TITLE
[Feature] Reduce volume of logs printed to Homebridge console

### ISSUE THREAD

**Issue by EdwardChamberlain** [itavero/homebridge-z2m#518]
**Problem description**
Currently this plugin generates a large amount of entry into the logs page as every device interaction / message is logged. This can drown out critical issues (with other plugins) meaning they go undetected. 

**Suggested solution**
Add an option in config to change the log level for this plugin allowing device updates to be silenced.

**Describe alternatives you've considered**
-

**Additional context**
-

**Are you willing to contribute to this feature?**
Yes.

**Comment by itavero** [comment]
Just wondering: do you have debug logs (`-D`) turned on?
If so, have you considered turning them off?

I don't have it turned on and the only thing I see from this plugin is whenever it publishes a message (which most of the time means that a user operated an accessory).

What logs would you want to get rid off?

**Comment by EdwardChamberlain** [comment]
> Just wondering: do you have debug logs (-D) turned on?

I dont have this on, so am not seeing debug logs.

> I don't have it turned on and the only thing I see from this plugin is whenever it publishes a message (which most of the time means that a user operated an accessory).

These are the logs I am talking about here. 

While this is limited to when messages are published, that still adds up to a huge number of logs (at least for me) as I have quite a few z2m devices, multiple people sending commands and a large number automations running regularly (motion sensors are particularly noisy as they can end up firing off 10 to 15 messages just walking around the house to turn lights on and off). This results in this plugin producing roughly 30x more logs than all other plugins put together. Unless I am checking the logs daily its easy to miss errors / issues / etc being posted. 

It would be nice to have a way to suppress these publish messages and receive only critical / warning logs to help keep the log tidy and readable.

**Comment by itavero** [comment]
I'll see if I can make it so that you can configure these logs to be part of the "Debug" messages rather than the "Info" level I believe they are currently on. Not sure when I have time to do so, but seems like a rather easy change.

**Comment by JacVid** [comment]
Hello, 
I'm using homebridge-z2m v1.9.2.

No matter the value, "log": {"mqtt_publish": "warn"} or "log": {"mqtt_publish": "error"}, I still have all the Publish to 'zigbee2mqtt/...../set': '{"state":"ON"}' log information.

Can you help me disabling this logs ?

Thank you

**Comment by itavero** [comment]
This feature has not been released yet.
I'll let you know when it's available.

**Comment by itavero** [comment]
Just released `v1.10.0` to `homebridge-z2m@next` which includes this feature. Because there were quite some internal changes, I haven't pushed it to `latest` yet. So far it seems to be working fine on my setup, but if you run into any issues, please do let me know.
