### ISSUE TITLE
Aqara Opple WXCJKG13LM doesn't work on new IOs 16

### ISSUE THREAD

**Issue by gonzaechev** [itavero/homebridge-z2m#519]
**Describe the bug**
After the upgrade to IOs 16, these devices stopped appearing, also the automations that were there were eliminated

**Related devices**
WXCJKG11LM | Xiaomi Aqara Opple switch 1 band
WXCJKG12LM | Xiaomi Aqara Opple switch 2 bands
WXCJKG13LM | Xiaomi Aqara Opple switch 3 bands

**To Reproduce**
Upgrade your Iphone to 16v

**Expected behavior**
Before in the version of iOS 15 it detected it without problems, in 16 it did not

**Versions used**
Please provide the version of the following pieces of software:
 - z2m v1.9.0
 - Homebridge v1.5.0
 - Zigbee2MQTT 1.27.2
 - homebridge-config-ui-x v4.50.1

**Comment by itavero** [comment]
Did you also update your home hub (Apple TV or HomePod)?

I have the 3 band switch as well and have also updated my iPhone to iOS 16, but for me the device still works as it did before.

**Comment by gonzaechev** [comment]
> Did you also update your home hub (Apple TV or HomePod)?
> 
> I have the 3 band switch as well and have also updated my iPhone to iOS 16, but for me the device still works as it did before.
> 
> ![image](https://user-images.githubusercontent.com/203398/191336567-950d1bf1-35b5-4b14-be9d-364b95f56446.png)
> 
> Have you also tried a third party app like Eve to see if that still shows the device?
> 
> Since this plugin did not change, I expect a bug in one of the Apple releases is more likely.

Thank you for the response, yes I have two instalaciones with Homepods in V16, after the upgrade, al bands dissappeared from zigbee zm2 bridge. in Zigbee2mqtt no problem
![0EDE0D70-D63D-4E25-9487-6527FCBA791F](https://user-images.githubusercontent.com/12264738/191338691-aac08cfe-d9a8-4250-a637-37d3260bf6e2.png)
![8DEC953A-5EAA-4E37-930A-6DE0E0639165](https://user-images.githubusercontent.com/12264738/191338703-3fe7e29e-2116-4a13-9d46-508d1bc0e2b8.png)

**Comment by itavero** [comment]
I guess it has to do with the updates of the HomePods. I don't have those so I don't know how to reproduce it.

Also, I don't know if this can even be fixed if Apple deliberately decided to change this behavior.

**Comment by gonzaechev** [comment]
Thank you for your help. It seems that they have removed this functionality, I will continue investigating. In homebridge the switch still appears

![image](https://user-images.githubusercontent.com/12264738/191342239-6d818eb9-d311-4654-ac86-a4459193e71c.png)

**Comment by BastienClermont** [comment]
Hello, I also have the same issue as you, by switching from iOS 15 to iOS 16 all my stateless programmable switches went away from the HomeKit app. They're still visible and active in zigbee2mqtt logs and home bridge accessory panel (but not showing a log entry when I press the switch). My switches models are Xiaomi Aqara WXKG11LM and Xiaomi Aqara WXKG02LM . 
Also it's good to mention that these models of switches also have a temperature service and they are visible in HomeKit and the temperature updates frequently, so it appears that it's not a problem of zigged communication, but the Stateless Programmable Switch service not showing in HomeKit...

**Comment by itavero** [comment]
One thing I noticed is that Stateless Programmable Switches are not shown in the overview in the new Home.app on iOS 16.
I really had to go into a room (e.g. by clicking its name in the overview) to see that service.
