### ISSUE TITLE
[Feature] Support regions of Aqara FP1 sensor

### ISSUE THREAD

**Issue by M4R1U5-W** [itavero/homebridge-z2m#568]
Please use the template and fill in all the data requested below!

**Problem description**
In the Home App there is no support for regions from the Aqara FP1 Sensor.

**Suggested solution**
You could implement a Button with the different Regions with the different states like entering or leaving the zone.

**Describe alternatives you've considered**
Another possible way would be, that there are more than one exposed Sensor, named by the regions you set in the aquaria app.

**Additional context**
This is the view from the Aqara App:

![image](https://user-images.githubusercontent.com/23058300/202520507-d64e406d-eef4-4b48-9bfb-c89901bc7ad3.png)

May there are any possibilities to implement this feature. It would be very helpful for my automations.

**Are you willing to contribute to this feature?**
Yes

**Comment by itavero** [comment]
Can you also include the `exposes` information for this device?

Is there an easy way for the plugin to discover the configured zones?
