### ISSUE TITLE
[Bug] Ledadvance Smart+ Switch Mini we detected but does not switch

### ISSUE THREAD

**Issue by cjk2** [itavero/homebridge-z2m#571]
The switch is detected via Zigbee MQTT and also integrated into homebridge. However, 10 possible buttons are displayed in homebridge. In fact, the Ledadvance Smart+ Switch Mini has only three buttons: up, down, Circle. 
In zigbee2mqtt the correct values for the buttons are also displayed when switching. In Homebridge, however, nothing arrives and I can not switch anything. 
Does anyone have an idea?

Ledadvance Smart+ Switch Mini https://www.zigbee2mqtt.io/devices/AC0251100NJ_AC0251600NJ_AC0251700NJ.html#osram-ac0251100nj%252Fac0251600nj%252Fac0251700nj

**Comment by itavero** [comment]
Unfortunately you did not use the template provided for bugs, so now I'm missing a lot of information needed to analyze this.

Can you provide me with at least the following:
- Versions of the software you are running
- Exposes information for the device
- Logs from when Homebridge starts (should show the mapping of the action values)
- MQTT messages published by Zigbee2MQTT for this device

My best guess at this point is that the exposes information for this device is incorrect or that the device has `legacy` option that needs to be changed.

**Comment by cjk2** [comment]
Sorry for the oversight. I did not have all the data at hand right away. Here now the data. I hope they are complete.

**Versions of the software:**
Zigbee2MQTT: 1.28.2 commit: e66fe85
Homebridge: v1.5.1
PlugIn: homebridge-z2m v1.9.2

**Expose for the Device:**
Friendly name: Ledadvance 1
Description
Device type: EndDevice
Zigbee Model: Lightify Switch Mini
Zigbee Manufacturer: OSRAM
Description: Smart+ switch mini
Support status: Supported
IEEE Address: 0x000d6f001417f5c5
Network address: 0x5948
Firmware build date: 201904240821440
Firmware version: e.1.11.0M
Manufacturer: [OSRAM](https://www.zigbee2mqtt.io/supported-devices/#v=OSRAM)
Model: [AC0251100NJ/AC0251600NJ/AC0251700NJ](https://www.zigbee2mqtt.io/devices/AC0251100NJ_AC0251600NJ_AC0251700NJ.html#osram-ac0251100nj%252Fac0251600nj%252Fac0251700nj)
Power: Battery 100%
Interview completed: True

**Log from Homebridge start:**
[29.11.2022, 07:52:14] [zigbee2mqtt] Mapping of property 'action' of device 'Ledadvance 1':
Button 1 (off):
        - SINGLE: off
Button 2 (on):
        - SINGLE: on
Button 3 (brightness_stop):
        - SINGLE: brightness_stop
Button 4 (hue_move):
        - SINGLE: hue_move
Button 5 (hue_stop):
        - SINGLE: hue_stop
Button 6 (brightness_move_down):
        - SINGLE: brightness_move_down
Button 7 (brightness_move_up):
        - SINGLE: brightness_move_up
Button 8 (color_temperature_move):
        - SINGLE: color_temperature_move
Button 9 (move_to_saturation):
        - SINGLE: move_to_saturation
Button 10 (brightness_move_to_level):
        - SINGLE: brightness_move_to_level

**MQTT Messages:**
Info 2022-11-29 07:53:48MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{"action":"up","battery":100,"linkquality":255,"voltage":3000}'
Info 2022-11-29 07:53:53MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{"action":"circle_click","battery":100,"linkquality":255,"voltage":3000}'
Info 2022-11-29 07:53:55MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{"action":"down","battery":100,"linkquality":255,"voltage":3000}'

**Comment by cjk2** [comment]
**6 more MQTT Messages:**

Info 2022-11-29 07:56:48MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{"action":"up_hold","battery":100,"linkquality":255,"voltage":3000}'
Info 2022-11-29 07:56:50MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{"action":"up_release","battery":100,"linkquality":255,"voltage":3000}'
Info 2022-11-29 07:56:53MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{"action":"down_hold","battery":100,"linkquality":255,"voltage":3000}'
Info 2022-11-29 07:56:55MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{"action":"down_release","battery":100,"linkquality":255,"voltage":3000}'
Info 2022-11-29 07:56:57MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{"action":"circle_hold","battery":100,"linkquality":255,"voltage":3000}'
Info 2022-11-29 07:57:00MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{"action":"circle_release","battery":100,"linkquality":255,"voltage":3000}'

**Comment by itavero** [comment]
The exposes information should be a JSON description of the properties the device exposes/provides, which is part of the device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`).

What I can already notice is that device is sending values that do not appear to be listed in this exposes information (otherwise I would expect them to be in the mapping written to the log).

Have you checked if the device indeed has a `legacy` option in Zigbee2MQTT?
If it doesn't, it seems like a bug in zigbee-herdsman-converters (based on the information I have at hand right now).

**Comment by cjk2** [comment]
Sorry. I'm new in zigbee2MQTT:

Is this the right JSON:
            "friendly_name": "Ledadvance 1",
            "ieee_address": "0x000d6f001417f5c5",
            "interview_completed": true,
            "interviewing": false,
            "manufacturer": "OSRAM",
            "model_id": "Lightify Switch Mini",
            "network_address": 22856,
            "power_source": "Battery",
            "software_build_id": "e.1.11.0M",
            "supported": true,
            "type": "EndDevice"

Or where can I find the Infos?

**Comment by itavero** [comment]
Personally I find a client like MQTT Explorer to be the easiest way to read the data published to the MQTT broker.

The `legacy` option you can probably also find in the Zigbee2MQTT front-end if it exists.

**Comment by cjk2** [comment]
Now I've found the JSON:
{"level":"info","message":"MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{\"action\":\"circle_click\",\"battery\":100,\"linkquality\":255,\"voltage\":3000}'"}
{"level":"info","message":"MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{\"action\":\"down\",\"battery\":100,\"linkquality\":255,\"voltage\":3000}'"}
{"level":"info","message":"MQTT publish: topic 'zigbee2mqtt/Ledadvance 1', payload '{\"action\":\"up\",\"battery\":100,\"linkquality\":255,\"voltage\":3000}'"}

**Comment by itavero** [comment]
That's not the information I've asked for.

Please see:
- https://www.zigbee2mqtt.io/guide/usage/exposes.html
- https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-devices

Anyway, **have you checked for the `legacy` option** in the Zigbee2MQTT front-end?

**Comment by cjk2** [comment]
With the legacy-mode false it works. From the 10 switches offered, 1 and 2 are the arrows and 10 is the circle. Thank you

**Comment by itavero** [comment]
If you want to get rid of the other buttons, you can include/exclude specific `values` in your configuration. The [documentation of the plugin includes an example](https://z2m.dev/config.html).

Closing this issue, as there does not seem to be a bug in homebridge-z2m.
