### ISSUE TITLE
[Device] Atlantic Group GW003-AS-IN-TE-FC / Takao

### ISSUE THREAD

**Issue by Ch4rlus** [itavero/homebridge-z2m#591]
**Device description**
"Atlantic Group GW003-AS-IN-TE-FC" (also known as Atlantic Takao)

**Supported in Zigbee2MQTT?**
Yes, device is already supported in Zigbee2MQTT (see https://www.zigbee2mqtt.io/devices/GW003-AS-IN-TE-FC.html)

**Device model / Exposes information**

```json
[
  {
    "type": "enum",
    "name": "programming_operation_mode",
    "property": "programming_operation_mode",
    "access": 7,
    "values": [
      "setpoint",
      "schedule",
      "eco"
    ],
    "description": "Controls how programming affects the thermostat. Possible values: setpoint (only use specified setpoint), schedule (follow programmed setpoint schedule). Changing this value does not clear programmed schedules."
  },
  {
    "type": "climate",
    "features": [
      {
        "type": "numeric",
        "name": "local_temperature",
        "property": "local_temperature",
        "access": 5,
        "unit": "°C",
        "description": "Current temperature measured on the device"
      },
      {
        "type": "numeric",
        "name": "occupied_cooling_setpoint",
        "property": "occupied_cooling_setpoint",
        "access": 7,
        "value_min": 18,
        "value_max": 30,
        "value_step": 0.5,
        "unit": "°C",
        "description": "Temperature setpoint"
      },
      {
        "type": "numeric",
        "name": "occupied_heating_setpoint",
        "property": "occupied_heating_setpoint",
        "access": 7,
        "value_min": 16,
        "value_max": 30,
        "value_step": 0.5,
        "unit": "°C",
        "description": "Temperature setpoint"
      },
      {
        "type": "enum",
        "name": "system_mode",
        "property": "system_mode",
        "access": 7,
        "values": [
          "off",
          "heat",
          "cool",
          "auto",
          "dry",
          "fan_only"
        ],
        "description": "Mode of this device"
      },
      {
        "type": "enum",
        "name": "preset",
        "property": "preset",
        "access": 3,
        "values": [
          "activity",
          "boost",
          "eco"
        ],
        "description": "Mode of this device (similar to system_mode)"
      },
      {
        "type": "enum",
        "name": "fan_mode",
        "property": "fan_mode",
        "access": 7,
        "values": [
          "low",
          "medium",
          "high",
          "auto"
        ],
        "description": "Mode of the fan"
      },
      {
        "type": "enum",
        "name": "swing_mode",
        "property": "swing_mode",
        "access": 3,
        "values": [
          "on",
          "off"
        ],
        "description": "Swing mode"
      }
    ]
  },
  {
    "type": "binary",
    "name": "quiet_fan",
    "property": "quiet_fan",
    "access": 3,
    "value_on": true,
    "value_off": false,
    "description": "Fan quiet mode"
  },
  {
    "type": "enum",
    "name": "ac_louver_position",
    "property": "ac_louver_position",
    "access": 3,
    "values": [
      "quarter_open",
      "half_open",
      "three_quarters_open",
      "fully_open"
    ],
    "description": "Ac louver position of this device"
  },
  {
    "type": "numeric",
    "name": "linkquality",
    "property": "linkquality",
    "access": 1,
    "unit": "lqi",
    "description": "Link quality (signal strength)",
    "value_min": 0,
    "value_max": 255
  }
]
```

**Missing features/functionality**
None of the features seems currently exposed to homebridge.

**Suggested services and characteristics**
Device should behave like a thermostat (heater/cooler). I think all the needed functions are already been handled/decoded by Z2Mqttt

**Comment by itavero** [comment]
If I recall correctly, it's probably currently not working as it has a separate heating and cooling setpoint, which is not natively supported by HomeKit.

Any suggestions on how to deal with this are welcome.

(If you only use it for heating, you might give excluding the cooling setpoint a shot to see if it does end up in HomeKit then)

**Comment by itavero** [comment]
I think I can make some code that maps devices with both a heating and cooling setpoint as a [Heater Cooler](https://developers.homebridge.io/#/service/HeaterCooler).
I guess the setpoints should be mapped to the Heating/Cooling Threshold Temperature attributes?

`swing_mode` can be mapped to [Swing Mode](https://developers.homebridge.io/#/characteristic/SwingMode), but I'm not sure how to map `fan_mode` to [Rotation Speed](https://developers.homebridge.io/#/characteristic/RotationSpeed).

I should probably also check which other devices have both a heating and a cooling setpoint and if they can also be mapped.

**Comment by Ch4rlus** [comment]
On this unit fan_mode has only 4 settings, which are auto, low, medium and high speed. That does not really fit with what Homekit expects (percentage). 

I've worked something out with mqttthing a few days ago, and I just made steps: 0-10% = auto, 10%-40% = low, 40% - 70% = medium, 70%-100% = high. 

Clearly not ideal, but it does the job
