### ISSUE TITLE
[Device] TuYa GDC311ZBQ1

### ISSUE THREAD

**Issue by Ropuh** [itavero/homebridge-z2m#594]
**Device description**
LoraTap Wireless Garage Door Opener

**Supported in Zigbee2MQTT?**
Is this device already supported by Zigbee2MQTT / zigbee-herdsman-converters?
Yes

**Device model / Exposes information**
 ##
https://www.zigbee2mqtt.io/devices/GDC311ZBQ1.html#tuya-gdc311zbq1

**Comment by itavero** [comment]
Unfortunately, you have not filled in all the information requested in the template.
I reckon this is a duplicate of #471 / #444.
