### ISSUE TITLE
[Feature] Carbon dioxide sensors support

### ISSUE THREAD

**Issue by satter** [itavero/homebridge-z2m#609]
### Problem description

There is currently no support for CO2 sensors in homebride-z2m plugin:
https://z2m.dev/devices/custom_devices_diy/efekta_co2_smart_monitor.html
https://z2m.dev/devices/custom_devices_diy/efekta_iaq.html
https://z2m.dev/devices/titan_products/tpzrco2ht-z3.html
https://z2m.dev/devices/tuya/ts0601_co2_sensor.html

z2m reports co2 levels, both homebridge and apple homekit seems to be supporting co2:
https://developers.homebridge.io/#/service/CarbonDioxideSensor
https://developer.apple.com/documentation/homekit/hmcharacteristictypecarbondioxidelevel

### Suggested solution

Looks like new basic sensor needed (similar to `carbon_monoxide.ts`)

### Additional context / information

I'm not sure I can help with writing code, but I definitely can test new versions on my co2 sensors

**Comment by itavero** [comment]
I briefly looked at this in the past.
Probably have to add a configurable setpoint for the mandatory [Carbon Dioxide Detected](https://developers.homebridge.io/#/characteristic/CarbonDioxideDetected) characteristic.
Back then, I didn't have a good way to make that configurable, but in the mean time, I've added a mechanism for such things.

**Comment by itavero** [comment]
Just made an implementation with a fixed detection threshold (1200 ppm). Still have to double check it, merge it and release it though.

I don't own a CO2 sensor myself, so I'm hoping my automated test is sufficient.

**Comment by itavero** [comment]
Added initial support in `v1.11.0-beta.2` (available on the `next` release channel).

**Comment by satter** [comment]
The integration is running without any issues so far: value is reported and sensor alerts are working.

It also would be nice to have configurable detection threshold. 1200 is okay for default but due to personal sensitivity I would like to set detection around 1000 ppm

**Comment by satter** [comment]
I think this version could be merged into master

**Comment by satter** [comment]
it is not stale

**Comment by itavero** [comment]
> I think this version could be merged into master

It already is. It's just not released in a "non-beta" release yet. Unfortunately there's still some things to improve in the last beta release with regards to adaptive lighting.
