### ISSUE TITLE
Multiple messages are being sent [Bug] 

### ISSUE THREAD

**Issue by gbsingh1993** [itavero/homebridge-z2m#61]
**Describe the bug**
When I trigger an action for some reason this plugin publishes two messages to the MQTT broker. Sometimes this is fine but sometimes this causes automations to fire twice or weird things to show up in the home app. One of these weird things is when changing my radiator valve from HEAT to anything else it will get stuck in a weird loop where it will randomly publish messages and flick between states until you leave it alone for a bit and try again.

**Related devices**
Switches
Radiator Valves 

**To Reproduce**
1. Change the state of a device in the Home App
2. Look at the logs on Homebridge and you will see two publish messages
3. Look at the zigbee2mqtt logs on and you will see two or more messages being received an it responding for each message

**Expected behavior**
only one message to be sent for one action in the Home App

**MQTT messages**
[2/10/2021, 12:58:24] [zigbee2mqtt] Publish to 'zigbee2mqtt/xxxxx/set': '{"state_right":"OFF"}'
[2/10/2021, 12:58:26] [zigbee2mqtt] Publish to 'zigbee2mqtt/xxxxx/set': '{"state_right":"OFF"}'

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin - 1.1.1
 - Homebridge - 1.2.5
 - Zigbee2MQTT (can be found in MQTT topic `zigbee2mqtt/bridge/info`) - 1.17.0
 - Homebridge Config UI X (if applicable) - 4.38.0

**Comment by itavero** [comment]
I can see if I can add some logging for changes from HomeKit, but as far as I can tell this just means that HomeKit is triggering the change multiple times (especially since there is two seconds between the messages).
I've never experienced any behavior like this myself.

Can you maybe add the exact steps you take and for which specific device you do this?

**Comment by gbsingh1993** [comment]
Hey,
Apologies for the late response. I think the issue might be with the Home app and my hubs. This can be closed for now and I will monitor and get back to you guys if anything comes up.

Thank you :)
