### ISSUE TITLE
[Feature] Explictly include devices via config UI

### ISSUE THREAD

**Issue by platini76** [itavero/homebridge-z2m#610]
### Problem description

my config:

"defaults": {
                "exclude": true
            },
            "devices": [
                {
                    "id": "xxxxxxxxxxxx",
                    "exclude": false
                }

### Suggested solution

can you create a box in visual config where add every include device instead of insert them into json?
thanks

**Comment by itavero** [comment]
I thought this was already possible by adding the device to the list and not checking the exclude checkbox. Unfortunately I just checked and it seems that it only adds the `id` to the JSON, but but the `exclude` property.

I'll see if I can change the schema to resolve this.

**Comment by platini76** [comment]
Fammi sapere se risolvi. Grazie
Let me know thanks
