### ISSUE TITLE
[Feature] Exclude Zigbee2MQTT group from HomeKit

### ISSUE THREAD

**Issue by Jeepmg** [itavero/homebridge-z2m#612]
### Problem description

I created a group of bulbs in Z2M to link it to a Hue remote.

The group appears in Homebridge and in Homekit. If I hide it in Homebridge accessories web page, it still appears in Homekit unlike the other accessories.

### Suggested solution

Group disappears from Homekit when hidden in Homebridge accessories web page as an accessory

### Alternative solutions

I can hide the group in Homebridge configuration.

**Comment by itavero** [comment]
This is already possible by adding an entry to the plugin configuration, similar to excluding a device.
Instead of the IEEE address, you'd have to use the group ID or its friendly name.

https://z2m.dev/config.html#devices
