### ISSUE TITLE
[Bug] Stateless Programmable Button Event Mapping

### ISSUE THREAD

**Issue by m1nimt** [itavero/homebridge-z2m#639]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a hue dimmer switch. it supports single click and hold. when i click it it sends out two messages: 

> on_press

> on_press_release 

same thing when i hold except it sends out an on_press first:

> on_press

> on_hold

> on_hold_release

so because of the of the [event mapping](https://z2m.dev/action.html) of this plugin, when i hold the button, homekit thinks im pressing the button AND holding it. (i.e single press turns light on, hold opens blinds. when i hold to open only my blinds it will also register a single click turning the lights on too)

### Related devices

Phillips Hue Dimmer Switch V2 

### Expected behavior

I would like for it to respond to any .._.._release as it would prevent dual inputs

### Status update

```json
Info 2023-02-18 16:03:16MQTT publish: topic 'zigbee2mqtt/Hue Dimmer Switch', payload '{"action":"on_press","battery":86,"linkquality":116,"update":{"installed_version":33565954,"latest_version":33565954,"state":"idle"},"update_available":false}'

Info 2023-02-18 16:03:16MQTT publish: topic 'zigbee2mqtt/Hue Dimmer Switch', payload '{"action":"on_hold","action_duration":0.794,"battery":86,"linkquality":116,"update":{"installed_version":33565954,"latest_version":33565954,"state":"idle"},"update_available":false}'


Info 2023-02-18 16:03:17MQTT publish: topic 'zigbee2mqtt/Hue Dimmer Switch', payload '{"action":"on_hold_release","battery":86,"linkquality":108,"update":{"installed_version":33565954,"latest_version":33565954,"state":"idle"},"update_available":false}'
```

### This plugin

1.9.2

### Homebridge

v1.6.0

### Zigbee2MQTT

 1.30.1 commit: eb878d3

### Homebridge Config UI X (if applicable)

v4.50.2

**Comment by itavero** [comment]
This is the device you are referring to, right?

https://www.zigbee2mqtt.io/devices/929002398602.html
