### ISSUE TITLE
[Bug] Devices Appear in the Zigbee2MQTT Frontend but not in Homebridge

### ISSUE THREAD

**Issue by danmcpherson** [itavero/homebridge-z2m#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I think I have everything setup correctly and as follows: 

Raspberry Pi running the Homebridge image. 

1. Mosquitto is installed on the Pi. 
2. Zigbee2MQTT is installed on the Pi. 

I have paired two devices which appear in the frontend, the logs looks to be exactly what I would expect (see below).
I then added the homebridge-z2m v1.9.2 add in, also configured as both a child bridge and direct. 

However, I dont see these appear as accessories (and of course not in the Home app). Any help appreciated. 

<img width="787" alt="image" src="https://user-images.githubusercontent.com/18294661/220687971-5bf84218-54e5-4272-9940-2747dbd05a1b.png">

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/18294661/220687470-04bb61e0-ef48-4bf3-95fb-84532c61a551.png">

Zigbee2MQTT:info  2023-02-22 17:01:36: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-02-22.17-01-36' filename: log.txt
Zigbee2MQTT:info  2023-02-22 17:01:36: Starting Zigbee2MQTT version 1.30.1 (commit #eb878d3)
Zigbee2MQTT:info  2023-02-22 17:01:36: Starting zigbee-herdsman (0.14.89)
Zigbee2MQTT:info  2023-02-22 17:01:38: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-02-22 17:01:38: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20220219,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2023-02-22 17:01:38: Currently 2 devices are joined:
Zigbee2MQTT:info  2023-02-22 17:01:38: Downstairs Toilet Light Strip ZM (0x001788010b45ffda): 8718699703424 - Philips Hue white and color ambiance LightStrip plus (Router)
Zigbee2MQTT:info  2023-02-22 17:01:38: Downstairs Toilet Ceiling ZM (0x001788010bbb95ed): 929001953301 - Philips Hue white ambiance GU10 with Bluetooth (Router)
Zigbee2MQTT:warn  2023-02-22 17:01:38: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2023-02-22 17:01:38: Allowing new devices to join.
Zigbee2MQTT:warn  2023-02-22 17:01:38: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2023-02-22 17:01:38: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2023-02-22 17:01:38: Connecting to MQTT server at mqtt://localhost
Zigbee2MQTT:info  2023-02-22 17:01:39: Connected to MQTT server
Zigbee2MQTT:info  2023-02-22 17:01:39: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
Zigbee2MQTT:info  2023-02-22 17:01:39: Started frontend on port 0.0.0.0:8080
Zigbee2MQTT:info  2023-02-22 17:01:39: MQTT publish: topic 'zigbee2mqtt/Downstairs Toilet Light Strip ZM', payload '{"color_mode":"xy","linkquality":76,"update":{"installed_version":16784902,"latest_version":16785154,"state":"available"}}'
Zigbee2MQTT:info  2023-02-22 17:01:39: MQTT publish: topic 'zigbee2mqtt/Downstairs Toilet Ceiling ZM', payload '{"color_mode":"xy","linkquality":21,"state":"ON","update":{"installed_version":16784402,"latest_version":16784918,"state":"available"}}'
Zigbee2MQTT:info  2023-02-22 17:01:39: Zigbee2MQTT started!
Zigbee2MQTT:info  2023-02-22 17:05:25: MQTT publish: topic 'zigbee2mqtt/Downstairs Toilet Light Strip ZM', payload '{"color_mode":"xy","linkquality":83,"update":{"installed_version":16784902,"latest_version":16785154,"state":"available"}}'
Zigbee2MQTT:info  2023-02-22 17:05:25: Update available for 'Downstairs Toilet Light Strip ZM'
Zigbee2MQTT:info  2023-02-22 17:06:43: MQTT publish: topic 'zigbee2mqtt/Downstairs Toilet Ceiling ZM', payload '{"color_mode":"xy","linkquality":21,"state":"ON","update":{"installed_version":16784402,"latest_version":16784918,"state":"available"}}'
Zigbee2MQTT:info  2023-02-22 17:06:43: Update available for 'Downstairs Toilet Ceiling ZM'

### This plugin

homebridge-z2m v1.9.2

### Homebridge

1.6.0

### Zigbee2MQTT

1.30.1

**Comment by itavero** [comment]
Can you please include debug logs from Homebridge when it is starting up?

**Comment by itavero** [comment]
It seems that it never connects to the MQTT server (otherwise I would have expected more log entries from the plugin), have you checked that it is reachable from the environment where Homebridge is running?
