### ISSUE TITLE
[Feature] Reporting TS0601 illumination the same way as TS0222 illumination

### ISSUE THREAD

**Issue by Avamander** [itavero/homebridge-z2m#672]
### Problem description

I have two devices, TS0601 (motion sensor with illumination sensor) and TS0222 (temperature, illumination and humidity sensor with display). Unfortunately only the TS0222 lux reading appears in HomeKit.

The TS0601 reports `illuminance` (Raw measured illuminance) and it's displayed in lux, but not `illuminance_lux`. As opposed to the TS0222 which reports both (but `illuminance` is actually a raw value without an unit).

### Suggested solution

That `illuminance` would be considered `illuminance_lux` in the case of sensors that just have a single `illuminance` value.

**Comment by itavero** [comment]
You can provide a custom exposes information for this device in the plugin configuration as a workaround.
On the other hand, if it really reports the value in lux then the exposes information in koenkk/zigbee-herdsman-converters should probably be corrected.

**Comment by RobXYZ** [comment]
I have the same issue. How would I implement the workaround of custom exposes? Is this in the homebridge-z2m config? Thanks
