### ISSUE TITLE
[Bug] Device value less than 1% showing 100% in HomeKit

### ISSUE THREAD

**Issue by jtheller** [itavero/homebridge-z2m#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have IKEA TRADFRI bulbs that could be dimmed all the way down to 1/254 reported value in Zigbee2mqtt, or 0.39%. For some reason when the percentage value goes less than 1 it will be mistakenly reported as 100% in the Home app...could be an Apple thing for them to fix, but in the meantime could we implement this to [monitor.ts](https://github.com/itavero/homebridge-z2m/blob/master/src/converters/monitor.ts#L148)?- 

```
transformValueFromMqtt(value: unknown): CharacteristicValue | undefined {

  ...

  const percentage = (input - this.input_min) / (this.input_max - this.input_min);

  const result = out_minimum + percentage * (out_maximum - out_minimum);

  // Limit min possible return value to 1.
  if (result < 1 && result > 0) return Math.ceil(result);

  return result;
}
```

This will help HomeKit read less than 1% values somewhat correctly. 

I believe the change should only affect lights and battery percentages.

### Related devices

- TRADFRI LED bulb E26/E27 800/806 lumen, dimmable, white spectrum, clear

and potentially other bulbs.

### Steps To Reproduce

1. Use hardware dimmer switch or remote, or through Zigbee2mqtt, dim the lights to a brightness percentage value of less than 1%.
2. Observe in the Home app that reported brightness stays or jumps back to 100%.
3. Raise the brightness to a percentage value of greater than or equal 1%.
4. Observe in the Home app that reported brightness resumes correctly again.

### Expected behavior

Expect in the Home app that the reported value should correctly follow the calculated percentage even when it's less than 1%.

### This plugin

1.9.2

### Homebridge

1.6.0

### Zigbee2MQTT

1.30.3

**Comment by itavero** [comment]
Can you make a PR for this?
Never seen this behavior myself, but I'm happy to look and test a PR for this.

**Comment by jtheller** [comment]
Here is a short clip showing the problematic behavior, notice around 10s when the brightness value is 1 the percentage shown in Home app goes all the way to 100%.

https://user-images.githubusercontent.com/26282802/235045009-b6c78a33-ab00-49ad-8b70-84d567fa1208.mov
