### ISSUE TITLE
[Feature] TuYa ZN231392 - Valve service instead of Switch

### ISSUE THREAD

**Issue by mrmaximas** [itavero/homebridge-z2m#710]
### Problem description

I have some TuYa ZN231392 valves supported by Z2M https://www.zigbee2mqtt.io/devices/ZN231392.html
Zigbee Model TS0001
Zigbee Manufacturer _TZ3000_iedbgyxt
Description Smart water/gas valve
It is possible to change service to Valve instead of Switch in Homekit for this device?
Thanks!

**Comment by mrmaximas** [comment]
hi! what about my question?

**Comment by itavero** [comment]
> I will have a hard time configuring my almost hundred devices connected via zigbee2mqtt but it looks like I have no other choice.

You can simply exclude the few devices where you want different behavior in homebridge-z2m and only use homebridge-mqttthing for the others. It's not an all or nothing situation.

An alternative is learn to program in typescript and open up a PR to add this. I also learned typescript for the sole purpose of making this plugin.

> development and support for this plugin seems to be finished.

To be honest, all the devices I use myself are supported (or at least the services I care about in HomeKit are).
So in a way, you are correct about development from my own perspective.
However, I still like to work on the plugin. It's just that it has a lower priority than my daytime job, my family (which expanded last year), chores around my house and some of my other hobby projects.

With regards to support, whenever someone sends me a question, I try to answer it ASAP.
It's however sometimes difficult to keep track of all the channels were people ask questions, so stuff gets missed for sure.

As a sidenote, I wouldn't be surprised if someone would develop an Zigbee2Matter in the near future. If I really had a lot of time on my hands, I think I should be investing it in such a project as that's where the future is heading.
