### ISSUE TITLE
[Device] Aqara Curtain Controller B1

### ISSUE THREAD

**Issue by Starochev** [itavero/homebridge-z2m#74]
How can i add Aqara B1 to homebridge? Is it possible only through aqara gateway? I got Xiaomi Gateway 3.

**Comment by itavero** [comment]
@Starochev Can you please provide the answers to the questions asked in the template?

**Device description**
Which device would you like to be supported in this plugin?

**Supported in Zigbee2MQTT?**
Is this device already supported by Zigbee2MQTT / zigbee-herdsman-converters?
If this is NOT the case, please add support for the device there first.
Read there manual on [How to support new devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html) for more information.
If this is the case, please provide the version in which support is present/added.

**Device model / Exposes information**
Provide the device model (also known as [exposes information](https://www.zigbee2mqtt.io/information/exposes)) for this particular device, as published to `zigbee2mqtt/bridge/devices` by Zigbee2MQTT.

**Missing features/functionality**
Please describe the features/functionality of this device that are currently not exposed to HomeKit via this plugin.

**Suggested services and characteristics**
For each of the missing features, please mention to which HomeKit Services and Characteristics it should be mapped.
The [Homebridge Plugin Development documentation](https://developers.homebridge.io/) provides a nice overview of the standard HomeKit services and characteristics.
Note that some manufacturers also use custom services and characteristics (the Elgato Eve products for instance), which could also be mimicked if they have been reverse engineered.

**Comment by itavero** [comment]
I reckon you mean the [Xiaomi ZNCLDJ12LM](https://z2m.dev/devices/xiaomi/zncldj12lm.html) curtain motor. This is supported by Zigbee2MQTT and should also work with this plugin, providing both a Window Covering service as well as battery information.

Any particular issues you are facing?

**Comment by Starochev** [comment]
Yes, it’s about Xiaomi ZNCLDDJ12LM.
After installing the plugin Aqara B1 doesn’t added automatically to my devices list. What kind of information i need to add Aqara B1? For example when i was addin’ roborock vacuum cleaner, i extracted wi-fi token for it

**Comment by itavero** [comment]
You only have to configure the MQTT server the same as it is configured in your Zigbee2MQTT installation.

If it still doesn't appear, I would first check if Zigbee2MQTT is working correctly and if the device is paired successfully with your Zigbee adapter.

If everything on the Zigbee2MQTT side of things looks okay, then I'd suggest to turn on debug logging in Homebridge and check the logs. Perhaps the plugin ran into some error, which should be visible in the logs.

**Comment by Starochev** [comment]
In ZigBee2MQTT i added 1 device with friendly name "Curtain".
I installed mqttthing and added accessory "Window Covering" with name "Curtain_MQTT". It appeared in Homekit Devices list, but i cant control it. Which values i need to enter in MQTT Topics? Or i must configure ZigBee2MQTT plugin values?

**Comment by itavero** [comment]
MQTT Thing is a totally different Homebridge plugin. This is the repository of homebridge-z2m.

**Comment by Starochev** [comment]
I need to install some dedicated MQTT Server Homebridge plugin (For example MQTTThing, MQTT Broker, etc) and configure it for z2m to work, did I get it right? Or z2m homebridge plugin already has server and working as standalone solution?
I installed z2m plugin in homebridge and now figuring out what to do next, to add Aqara B1 Curtain Controller to Homebridge -> Apple HomeKit.

**Comment by itavero** [comment]
I'm not sure if there is a plugin that will spin up a MQTT message broker within Homebridge for you. There's no MQTT broker included in this plugin. Personally I use mosquitto.

Besides that you also need to have Zigbee2MQTT installed and configured to use that same message broker.

These [requirements](https://z2m.dev/install.html#requirements) are mentioned in the installation instructions.
I would suggest to with setting up Zigbee2MQTT, by following their [Getting started](https://www.zigbee2mqtt.io/#getting-started) steps.

**Comment by itavero** [comment]
As I've gotten several questions over the past week on how to setup the plugin, I've tried to make it a bit more clear what should be installed before the plugin can be used.
Hopefully this also helps you: [Getting started](https://z2m.dev/install.html)

**Comment by itavero** [comment]
Marking this issue as `stale` as there is no further action. It should automatically close in a couple of weeks if no more responses come in.
