### ISSUE TITLE
[Bug] Is it normal that zigbee2mqtt is not working after using this plugin?

### ISSUE THREAD

**Issue by Aekung** [itavero/homebridge-z2m#75]
**Describe the bug**
I am very new to Zigbee2mqtt and I found that after using this plugin, the zigbee2mqtt log never logged further more when checking this command

`cat /opt/zigbee2mqtt/data/log/2021-02-21.18-05-28/log.txt`

I tried this command

`cd /opt/zigbee2mqtt && npm start`

and it returns error with

`Zigbee2MQTT:error 2021-02-21 20:14:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-21 20:14:32: Failed to start zigbee
Zigbee2MQTT:error 2021-02-21 20:14:32: Exiting...
Zigbee2MQTT:error 2021-02-21 20:14:32: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at Znp.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)`

After searching on the internet, I found that this error occurs when another program is already using (and thus locking) the adapter. So is it because homebridge-z2m is running that the zigbee2mqtt doesn't seem to be running anymore?

If that is the case, will I still be able to add the zigbee device the way instructed in zigbee2mqtt? Or this plugin should be conflicting with zigbee2mqtt at all?

This might be a noob question but I'm so sorry since I'm very new to Zigbee2mqtt.

Thanks in advance.

**Comment by itavero** [comment]
My gut feeling says that there might be something else using the serial port.
I can't imagine that this would be caused by this plugin though, as it only communicates via MQTT.

I'd suggest asking for help on the Zigbee2MQTT Discord server.

**Comment by Aekung** [comment]
> My gut feeling says that there might be something else using the serial port.
> I can't imagine that this would be caused by this plugin though, as it only communicates via MQTT.
> 
> I'd suggest asking for help on the Zigbee2MQTT Discord server.
> 
> With regards to your question on adding devices: you only have to add devices to Zigbee2MQTT. After a successful pairing, they should automatically appear in Homebridge.

Thanks for the reply.

I got it working somehow after a reboot of the raspberry pi.

Again, thank you for your fast respond.

**Comment by itavero** [comment]
Good to hear. Enjoy!
