### ISSUE TITLE
Problem with Aqara Wireless Switches and TRADFRI ON/OFF switch.

### ISSUE THREAD

**Issue by Damianod27** [itavero/homebridge-z2m#765]
### Describe the bug

Hi. I don't know why, but three shortcut keys stopped working at the same time today, namely two Aqara wireless switches and one TRADFRI ON/OFF switch. Strangely enough, the temperature sensors in the Aqara wireless switch work properly, but the switches themselves do not respond. They are visible in Homekit. I had a second Micro SD card with a clean Homebridge system and Zigbee2MQTT. I launched it and added one of the Aqara shortcut keys and it turned out that the problem was identical, i.e. the temperature sensor worked properly but the switch did not. I didn't change anything in the system. As I wrote, the same thing happens on the new system. What could be the problem?

![Zrzut ekranu 2023-11-26 204157](https://github.com/itavero/homebridge-z2m/assets/79320859/c7792128-a064-4249-9cb2-e7f1cfc3c1f6)
![IMG_2404](https://github.com/itavero/homebridge-z2m/assets/79320859/52ab8ab8-7089-4034-b782-38752e4565d3)

![Zrzut ekranu 2023-11-26 204219](https://github.com/itavero/homebridge-z2m/assets/79320859/58bf0f04-591d-4dda-bc01-d44340c8788b)
![IMG_2405](https://github.com/itavero/homebridge-z2m/assets/79320859/2b791c1e-39e1-4562-a22e-639668fe48ac)

### This plugin

1.9.2

### Homebridge

1.7.0

### Zigbee2MQTT

1.33.2

### Homebridge Config UI X (if applicable)

4.53.0 or 4.52.3

**Comment by itavero** [comment]
What is the mapping shown for these devices in the Homebridge log when it starts?

Do you see updates for these devices in the Zigbee2MQTT front-end?
Do you see the action value change when you press a button?

**Comment by itavero** [comment]
In the [Zigbee2MQTT frontend](https://www.zigbee2mqtt.io/guide/configuration/frontend.html) or by looking at the MQTT messages (with something like MQTT Explorer).

Just to be clear: the issue you are facing is that no actions are triggered in HomeKit when you press the buttons? If not, please clarify what's problem is (expected vs actual behavior).

**Comment by Damianod27** [comment]
@itavero The strange thing is that it only applies to these devices. The rest works fine. I didn't change anything in the system. The second strange thing is that the temperature sensors still transmit the correct value and change with the Aqara Button.

As you can see in the photos I sent, the switches do not respond.

![a1](https://github.com/itavero/homebridge-z2m/assets/79320859/cf35ec05-cd3e-4b57-b27c-573845218e59)
![a2](https://github.com/itavero/homebridge-z2m/assets/79320859/4da3edd4-16b6-4357-8a65-f68a5ed461ba)

**Comment by Damianod27** [comment]
@itavero Everything is OK in MQTT Explorer. See the photo. I also reconfigured the Ikea Button as you can see in the photo.
![c1](https://github.com/itavero/homebridge-z2m/assets/79320859/f1da600d-1fd8-438a-b30d-eabfe0dd2a43)
![c2](https://github.com/itavero/homebridge-z2m/assets/79320859/cd9f19ed-20f7-4a0a-89bf-f465f8bb2fce)

**Comment by Damianod27** [comment]
@itavero The problem resolved itself after a few hours. In my opinion, it must have been the fault of Apple's servers. As if these switches did not see the accessory center without which they cannot function. Thanks for the help
