### ISSUE TITLE
HOOBS issue [Bug] 

### ISSUE THREAD

**Issue by galzil** [itavero/homebridge-z2m#8]
The plugin doesn't start, The Error message is:
`The requested platform "zigbee2mqtt" was not registered by any plugin.
Your config.json is requesting the platform "zigbee2mqtt" which has not been published by any installed plugins.`

I've found a related issue [here ](https://github.com/hjdhjd/homebridge-myq2/issues/63)stating that a simple fix is changing
`api.registerPlatform(PLATFORM_NAME, ScreenLogicPlatform)`
to
`api.registerPlatform("homebridge-z2m", PLATFORM_NAME, ScreenLogicPlatform)`

**Versions used**
 - This plugin: 0.0.5
 - Homebridge - HOOBS - 3.2.6
 - Zigbee2mqtt - 1.14.1
 - Homebridge Config UI X (if applicable)

**Comment by itavero** [comment]
I don't use HOOBS, are you able to make this change, verify it and open up a PR?

Maybe also open up a issue on homebridge/homebridge-plugin-template as this call is part of their template.

**Comment by galzil** [comment]
I'll try to see if I can so it myself, never done it before.
I'll also open an issue there, thanks.

**Comment by itavero** [comment]
I might have some time next weekend to look into the suggested change and possibly apply it.
If so, I'll update you via this issue so you can maybe verify the change.

**Comment by itavero** [comment]
Actually had some time now. The suggested change is applied in the `master` branch. Can you give this a try?

The [README describes how to test changes that have not yet been released](https://github.com/itavero/homebridge-z2m#testing-the-latest-changes).

**Comment by itavero** [comment]
@galzil Will you be able to test this? I see no negative side effects in my setup, but I'm not sure if this actually solves the problem for your HOOBS setup.

**Comment by galzil** [comment]
@itavero for some reason the HOOBS plugin db is not updated, I can only install via the Web gui and it still shows an older version

**Comment by itavero** [comment]
The change is not released yet, as indicated above. I wasn't aware that you cannot run `npm` commands on a HOOBS installation (never used it myself).
I guess I'll just have to include it in the next release then and hope it works for you.

**Comment by nferro** [comment]
Any idea when next release is coming?

**Comment by itavero** [comment]
I'll see if I can make some time later this week to verify the `master` branch again and release it. "Unfortunately" I've been rather busy with some other personal projects in my spare time  😉

**Comment by itavero** [comment]
FYI: relates to homebridge/homebridge-plugin-template#11

**Comment by galzil** [comment]
This is a Hoobs issue, they need to update their api. 
Meanwhile, it is possible to install the plugin and then manually update the index.js file accordingly

**Comment by itavero** [comment]
I have just released version v0.0.6 with the change suggested earlier. I hope that prevents you from having to do the manually change.
Hopefully it doesn't break anything for other installations ;)

Closing this issue for now for the reason you mentioned (it's a HOOBS issue, even though I tried to solve it here).
