### ISSUE TITLE
Ikea SOMRIG Switch activities not reaching Homebridge [Bug] 

### ISSUE THREAD

**Issue by ielliott75** [itavero/homebridge-z2m#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Device is visible in Home app, and i can configure actions for what to do when a button gets pressed etc. I can also see the actions on the MQTT topic, but when i press the buttons the actions don't ever reach Homebridge or the Homekit app from what i can tell.

### Related devices

https://www.zigbee2mqtt.io/devices/E2213.html#ikea-e2213

### Related Devices

Ikea SOMRIG Switch

### Steps To Reproduce

**Zigbee2MQTT shows the events being converted to MQTT actions:**

Received Zigbee message from 'NewSwitch', type 'commandAction1', cluster 'tradfriButton', data '{"data":0}' from endpoint 2 with groupID 0
MQTT publish: topic 'zigbee2mqtt/NewSwitch', payload '{"action":"2_initial_press","battery":100,"linkquality":33,"update":{"installed_version":16777248,"latest_version":16777248,"state":"idle"},"voltage":1500}'

Received Zigbee message from 'NewSwitch', type 'commandAction3', cluster 'tradfriButton', data '{"data":0}' from endpoint 2 with groupID 0
MQTT publish: topic 'zigbee2mqtt/NewSwitch', payload '{"action":"2_short_release","battery":100,"linkquality":21,"update":{"installed_version":16777248,"latest_version":16777248,"state":"idle"},"voltage":1500}'

**Using MQTT Client i can see the actions being pushed to the MQTT topic:**

Topic: zigbee2mqtt/NewSwitchQoS: 0

{"action":"2_initial_press","battery":100,"linkquality":42,"update":{"installed_version":16777248,"latest_version":16777248,"state":"idle"},"voltage":1500}

{"action":"2_short_release","battery":100,"linkquality":30,"update":{"installed_version":16777248,"latest_version":16777248,"state":"idle"},"voltage":1500}

### This plugin

1.11 beta 3

### Homebridge

1.1.5

### Zigbee2MQTT

1.35.1

**Comment by itavero** [comment]
Do you see a mapping for this device in the Homebridge logs, when Homebridge starts?
If not, can you turn on debug logging and check if you see any messages related to this device?

**Comment by ielliott75** [comment]
I think so...

![Screenshot 2024-01-09 at 19 04 00](https://github.com/itavero/homebridge-z2m/assets/155854398/81272b02-bb5d-4a53-b7cc-8ebdaf41ec79)

**Comment by ielliott75** [comment]
With Debug turned on i can also see the following when i press the button on the switch:

[1/9/2024, 7:14:12 PM] [zigbee2mqtt] Handled device update for NewSwitch: {"action":"1_initial_press","battery":100,"linkquality":30,"update":{"installed_version":16777248,"latest_version":16777248,"state":"idle"},"voltage":1500}
[1/9/2024, 7:14:13 PM] [zigbee2mqtt] Handled device update for NewSwitch: {"action":"1_short_release","battery":100,"linkquality":66,"update":{"installed_version":16777248,"latest_version":16777248,"state":"idle"},"voltage":1500}

**Comment by itavero** [comment]
> Is it possible that there isn't a match, because **dots_1_initial** or **dots_1_initial_press** is actually **1_initial_press** in the action?

It looks as if the exposes information provided by Zigbee2MQTT does not match the values it actually sends. Seems like a bug in Zigbee2MQTT or zigbee-herdsman-converters.

Sometimes devices have a `legacy` configuration option that can cause this, but I don't believe I saw that on the Zigbee2MQTT device page.

Anyway, I would not expect the accessory to not show up because of this.
Did you try the _Eve_ app to see if you could find the stateless programmable switch service with that?

**Comment by ielliott75** [comment]
I believe you are correct it seems to be a converter issue. I've raise an issue over there.
