### ISSUE TITLE
[Feature] change sensor type

### ISSUE THREAD

**Issue by bubez81** [itavero/homebridge-z2m#955]
### Problem description

I need to change from water_leak to occupancy or presence

### Suggested solution

maybe a sort of customization device based?

**Comment by itavero** [comment]
You can provide modified exposes information for this particular device to make it appear as a occupancy sensor.

https://z2m.dev/config.html#devices

**Comment by bubez81** [comment]
Hello. thank you for the answer! Can you please provide me an example? 
I tried this but nothing changed:

```
       {
            "id": "0x00158d0009f3fb61",
            "type": "binary",
            "name": "occupancy",
            "label": "Occupancy",
            "property": "occupancy",
            "access": 1,
            "exclude": false
        },
```

**Comment by itavero** [comment]
Can you share the current `exposes` information for this specific device?

You can find it on MQTT topic `zigbee2mqtt/bridge/devices`

**Comment by bubez81** [comment]
this?:

```
{
    "battery": 100,
    "battery_low": false,
    "device_temperature": 21,
    "linkquality": 180,
    "power_outage_count": 11,
    "tamper": false,
    "trigger_count": 0,
    "voltage": 3045,
    "water_leak": true
}
```

**Comment by itavero** [comment]
That last one, indeed.

You can copy the `exposes` part to the plugin configuration (see link above).
If you change just the `name` (**NOT** the `property`) from water leak to `occupancy`, that should work.

**Comment by bubez81** [comment]
Thank you, it works!
