### ISSUE TITLE
[Feature] Expose power, voltage, current to Xiaomi SP-EUC01

### ISSUE THREAD

**Issue by ratsoid** [itavero/homebridge-z2m#96]
It would be great to get power consumption support for the Xiaomi SP-EUC01

Currently, only Switch and Temperature are exposed: https://z2m.dev/devices/xiaomi/sp-euc01.html

The device exposes switch (state), power, energy, temperature, voltage, current, linkquality
https://www.zigbee2mqtt.io/devices/SP-EUC01.html

I use a TP-LINK HS110 to monitor the power consumption of the laundry machine. I have an automation set-up for the TP-LINK Outlet that monitors the watt usage and I'd love to get rid of the Kasa ecosystem

https://i.imgur.com/AasYYiW.png

**Comment by itavero** [comment]
So far the only device I've seen that expose this information as well, are of type `switch` or `light`. I'd suggest to make a generic implementation that can be integrated in the two `ServiceHandler` classes used for these different types.

**Comment by ratsoid** [comment]
I can't say if that's what I'm after since I'm not in the Elgato Eve Energy, but I do use the Eve app (now Home+ mostly), and I want the ability to measure the outlet characteristics.

I have seen outlets that do give a lot more info (voltage, watts, total consumption). One example would be TP-Link HS110. I use the power consumption characteristic in Eve/Home+ app to trigger automations.
However, my thought is that homebridges-z2m should add outlets as outlet accessories, for HomeKit consistency. Although zigbee2mqtt does share it as a switch, I think the plugin needs to interpret it as an outlet. Does that make sense? I think the characteristics that I'm after aren't attached to switches but to outlets.

P.S. Just to reiterate, the automations regarding power consumptions can't be done through the Home app since they're not available there, but through other HomeKit management apps

**Comment by itavero** [comment]
The characteristics are non-standard and I don't expect any issues when they are added to a light or switch accessory.

I don't know the exact difference in the Home app between a Switch and an Outlet. For my particular use case the Switch service works just fine. I have an [IKEA outlet](https://z2m.dev/devices/ikea/e1603_e1702.html) that uses the switch service. I use it to control a "dumb" light and it works exactly right for my use case (I can even select in the Home app that it is a light).

By the way, there is a different feature request about selecting alternative services for certain devices

**Comment by Leseptiemeciel** [comment]
@ratsoid have you found a way to get power reading?

**Comment by itavero** [comment]
If someone would be able to give #1155 a go on their system as well, that would be great.

(You can check out the branch, run `npm ci`, `npm build` and lastly `npm link` to do so).

**Comment by itavero** [comment]
This is now released in [v1.11.0-beta.11](https://github.com/itavero/homebridge-z2m/releases/tag/v1.11.0-beta.11) 🚀
